### ISSUE TITLE
Create commands for login and logout in cypress 

### ISSUE THREAD

**Issue by mdshamoon** [ColoredCow/portal#1000]
**Describe the task**
Create commands for login and logout in cypress so that it can be reused in multiple test files.

**Expected behavior**
We should have two commands in cypress namely- `login` and `logout` that can be called in any test case and perform the relevant actions.

**References**
https://docs.cypress.io/api/cypress-api/custom-commands

**Comment by am-Anmol** [comment]
I'll be covering this issue in this PR #999
