### ISSUE TITLE
Update Domain list on the portal

### ISSUE THREAD

**Issue by am-Anmol** [ColoredCow/portal#1001]
**Describe the task**
Add all domains which are existing on the ColoredCow website career page.

**References**
- Portal:
![image](https://user-images.githubusercontent.com/48876126/133610924-a03474e0-4257-4879-b1b9-b0ee76adfcaa.png)
- ColoredCow Website:
![image](https://user-images.githubusercontent.com/48876126/133611001-4f94fee2-53f2-4608-8616-efe3ee9ec5da.png)

**Comment by rathorevaibhav** [comment]
This looks great. Closing.
