### ISSUE TITLE
Add a guideline for variable naming convention

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1003]
**Describe the task**
Add a guideline for the naming conventions followed in PHP, blade, js, css and vue file

**Expected behavior**
Add a documentation file.

**References**
JS:
    className - snake-case
    idName - camelCase
PHP:
    variable name - camelCase
    function name - camelCase
    class name - TitleCase
Blade:
   variable name - camelCase
   className - snake-case
   idName - camelCase

**Comment by kickb71** [comment]
@GauravGusain98  Can you link the branch name documentation here it will be helpful

**Comment by srivastava-jyoti** [comment]
Closing.
