### ISSUE TITLE
Make the installation process page easier to understand

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#1006]
**Describe the task**
Make the installation Guide/Page more easier to install the portal more easily 

**Expected behavior**
- [ ] Show the output of each code for (Composer and NPM install)
- [x] Tell the reader where to place the portal project - not to be worked on. Being fixed in another issue #1028
- [x] Tell them to open system files in admin mode

**Comment by bharatsingh100** [comment]
Should we also add instructions for username and password required to login to `portal.test`

**Comment by gautam071** [comment]
@bharatsingh100 Great Idea Thanks. I will try to update it

**Comment by rathorevaibhav** [comment]
The output of composer install and npm install is not there yet. But closing this. We can tackle it later.
