### ISSUE TITLE
Google sheet integration and getting effort hours for each person in the project (JS snippet)

### ISSUE THREAD

**Issue by mdshamoon** [ColoredCow/portal#1008]
Completed:

- [x] Created a command `sync:effortsheet` that gets all the active projects and fill an entry for each user in the project in the table `project_team_member_effort`
- [x] Added the command to run each day at 10 pm with a CRON job

Left to do:

- [x] Calculate the effort for the current day. Following conditions needs to be checked for this:
    - Check if there is a last entry for the project member. If there is an entry:
        - Check if the month has changed or not
            - If the month has changed the actual hours will be the total hours we have in the effortsheet for the current month
            - If the month did not changed then calculate the effort for current entry by subtracting the total effort from previous entry
    - If not
        - Actual effort will be the total effort

**Comment by GauravGusain98** [comment]
This is implemented. Closing this now.
