### ISSUE TITLE
Job Opportunity Seeder

### ISSUE THREAD

**Issue by am-Anmol** [ColoredCow/portal#1015]
**Describe the task**
- Create a seeder for creating 3 job opportunities for all domains `(hints : hr_jobs table)`:
  -  `Engineering => Software Developer`
  -  `Designer      => Product Designer`
  -  `Marketing    => Data Researcher`
- Create a seeder for job rounds with their respective `job_id` and `round_id`. `(hints : hr_jobs_round table)`

**Expected behavior**
- [ ] Seeder for creating job opportunities.
- [ ] Seeder for assigning their respective hr_id and round_id in jobs round.

**References**
![image](https://user-images.githubusercontent.com/48876126/134129648-7f07db03-8006-4c08-8e0d-af90cce1a7ae.png)

**Comment by rathorevaibhav** [comment]
Looks complete. Closing.
