### ISSUE TITLE
Users Seeder

### ISSUE THREAD

**Issue by am-Anmol** [ColoredCow/portal#1018]
**Describe the task**
Update users table seeder to add a new user with followings details:
 - email => 'john@example.com',
 - name => 'John Doe',
 - password' => Hash::make('12345678'),
 - provider' => 'default',
 - provider_id => 'default'

**Expected behavior**
- [x] Update users table seeder for add new users.

**References**
There is already one seeder that exists for the users table, take help from the previous entry.

**Comment by himanshu007-creator** [comment]
Hi, I would like to work on this issue!, please assign me

**Comment by GauravGusain98** [comment]
@am-Anmol @vipulgoyal006 I have merged a PR related to seeders today. There we have user seeder that create new entry for a user whenever we run the seeder command. To run that you can use the command `php artisan module:seed User`

I think we can close this issue as it is not needed now.

**Comment by am-Anmol** [comment]
> @am-Anmol @vipulgoyal006 I have merged a PR related to seeders today. There we have a user seeder that create new entry for a user whenever we run the seeder command. To run that you can use the command `php artisan module:seed User`
> 
> I think we can close this issue as it is not needed now.

@GauravGusain98 For Cypress Testing I need a minimum of 2 users in the UserSeeder, I think that requires linked PR to this issue is to be merge.

**Comment by GauravGusain98** [comment]
> > @am-Anmol @vipulgoyal006 I have merged a PR related to seeders today. There we have a user seeder that create new entry for a user whenever we run the seeder command. To run that you can use the command `php artisan module:seed User`
> > I think we can close this issue as it is not needed now.
> 
> @GauravGusain98 For Cypress Testing I need a minimum of 2 users in the UserSeeder, I think that requires linked PR to this issue is to be merge.

@am-Anmol The seeder that I am referring to creates 3 users at a time in the database. I think that'll work in this case.

**Comment by am-Anmol** [comment]
> > > @am-Anmol @vipulgoyal006 I have merged a PR related to seeders today. There we have a user seeder that create new entry for a user whenever we run the seeder command. To run that you can use the command `php artisan module:seed User`
> > > I think we can close this issue as it is not needed now.
> > 
> > 
> > @GauravGusain98 For Cypress Testing I need a minimum of 2 users in the UserSeeder, I think that requires linked PR to this issue is to be merge.
> 
> @am-Anmol The seeder that I am referring to creates 3 users at a time in the database. I think that'll work in this case. You can try with that once.

@GauravGusain98 Ok I try it again
