### ISSUE TITLE
Updates to installation guideline

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1028]
**Describe the task**
The installation guideline can be tricky to understand in some places. We need to update those steps.

**Expected behavior**
Updates to installation guideline
- [x] Add a step at the beginning to go through the "Pre-requisites" guide if you haven't. The pre-requisites doc should be linked like it's there on the main README
- [x] Add a step before cloning to switch to the right directory based on XAMPP, MAMP, or WAMP (all three should be mentioned)
- [x] Correction to the cloning URL `git clone https://github.com/coloredcow/portal`
- [x] Add command for copying env. `cp .env.example .env`
- [x] Seeders step, the steps with "In case you...` should be prefixed with `(Optional)` text. Like:
    ```
     (Optional) In case you want to run a specific seeder class, use the --class option:
    ```

**Comment by carrisunrio** [comment]
@rathorevaibhav the link to the "prerequisites guide" in the portal/installation.md shows Error 404 Page Not Found.

**Comment by rathorevaibhav** [comment]
@carrisunrio possible for you to fix it?

**Comment by carrisunrio** [comment]
@rathorevaibhav yes, please open this again, i will make a PR
