### ISSUE TITLE
Change application received graph from line chart to bars

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1033]
**Describe the task**
Line chart is a bit difficult to follow
![image](https://user-images.githubusercontent.com/12053186/134758325-2c5edd8e-160d-4f80-b688-6eba3d3fd7c0.png)

**Expected behavior**
- [x] Show bars instead of line chart
- [x] Date format to be "Sep 25, Sep 26, Sep 27" etc

**Comment by vipulgoyal006** [comment]
I have implemented the bar graph functionality in the code. Please refer to the branch  'feature/reports_bar_graph '. Unable to resolve the second issue of the Date Format.

**Comment by srivastava-jyoti** [comment]
@rathorevaibhav tested this on Uat. It is working fine now bar graphs are shown instead of line graph and the formats of dates are also same as mentioned in the issue.

**Comment by rathorevaibhav** [comment]
Looks good. Closing.
