### ISSUE TITLE
Recruitment menu UI issues

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1081]
**Describe the task**
Recruitment menu numbers are overlapping on the icon
![image](https://user-images.githubusercontent.com/12053186/136667245-d8044c8c-1d4f-41c0-9416-fd4f054bb3a3.png)

**Expected behavior**
- [ ] Numbers shouldn't overlap the icons. Increase the spacing if the number is high.

**Comment by P4NK4J** [comment]
The UI for the recruitment submenu is not fixed yet, hence reopening the issue.
![image](https://user-images.githubusercontent.com/35001775/144969006-90507b4c-8225-4c30-890d-44d82dfb90f3.png)

**Comment by dsajwan2020** [comment]
The issue is fixed refer screenshot 

![image](https://user-images.githubusercontent.com/96309135/161371069-b4596700-74a0-44e9-bcaa-fa77a4b2191a.png)

**Comment by Ayush8923** [comment]
This issue is complete. Closing it.
