### ISSUE TITLE
Recruitment list sort assignee filter

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1082]
**Describe the task**
The names in the assignee filter should be sorted alphabetically. This will help to find the person easily.
![image](https://user-images.githubusercontent.com/12053186/136667357-ac077b61-6a49-4141-a357-24866dab0f38.png)

**Expected behavior**
- [ ] Sort names alphabetically in the list

**Comment by srivastava-jyoti** [comment]
This works fine.Closing
