### ISSUE TITLE
Empty status for new job applications

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1088]
**Describe the task**
For new applications, we used to have a tag automatically assigned as "New Application". It is not showing up anymore. The new applications do not have that tag/status.
![image](https://user-images.githubusercontent.com/12053186/136755622-da4d20a6-0579-4895-9933-04caf83ee187.png)

**Expected behavior**
- [ ] The new applications should have the "New Application" tag that has green background.

**Comment by P4NK4J** [comment]
@rathorevaibhav I think we should be good to close this issue now, since the issue is resolved on production after migration. Let me know your thoughts.
