### ISSUE TITLE
Save Applicant WhatsApp Optin Time 

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#1113]
**Is your feature request related to a problem? Please describe.**
We are integrating WhatsApp services in EP. For that, we need to save the Applicant optin in the DB so that we can communicate with them. 

**Describe the solution you'd like**
1. Create a new migration and add a field wa_optin_at in the applicant table. The type of this column will be timestamp and by default nullable.
2. Add a new field in the new application form (in the portal) as well. 
![image](https://user-images.githubusercontent.com/10670690/137671785-19bed8ed-75a1-48ba-828c-0629f9f7ebc1.png)

**Comment by srivastava-jyoti** [comment]
Closing
