### ISSUE TITLE
Project management menu item display based on permissions

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1114]
**Describe the task**
If user doesn't have `projects.view` permission and neither `clients.view` permission, the project management tab shouldn't show up at all. Right now it shows blank dropdown.
![image](https://user-images.githubusercontent.com/12053186/137742423-f306e942-c0dc-4746-9f80-d9a3b21288af.png)

**Expected behavior**
The project management tab shouldn't show up if both `projects.view` and `clients.view` permissions are not given.

**Comment by srivastava-jyoti** [comment]
Closing.
