### ISSUE TITLE
All the project listing pages show throw 403 if permission fails

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1117]
**Describe the task**
All the project listing pages show throw 403 page if permission fails if user has `projects.view` permission. Right now it says the message in the table but I can still see the tabs, and count of projects which is not right.

**Expected behavior**
All project pages should show 403 page if `projects.view` permission isn't there
![image](https://user-images.githubusercontent.com/12053186/137748733-d62e7561-3b57-49bd-8a24-6c55468281f2.png)

**Comment by deepankar-sajwan** [comment]
Closing as issue is fixed
