### ISSUE TITLE
Getting error on FTE page when two users are assigned to a project

### ISSUE THREAD

**Issue by mdshamoon** [ColoredCow/portal#1130]
**Describe the bug**
Getting error on FTE page when two users are assigned to a project and one of them have the efforts present while the other one does not.

**To Reproduce**
1. Assign two people to a project
2. Add effort for one of the members
3. Now open the FTE screen
4. It should give an error

**Expected behavior**
There should be no error.

**Screenshots**
![image](https://user-images.githubusercontent.com/32592458/138243066-b3113043-cbba-456a-93d9-bf2b37320275.png)

**Comment by deepankar-sajwan** [comment]
The issue has been fixed hence closing it
