### ISSUE TITLE
Minor feedbacks on project team member list

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1138]
From #1120

Minor feedbacks: 

1. There should be a bottom margin when team member photo move to the next line 
![image](https://user-images.githubusercontent.com/32592458/138692882-5f5dccd4-ac79-4288-8e5e-1b15cd314a68.png)

2. The designation and name should either be on a single line or on separate lines. One part of designation on one line and the second on another line looks a bit weird.
![image](https://user-images.githubusercontent.com/32592458/138693047-c4bda793-4d08-40a3-9175-2e73c58f2b99.png)

_Originally posted by @mdshamoon in https://github.com/ColoredCow/portal/issues/1120#issuecomment-950865189_

**Comment by suntwalriya** [comment]
I am having issues, with the avatar placement as when I add new avatars, I am unable to see them updated on the UI. I have fixed the tooltip issue.

**Comment by srivastava-jyoti** [comment]
This works fine. Closing.
