### ISSUE TITLE
Improve UI for infrastructure card on dashboard

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1145]
**Describe the task**
We need to improve the user interface for dashboard cards for infrastructure costs. Right now it's looking difficult to understand.
![image](https://user-images.githubusercontent.com/12053186/139257606-d1f2d3be-74f2-4c1c-a179-aed3feea08ac.png)

**Expected behavior**
Create four lines inside the card. Each line should look something like this:
![image](https://user-images.githubusercontent.com/12053186/139257419-66f28c68-c871-4cab-95b3-3264a273a0e9.png)

**Comment by srivastava-jyoti** [comment]
These are incomplete.

**Comment by srivastava-jyoti** [comment]
This is incomplete.

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
