### ISSUE TITLE
Add currency to finance numbers in invoice page

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1146]
**Describe the task**
Add currency sign to finance invoice page
![image](https://user-images.githubusercontent.com/12053186/139257869-e245b93f-a2bd-478f-91a5-fbb2bad76c89.png)

**Expected behavior**
The above text should look like this:
```
Current Exchange rates ($1): ₹74.79
Receivable amount (for current filters): ₹1052624.03
```

**Comment by srivastava-jyoti** [comment]
This works fine.Closing
