### ISSUE TITLE
Improve UI for invoice card on dashboard

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1147]
**Describe the task**
We need to improve the user interface for dashboard card for invoice. Right now it's looking difficult to understand.
![image](https://user-images.githubusercontent.com/12053186/139258289-ac6cd9f8-3b89-468a-8c5c-dc3bb6b0d09a.png)

**Expected behavior**
The pending invoice count and label should show up like this
![image](https://user-images.githubusercontent.com/12053186/139257419-66f28c68-c871-4cab-95b3-3264a273a0e9.png)

**Comment by GauravGusain98** [comment]
> Sir on this problem #1147 do I have to show pending invoice count below the "pending invoice" or total pending amount should be shown below "pending invoice"? Are these changes correct which were done by me? <img alt="Invoice" width="218" src="https://user-images.githubusercontent.com/91321534/139441086-3d3df448-49c2-403e-9cc0-0efb08a0cb72.png">

@rathorevaibhav Could you please confirm if this is fine?

**Comment by srivastava-jyoti** [comment]
This is incomplete.

**Comment by Shivam-Samant** [comment]
@srivastava-jyoti Mam what should I do in this issue?

**Comment by dsajwan2020** [comment]
The issue has been fixed refer screenshot for reference

![image](https://user-images.githubusercontent.com/96309135/161959675-485a80a8-66ad-4c8b-bda1-128bc4f71fbe.png)

**Comment by deepankar-sajwan** [comment]
This issue has been fixed
