### ISSUE TITLE
Estimated hours fields should be non required. 

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1159]
**Describe the bug**
On the Edit Project and Add Project page, the `total estimated hours` and `monthly estimated hours` are non-required fields but we are getting an error when we leave these fields empty.

TASKS: 
- [x] Make the above-mentioned fields nullable
- [x] Update the `monthly_estimated_hours` column as nullable in database table

**To Reproduce**
NA

**Expected behavior**
The user should be able to leave these fields empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/54376313/139801739-ef0ead6a-629f-4e0c-9603-03f7342f6a45.png)

![image](https://user-images.githubusercontent.com/54376313/139802213-083c6e6c-8f3a-48d4-bcf3-d2c700f29940.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by srivastava-jyoti** [comment]
This works fine. Closing.
