### ISSUE TITLE
Add amount in words in invoices pages

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#1164]
**Is your feature request related to a problem? Please describe.**
Adding an amount in numbers only may lead to adding an incorrect amount by mistake.  If we have an amount in words also, it will reduce the chances to add an incorrect amount.

**Describe the solution you'd like**
When some add an amount in numbers while creating the invoices. please show the amount in words at bottom of all amount fields. Make the text red, so that it is easily readable.
For Example 
In numbers: INR 100,000
In Words: One lakh only

<img width="1130" alt="Screenshot 2021-11-08 at 11 01 00 AM" src="https://user-images.githubusercontent.com/16541548/140689235-5fc17969-6249-4453-b3e2-e8862bfd1767.png">

**Comment by srivastava-jyoti** [comment]
This is working fine. Closing.
