### ISSUE TITLE
FTE Page showing 500 error on first day of the month

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1169]
**Describe the bug**
On the Project FTE page, for the first day of the month, the Page is broken until the data is updated via cron.

**To Reproduce**
1. Go to the Project FTE page on the first day of the month
2. You will see a 500 error 

**Expected behavior**
We should add a check for null value in the application logic for this case.

**Screenshots**
![image](https://user-images.githubusercontent.com/54376313/140938294-e1fa95b0-6393-4c6f-a67e-9e9bd99be3a2.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
