### ISSUE TITLE
Add a FTE button on the Project detail Page

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1170]
**Describe the task**
Add a button for the FTE page on the project details page. 

**Expected behavior**
Users should be able to go to the project FTE page directly from the Project details page. The button style should be similar to the other button on the page. 

Rough design:

![image](https://user-images.githubusercontent.com/96309135/163544055-6d6a0461-c575-47bf-a1ba-0b1498c3bf44.png)

**Comment by dsajwan2020** [comment]
The FTE button has been added as mentioned in https://github.com/ColoredCow/portal/pull/1172

Refer screenshot
![image](https://user-images.githubusercontent.com/96309135/161991480-bb1158d5-386d-4cad-ae5e-9edd2cc48387.png)

**Comment by deepankar-sajwan** [comment]
closing as task is implemented
