### ISSUE TITLE
Add a back button to redirect user to previous page

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1171]
**Is your feature request related to a problem? Please describe.**
On the Project details page, add a back button similar to the FTE page back button. 

**Describe the solution you'd like**
We need to provide a button for users to redirect to the previous page. 
- [ ] The back button should be able to open the same page along with the filter applied to that page. For example, if the project listing page has `all projects` filters applied, then the back button should redirect the user to project listing page for the `all projects`. 
- [ ] Similar is to be done for the `my projects` filter as well.

Reference image
![image](https://user-images.githubusercontent.com/54376313/140941148-e03d0375-00ed-4f19-83f5-0c1cf781d10b.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by srivastava-jyoti** [comment]
This works fine. Closing
