### ISSUE TITLE
Part:1 Need to add a field to upload  contract file of the project in the project details page

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#1177]
**Issue**
- The original issue #816 

**Describe the task**
- [ ] Create the input field for uploading a file (ref to the image for example and replicate it). 

**References**
![image](https://user-images.githubusercontent.com/73119570/142725111-e3c99a86-b4b9-4b71-b27e-e0f872d53c07.png)

**Comment by dsajwan2020** [comment]
The input field for adding the contract is available,  when adding new project.
Refer screenshot
![image](https://user-images.githubusercontent.com/96309135/161971563-f62b8256-0c4e-4b35-b438-98227c2479ac.png)

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
