### ISSUE TITLE
Part:2 Validate the file in backend

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#1178]
**Issue**
- The original issue #816 

**Describe the task**
- [x] Validate that the submitted file is pdf or not in the backend.

**References**
- Go through the documents if anything is needed about validation (https://laravel.com/docs/8.x/validation).

**Comment by dsajwan2020** [comment]
The check for validating that file is Pdf type is implemented at backend 

Uploaded .doc extension file
![image](https://user-images.githubusercontent.com/96309135/161980615-27f3ed35-97fc-413f-a84a-d5e5af6a2575.png)

Error message is displayed suggesting Upload file of Pdf extension
![image](https://user-images.githubusercontent.com/96309135/161980864-719365b5-9d9f-4b9a-9007-6fa2163b732f.png)

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
