### ISSUE TITLE
Part:3 Create a table for the project contracts

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#1179]
**Issue**
- The original issue #816 

**Describe the task**
- [x] Create a new table in database called ```project_contracts```.
- [x] The columns in the table are:
       - id
       - project_id (Foreign key)
       - contract_file_path
       - timestamps
    
**References**
- If needed go through these docs (https://laravel.com/docs/8.x/migrations)

**Comment by dsajwan2020** [comment]
The table for Project contracts is available

1. Created a Project and uploaded contract file in pdf format
![image](https://user-images.githubusercontent.com/96309135/162205320-093476d1-23e3-4884-95ed-b34dd7741bcd.png)

2. Accessed the database  UAT environment, table for contracts is available
![image](https://user-images.githubusercontent.com/96309135/162205652-e8d2a91a-07d2-463b-a622-c0415938fddd.png)

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
