### ISSUE TITLE
KnowledgeCafe Permissions

### ISSUE THREAD

**Issue by srivastava-jyoti** [ColoredCow/portal#1192]
**Description**
Fix the permissions for the knowledgecafe module.

**Expected behavior**
- [ ] Dashboard "Knowledge Cafe" card should show up only if the user has `knowledgecafe.view` permission.
- [ ] The library dropdown item should be visible if the user has `knowledgecafe.library.view` permission.
- [ ] The weekly dropdown item should be visible if the user has `knowledgecafe.weeklyview` permission.
- [ ] The link for library page should open only if a user has `knowledgecafe.library.view` permission. Otherwise it should show 403 error.
- [ ] The link for weekly page should open only if user has `knowledgecafe.weekly.view` permission. Otherwise it should show 403 error.

**Permissions in KnowledgeCafe**
These will be the permissions in infrastructure:
1. `knowledgecafe.view` with [.view]
2. `knowledgecafe.library.view` with [.view, .create, .update, .delete]
3. `knowledgecafe.weekly.view` with [.view, .create, .update, .delete]

**Comment by dsajwan2020** [comment]
The feature has been implemented

1. Access Library permission to user 

![image](https://user-images.githubusercontent.com/96309135/162574961-244ab9f9-2fb6-4ac1-ab73-5301bc14a4f5.png)

2. User able to access Library and KnowledgeCafe

![image](https://user-images.githubusercontent.com/96309135/162575093-faacde71-7e2b-4d73-a112-366d63fdcdd7.png)


3. Removed Library permission for the user

![image](https://user-images.githubusercontent.com/96309135/162575165-297d932e-8303-41f0-a2d9-7777ada55378.png)

4. Error is displayed on page when accessing KnowledgeCafe library

![image](https://user-images.githubusercontent.com/96309135/162575267-87f4c7e6-6e53-41b0-9bf2-c937d156c9c2.png)

5. Error is displayed on page when accessing KnowledgeCafe weeklydose

![image](https://user-images.githubusercontent.com/96309135/162575304-db55b370-89ea-46e5-929f-3814963ec0bb.png)

**Comment by deepakbarmola** [comment]
Closing as seems completed with the latest applied label and after reading comments and PR associated is merged too.
