### ISSUE TITLE
Phase 1: Project details page

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1194]
**Issue's Linked**
#1196 

**Describe the task**
We need a project health dashboard, which will have all the project details, FTE graph, and health status score. As of now, when we click on a single project from the project listing, it should redirect the users to its details page having information about the project. Currently, on a project item click, the edit project details page opens up.

**Expected behavior**

- [ ] On the project listing, when we click on a project, a page having basic details about the project should open up instead of the **project edit page**. As of now, we can go with a blank page having no information.
- [ ] On the project details page, we would like to have an **edit project button**, which would take users to the project edit screen. Below attached the screenshot for reference (similar to Add new project button).
- [ ] The project details page should have the **navbar, name of the project and edit button** present.

**References**
Project listing page:
![image](https://user-images.githubusercontent.com/35001775/143676105-d92db04a-3417-4e2c-82c6-d4a3936c2168.png)

**Comment by srivastava-jyoti** [comment]
Closing. This is working fine.
