### ISSUE TITLE
Phase 2: Project details page

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1195]
**Issue's Linked**
#1196 

**Is your feature request related to a problem? Please describe.**
We need to create a project details page that will also show the health of the project.

**Describe the solution you'd like**
On the Project details page:
- [ ] Create a section for the project details with the title `Project Details` as shown in the design below
- [ ] `Check FTE` button should open the FTE page (https://uat.employee.coloredcow.com/effort-tracking/project/35)
- [ ] `Open Sheet` button should open the effort sheet URL in the new tab.  
- [ ] If there is no effort sheet URL or any other details available, then just show `Not Available` text.
- [ ] The buttons should have the color code `#6cb2eb`. you can also use `btn-info` class for the color.

![image](https://user-images.githubusercontent.com/54376313/143677375-1c3d235d-6d66-4a55-ae99-297cf7dc697a.png)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Ayush8923** [comment]
This issue is complete. Closing this.
