### ISSUE TITLE
Phase 2:Send mail to client from portal

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#1200]
**Describe the task**
- [ ] Make the sender's email address editable.
        - Add an input field in the model for the default sender email ("finance@coloredcow.com").
        - Add an input field called CC to send email to multiple email addresses (with comma separated).
    
- [ ] Add the validations for the emails in the backend.

**Issues Linked**
#839

**Comment by dsajwan2020** [comment]
Task that are implemented

Make the sender's email address editable.
- Add an input field called CC to send email to multiple email addresses (with comma separated).
  
   Email id in CC section can be added with comma separation

![image](https://user-images.githubusercontent.com/96309135/162369084-b973c4c8-f75b-488b-9620-6038d6ea6428.png)

- Add the validations for the emails in the backend.
  
   Validation check is available for email id 

![image](https://user-images.githubusercontent.com/96309135/162369216-b4c0b708-09c6-48fd-9d15-ec2d3b5993c4.png)

Task not implemented

-Add an input field in the model for the default sender email ("[finance@coloredcow.com](mailto:finance@coloredcow.com)").

Default email finance@coloredcow.com is not available 

![image](https://user-images.githubusercontent.com/96309135/162369546-926b22b1-edd9-463b-93c1-ad6eda4f1928.png)

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
