### ISSUE TITLE
Phase 3: Project details page

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#1202]
**Issue's Linked**
#1196

**Describe the task**
The project details page will have a project health  section that stores the status and details related to the project.. 

**Expected behavior**
- [x] Create a DB migration for the project_health table in the database. 

**References**
- https://laravel.com/docs/8.x/migrations

**Note**
- The design of schema is not ready yet in working on process by @gautam071  
- Once the design of schema is completed it's good to go.

**Comment by gautam071** [comment]
@ColoredCow/team-portal-reviewers Can you go through this schema and confirm it for the table **project_health**. https://docs.google.com/presentation/d/13jk2X6H1pJpkzZYR26edIvrientwLbMCrSi-F5-AAGk

**Comment by dsajwan2020** [comment]
The project_health table is created and is available in the database, please refer screenshot

![image](https://user-images.githubusercontent.com/96309135/162726148-f0dcd4c8-4beb-433e-b2eb-5d03e4bf411b.png)
