### ISSUE TITLE
Setup for the CRM module in the employee portal

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#1205]
**Describe the task**
- [x] The basic needs for CRM needed to be set up in the employee portal. 
             - The new page for CRM.
             - The page should be located in Project Management > CRM
             - Setup the modules for the CRM in the portal code.

**References**
- If any doubt go through this link https://nwidart.com/laravel-modules/v6/introduction

**Similar Issues**
#509, #511

**Comment by dsajwan2020** [comment]
CRM page has been added under the Project Management
