### ISSUE TITLE
Updates to pre-requisites documentation

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1220]
**Describe the bug**
The pre-requisites in documentation need to be updated for the 3rd pointer `Steps on how to connect to MySQL database in your PHPMyAdmin`. The correct path should be `localhost/phpMyAdmin`.

![image](https://user-images.githubusercontent.com/35001775/146139799-8bcc69a3-22b3-4b4d-b6f0-b73fca421a0f.png)

**Comment by dsajwan2020** [comment]
The correct path  localhost/phpMyAdmin is updated in pre-requisites document
Refer screenshot
![image](https://user-images.githubusercontent.com/96309135/161372003-8e3a0f84-62aa-43c8-9916-4eeb0e4a64c0.png)

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
