### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1221]
**Describe the task**
For someone new to Git and GitHub ecosystem, it's difficult to understand the concepts in one go. We should have a contributing guideline that can be helpful for new contributors.

**Expected behavior**
1. Updates on main readme
    1. Create a new section with header "New contributor?"
    2. The body for this section should have "If you are a new contributor, visit our Contributing Guidelines to get started"
    3. The contributing guideline link should be present above.
2. Steps in contributing guideline markdown file
    1. Create a new git branch - should have a bit more details with link of articles on how to create branch.
    2. Make code changes that are needed
    3. Commit and push the branch - more details with relevant links
    4. Make a Pull Request - more details with relevant links

**Comment by dsajwan2020** [comment]
The contributing guideline has been added in GitHub refer screenshot

![image](https://user-images.githubusercontent.com/96309135/161371667-324e30c4-d281-47e5-a086-902dce8d5112.png)

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
