### ISSUE TITLE
Integration testing checks are getting failed.

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1228]
**Describe the bug**
The composer dependencies are throwing error while installing the integration testing environment.

**To Reproduce**
1. Go to any PR with failed integration checks 
2. Click on failed checks and see details
3. Scroll down to the error message

**Expected behavior**
The integration check should work properly.

**Screenshots**
NA

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
NA

**Comment by srivastava-jyoti** [comment]
Closing.
