### ISSUE TITLE
Add a report section in sales Menu

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1232]
**Is your feature request related to a problem? Please describe.**
We need to provide some data studio reports related to sales and marketing. 

**Describe the solution you'd like**
For this we need to perform the below given tasks:
- [ ] Create a blank page with a menu bar and a coming soon banner as provided below. _Please update the text in the banner as per the issue requirements._
- [ ] Also add an `add report` button on the page that opens modal having the provided input fields (need to create only UI).
    - [ ] Name (required)
    - [ ] Description (Should be textarea)
    - [ ] Type (Pre-filled value that is displayed = `Sales and Marketing` and the value that should be stored in the database should be `sales_and_marketing`) _This value should be fetched from config variable having name `report_type => [ 'sales_and_marketing' => 'Sales and Marketing' ]`_
    - [ ] Embedded URL (Should be required URL field)
- [ ] Add a report option inside the sales menu 

![image](https://user-images.githubusercontent.com/54376313/146638376-b392d1a1-af6a-422a-86cb-a59b1db53b64.png)

![image](https://user-images.githubusercontent.com/54376313/146638485-ea5ece1a-2029-4fc1-ba6b-9ae4292fa71f.png)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by deepankar-sajwan** [comment]
Closing this task as it has been implemented
<img width="1270" alt="image" src="https://github.com/ColoredCow/portal/assets/96309135/46793712-efd5-4589-9fbc-b5e5ef9da9c2">
