### ISSUE TITLE
Create a reports table to store report URL and other data

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1234]
**Is your feature request related to a problem? Please describe.**
We need to store the embedded URL of the reports that we will be showing on the sales and marketing page. For this we will be needing a table to store the report details.

**Describe the solution you'd like**
- [x] Create a table `reports` using the Schema provided in this [Link](https://docs.google.com/presentation/d/19p69Ic4yyBQKjauHgXdsBZo3PFmQV5crSuZZfIYVtBc/edit#slide=id.g107fd8ecc8f_0_75)

**Describe alternatives you've considered**
NA

**Additional context**
- https://laravel.com/docs/8.x/migrations

**Comment by dsajwan2020** [comment]
The  table reports is created using  the Schema provided in this [Link] (https://docs.google.com/presentation/d/19p69Ic4yyBQKjauHgXdsBZo3PFmQV5crSuZZfIYVtBc/edit#slide=id.g107fd8ecc8f_0_75)

The table reports is available in the database refer screen shot

![image](https://user-images.githubusercontent.com/96309135/162724190-c500c849-f12b-4df1-bf2f-4a8eff58a0f8.png)

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
