### ISSUE TITLE
Edit the report details

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#1237]
- [ ] The edit button should open the modal with the prefilled form (the UI should be similar to the add report functionality). 
A User can edit the report details. To accomplish this task you need to perform the following tasks:
- [ ] Get the report details in the backend
- [ ] Only the user who can access or have permission to the report page can add report details. So for this, we need to create a policy to check the authorization
- [ ] Add a backend validation for the form fields.
- [ ] Once the form fields are received and validated, store them in the database.

**Comment by dsajwan2020** [comment]
Edit functionality has  been implemented please refer screenshot

1. Created new report 
![image](https://user-images.githubusercontent.com/96309135/162197037-feb4355c-25f7-4d26-a7d0-8d3ee924d81a.png)

2. Edit button is available for the report
![image](https://user-images.githubusercontent.com/96309135/162197121-15ab9edb-2a62-46ab-a8b3-504f292df9a4.png)

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
