### ISSUE TITLE
New status for opportunities

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1259]
**Describe the task**
In the status field for opportunities, we currently have three possible values: Draft, Published, and Closed. We need one more named "Archived".

**Expected behavior**
1. Update the options in the dropdown for status
2.  i) Create a custom field in WordPress for the job description named as "status". 
ii) The value in WordPress status field should get updated if it is changed from the portal screen.
3. The opportunities with "archived" status should not be visible on the career page in WordPress.

**Comment by dsajwan2020** [comment]
Task that are implemented

1. Updated  the options in the dropdown for status - added Archived option

![image](https://user-images.githubusercontent.com/96309135/163332927-b85fe431-dea2-4d67-bd81-82655bc0f9db.png)

3. The opportunities with "archived" status should not be visible on the career page in WordPress.

- Created a opportunity with Archived status 
  
![image](https://user-images.githubusercontent.com/96309135/163333605-70a19121-8e35-40c2-88c1-043440991a2d.png)

![image](https://user-images.githubusercontent.com/96309135/163333649-fed3958a-e5aa-4215-aa81-086507f8c3ef.png)

- Opportunity with Archived status not available in career page in Wordpress

![image](https://user-images.githubusercontent.com/96309135/163333779-aad03c6c-3846-4f16-a540-28b450fd36f4.png)
