### ISSUE TITLE
Reduce gap between navigation link and dropdown so that it doesn't close

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1270]
**Describe the task**
When I hover on a nav item and then try to go to the dropdown below, there is a certain space in between that closes the dropdown.
Here's a small recording to understand:
https://user-images.githubusercontent.com/12053186/157629862-89c6f0b2-0610-42ee-8ef8-77c39e58738f.mov

**Expected behavior**
- Reduce the spacing between menu link and dropdown so that it doesn't close
- Don't make them too close!

**Comment by dsajwan2020** [comment]
This issue has been fixed 
Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/161970331-9202aebf-8154-4724-ad9b-6fa1ca2424b1.png)
