### ISSUE TITLE
Error occurred when building npm package in windows 10

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1292]
**Describe the bug**
When building npm package getting error as shown in image
Environment:

Windows 10
nodejs v14.18
npm 8.5.0

**To Reproduce**
For reproducing issue execute step 4 available in following link
https://github.com/ColoredCow/portal/blob/master/docs/installation.md

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dsajwan2020** [comment]
![image](https://user-images.githubusercontent.com/96309135/161072174-df5dcc73-15c3-48f2-9fa4-6fa32832856e.png)

**Comment by deepankar-sajwan** [comment]
Closing as issue did not reoccured
