### ISSUE TITLE
Add validation to avoid adding duplicate Client and Project name in Portal

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#1297]

**Comment by dsajwan2020** [comment]
**Issue**
1. At present there is no validation implemented for client name. The user can create more than one client with same name. This results in redundancy in the system. 

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/165265796-7f528953-ccfe-4544-a0b2-d1dd952b770b.png)

2. At present there is no validation implemented for project name. The user can create more than one project with same name. This results in redundancy in the system. 

Refer screenshot 

![image](https://user-images.githubusercontent.com/96309135/165265213-84c0cda0-9bd6-4ab1-b923-dbba4f43d635.png)


**Possible solution**

1. When new client is created, validation check should be implemented once user enters client name , if the client with similar name already exist, message should be displayed to the user  "This name already exist. Please try another name."


2. When new project is created, validation check should be implemented once user enters project name , if the projects with similar name already exist, message should be displayed to the user  "This name already exist. Please try another name."

**Comment by deepankar-sajwan** [comment]
Hi @gautam071 the validation for duplicate client and  duplicate project needs to be implemented on two scenario
- When new project or client is created
- When we edit the existing client or project

**Comment by deepankar-sajwan** [comment]
The feature is implemented
