### ISSUE TITLE
Google analytics should capture click data of Apply Now Button

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1300]
This feature request in linked with (https://github.com/coloredcow-admin/employee-portal-2.0/issues/145

Is your feature request related to a problem? Please describe.
Google Analytics tool is not capturing, data related to the number of clicks on Apply Now Button.
The data of number of clicks can be used for obtaining Conversion Rate = Count of clicks on Apply Now button/ Number of visitors visiting Career page.

Describe the solution you'd like
Functionality should be added in Google Analytics to capture Count of clicks on Apply Now button.
If our Conversion Rate is low then we have to improve our website layout and content. This will help in increasing number of applicants and enhance recruitment process in coloredcow.

Additional context

**Comment by dsajwan2020** [comment]
![image](https://user-images.githubusercontent.com/96309135/161694942-3c0ebc03-cad1-4601-8d3a-58861dd941fc.png)

**Comment by P4NK4J** [comment]
This issue is related to ColoredCow website, it would be implemented based on Google Tag Manager, we will revisit this issue while working on the website. Hereby, closing it on portal repository
