### ISSUE TITLE
Show all the applications associated  with single  candidate on resume screening screen

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1305]
**Is your feature request related to a problem? Please describe.**
 If a job applicant has skills that match with more than one  job role, and the applicant applies for more than one role. 
When we click on the candidate name the window is opened, which displays only a single application, hence the interviewer is unable to evaluate the candidate for the other role. 
This results in opportunity loss for onboarding suitable candidate for the organization 

**Describe the solution you'd like**
If the recruitment portal receives two applications from a job applicant, both the applications should be displayed on the left corner of the window which is opened on clicking the candidate name.

**Comment by dsajwan2020** [comment]
Refer screenshot
![image](https://user-images.githubusercontent.com/96309135/161714125-86ab54d9-c225-4c7b-b6e6-b713cfd670f1.png)

**Comment by P4NK4J** [comment]
@Shivam-Samant Let's make smaller tasks for this issue as well, mentioning each details, like the file name where the code changes need to be made, for @JCArya to work on this.
