### ISSUE TITLE
Show job description as a tooltip on the applicant name

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1306]
Every applicant has been associated with one or more jobs.

We need to show the job description as a [tooltip](https://getbootstrap.com/docs/4.1/components/tooltips/) when the user will hover the mouse on the candidate name.

This feature will help HR to know about the job post for a candidate without going into one step deeper.

![image](https://user-images.githubusercontent.com/96309135/161714968-68b92569-3801-4934-8d39-b4922e1a1fcf.png)

**Comment by P4NK4J** [comment]
Closing this issue, as it seems that the existing portal functionality serves this functionality, we can revisit it later if we need more thoughts or details to it
