### ISSUE TITLE
The  email content for UAT environment and production environment should be in sync

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1312]
The content of the email body which is sent to job applicant , through production environment, and UAT environment is not synchronized.

Describe the solution you'd like
Review of email content should be performed to maintain synchronization.
Review should be performed for other email content
Refer image for reference

**Comment by dsajwan2020** [comment]
![image](https://user-images.githubusercontent.com/96309135/161763807-0a7c8e7e-7920-4bc8-8c09-fd48a921d8e8.png)

**Comment by deepankar-sajwan** [comment]
Closing this issue as it is not releavant
