### ISSUE TITLE
Please create GST Tax report for monthly invoices.

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#1324]
Need Invoices to report in the below format for monthly GST filing.
Please give functionality to download the report in excel.
Let me know if you have any questions.
<img width="1506" alt="Screenshot 2022-04-16 at 1 11 03 PM" src="https://user-images.githubusercontent.com/16541548/163666569-0693ddaa-4f0b-43cc-b968-81221acf9706.png">

**Comment by dsajwan2020** [comment]
Hi Mohit,

Can you please confirm  that following, banner is appropriate as per your requirement

![image](https://user-images.githubusercontent.com/96309135/163672614-f83fe4ab-5766-450a-bfae-3aa71f7e7eb3.png)

**Comment by mohitsharma-22** [comment]
Deepankar, Please use the same fields in the same order as I have shared., I need them for the monthly report in the same order.

**Comment by dsajwan2020** [comment]
> Deepankar, Please use the same fields in the same order as I have shared., I need them for the monthly report in the same order.

Thanks for your input I will use same order for the report as specified by you in the beginning.

**Comment by dsajwan2020** [comment]
Following task are created for implementing the requested feature

- [ ] Creation of frontend page which displays the Gst Report as per specified format
- [ ] Addition of csgt, sgst, invoice no, hsn code column in invoices table available in database.
- [ ] Adding billing state, cgst rate, sgst rate in the config file of invoice module
- [ ] Implementing process for generating the invoice no 
- [ ] Calculating cgst amount, sgst amount and isgt amount based on billing state.
