### ISSUE TITLE
Functionality to mark disputed invoices and remove from the list.

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#1332]
Currently, there are only two action options available for sent invoices.
1. Paid
2. Delete

Need a 3rd option for dispute invoices for which payments are not received and we need to mark it disputed and removed it from the pending invoices list.

**Comment by deepankar-sajwan** [comment]
Disputed should be added as actions, when an invoice is pending it can be marked as disputed, and comment box should be available, where user can add comment for marking invoice as disputed.

Refer screen shot for reference

![image](https://user-images.githubusercontent.com/96309135/168426902-716e87b4-7705-4838-abc3-e036384e64e9.png)

**Comment by deepankar-sajwan** [comment]
The disputed status for invoice is added in the Invoices page. 

![image](https://user-images.githubusercontent.com/96309135/173511341-24cbe778-8d32-49a6-9e3b-1301170d12ca.png)
