### ISSUE TITLE
User has to be assigned super admin role for accessing any feature of employee portal

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1337]
**Is your feature request related to a problem? Please describe.**
In current implementation of employee portal, when we assign rights to any user for accessing various  feature of employee portal, though **user  management** option available under **settings**. We have to assign Super Admin role to the user. 
This results in assigning  every user super admin role, which is not correct. Since there should be only on Super admin role for the system. 

The following steps describe the issue for  finance module
 
1. User is not assigned super admin role

![image](https://user-images.githubusercontent.com/96309135/165489544-1a6eaf5c-a7dc-47d9-b042-2bd3bbf5a9e9.png)

2. User not able to access finance feature of the portal

![image](https://user-images.githubusercontent.com/96309135/165489802-7df72599-72f5-4c3b-9604-c64328cde5ac.png)

3. User assigned super admin role 

![image](https://user-images.githubusercontent.com/96309135/165489949-b8117727-78af-4aea-970e-63c52a8b6608.png)

4. User able to access finance feature of the portal 

![image](https://user-images.githubusercontent.com/96309135/165490791-5d76967d-5f7e-47a1-a20e-4c883a13026d.png)

Same issue occurs in other features  of employee portal

**Describe the solution you'd like**
We need to develop a user access policy for various modules such as Finance, Project management, Sales, HR  of  the employee portal.

**Comment by deepankar-sajwan** [comment]
- Sharing my initial finidings related to the user access control policy available in the link
https://drive.google.com/drive/folders/1pkmyjhK5KxzYnKb_Y5DS8W6D22q7n7aW?usp=sharing

**Comment by rathorevaibhav** [comment]
This has been fixed. Closing.
