### ISSUE TITLE
Designing the algorithm for generating invoice no for the invoice

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1342]
To create the invoice report ([here](https://github.com/ColoredCow/portal/issues/1324)), we would need the following items 
1. **Invoice number**: It will have the format - Client Type - Client ID - Project ID - Invoice sequence
for example(IN-001-001-0001  for international it is EX-001-001-0001). Client ID, Client Type, and Project ID would be available in the database. To get the invoice sequence, we would have to add `1` to the count for each client and its project, how many invoices have been sent. The invoice number will be a different column in the invoices table, with a text/Varchar data type. It would be calculated and stored at the time an invoice is created. 

2. **IGST, CGST, SGST** -  Currently, we have Haryana as the billing state, that we can store in the config of invoices module. Upon invoice details listing, we will have to see if the client's state is the same as the billing state, the CGST value should be 9%(picked from config) and SGST value should be 9%(picked from config), IGST will remain null in this case. If the client's state is different from the billing state, the IGST value would be 18% (picked from config), and CGST and SGST will remain null in this case. The client's state can be picked from the database.

**Comment by P4NK4J** [comment]
To create the invoice report ([here](https://github.com/ColoredCow/portal/issues/1324)), we would need the following items 
1. **Invoice number**: It will have the format - Client Type - Client ID - Project ID - Invoice sequence
for example(IN-001-001-0001  for international it is EX-001-001-0001). Client ID, Client Type, and Project ID would be available in the database. To get the invoice sequence, we would have to add `1` to the count for each client and its project, how many invoices have been sent. The invoice number will be a different column in the invoices table, with a text/Varchar data type. It would be calculated and stored at the time an invoice is created.

2. IGST, CGST, SGST -  Currently, we have Haryana as the billing state, that we can store in the config of invoices module. Upon invoice details listing, we will have to see if client's state is same as the billing state, the CGST value should be 9%(picked from config) and SGST value should be 9%(picked from config), IGST will remain null in this case. If the client's state is different from billing state, the IGST value would be 18% (picked from config), CGST and SGST will remain null in this case. Client's state can be picked from the database.

**Comment by GauravGusain98** [comment]
### clarified Requirements

- Invoice Number format - <IN/EX><client ID><project Id><Six digit invoice id><MM><YY>
     - <IN/EX> - `IN` for indian clients, `EX` For international clients
     - Client Id - Id of client stored in DB
     - Project Id - Reference ID (client_project_id) of projects stored in DB
     - Invoice Id - Invoice sequecne number. If it is the first invoice then it should be `000001`, If it is 10th invoice then it should be `000010`
     
- We need to store Haryana in Config and check if the client state matches the config value. If yes then the CGST, IGST should be 9% (picked from config), For other states it should be 18% (picked from config). 
    - For international client it should 0

**Comment by deepankar-sajwan** [comment]
The feature is implemented as per requirement 

Refer screenshot
![image](https://user-images.githubusercontent.com/96309135/173504235-590b2131-e933-4780-aca8-be483b3b4265.png)
