### ISSUE TITLE
Disable create button on one click

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#1351]
**Describe the bug**
Create invoice button is clickable again, which resulting creating 2  invoices in the portal. 
<img width="506" alt="Screenshot 2022-05-02 at 12 46 59 PM" src="https://user-images.githubusercontent.com/16541548/166198241-aa90e387-525f-4295-b34f-9d3bc09a4bcc.png">

<img width="1200" alt="Screenshot 2022-05-02 at 12 42 17 PM" src="https://user-images.githubusercontent.com/16541548/166198142-7b8c8c07-f8de-4e45-babd-0dc4edd097c3.png">

**Comment by dsajwan2020** [comment]
Hi @mohitsharma-22  can you please confirm, that this issue is fixed in the production environment.

**Comment by mohitsharma-22** [comment]
@dsajwan2020 the crate button is getting disabled and it is working fine.
As discussed, we need to add a message, "Invoice created successfully" on the click of create button. . Please get that also implemented. Thanks

**Comment by deepankar-sajwan** [comment]
Hi @gautam071 can you display the message "Invoice created successfully" on the click of create button as metioned by @mohitsharma-22.

**Comment by deepankar-sajwan** [comment]
Message added when creating invoice.

![image](https://user-images.githubusercontent.com/96309135/170827367-0e2222a0-ad4b-4257-a76d-82da554c80c5.png)
