### ISSUE TITLE
Error 500 is displayed on screen while creating new project in  portal in production environment

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1352]
**Describe the bug**
When creating a new project all the fields  were provided to project creation form except uploading the project contract file. Error 500 occurs on clicking on **Create** button.

Refer screenshot for reference

![image](https://user-images.githubusercontent.com/96309135/166225823-d57ace09-45be-41ef-8476-868403eb5d95.png)

![image](https://user-images.githubusercontent.com/96309135/166225855-3ac1a075-e352-457f-9bf3-156de393912e.png)

**To Reproduce**
1. Go to Project Management
2. Click on Projects
3. Click on Add new project
4. Add all the fields in Project creation form, and do not upload Project contract file in the **Upload File** section.
5. Error 500 occurs

**Expected behavior**
The **Upload File** field should be made mandatory. 
The content **Upload File** should be modified to **Upload Contract File**

**Comment by dsajwan2020** [comment]
Hi Gautam can you please fix this issue on urgent basis as it is occurring in finance module.

**Comment by gautam071** [comment]
@dsajwan2020 Yea sure!👍🏻

**Comment by dsajwan2020** [comment]
Hi @mohitsharma-22  can you please confirm, that are you comfortable with the fix proposed for the issue.

**Comment by mohitsharma-22** [comment]
@dsajwan2020 Yes, Please make it mandatory and put validation on the field.

**Comment by dsajwan2020** [comment]
- When creating new project the **Upload Contract File** Field is made madatory. 

![image](https://user-images.githubusercontent.com/96309135/167070551-10dc7862-8953-45ce-b892-22d38d56dbff.png)


- When Project contract file is uploaded the project is created successfully

![image](https://user-images.githubusercontent.com/96309135/167071039-c57e2438-8a82-4056-9856-025ceed0b348.png)

![image](https://user-images.githubusercontent.com/96309135/167070783-1f423880-c4e3-45ab-be06-ab077bc8c0e5.png)

**Comment by deepankar-sajwan** [comment]
Closing this issue as it has been fixed
