### ISSUE TITLE
Create project button throws error

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#1353]
**Describe the bug**

<img width="593" alt="Screenshot 2022-05-04 at 2 59 55 PM" src="https://user-images.githubusercontent.com/16541548/166656055-d886fcdb-af7a-467a-9e07-f1ff347c6967.png">

**Screenshots**
<img width="1132" alt="Screenshot 2022-05-04 at 2 57 54 PM" src="https://user-images.githubusercontent.com/16541548/166655838-da53dd8c-abb4-44af-8701-c9a70a6d1cd9.png">

**Comment by dsajwan2020** [comment]
Hi @mohitsharma-22  the issue occured, since maximum file upload size in nginx configuration size was set as 2MB in production environment server . The maximum file upload size is now updated to  8MB. Can you please confirm is the issue is resolved in production environment.

**Comment by mohitsharma-22** [comment]
@dsajwan2020 The issue is resloved. Thanks.

**Comment by dsajwan2020** [comment]
Closing this issue as it has been fixed  in production environment.
