### ISSUE TITLE
Add project list in Client details page

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1359]
**Is your feature request related to a problem? Please describe.**
If a user comes to client details, he should be able to see the list of projects that client has and from there he can see the details of each project.

**Describe the solution you'd like**
Add a project tab in the client details section

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by dsajwan2020** [comment]
Projects field is avilable in Client details

![image](https://user-images.githubusercontent.com/96309135/167094561-59b6af71-f9bc-4cde-ad5a-9c2d56a50b28.png)

Details of individual project is available on clicking on to project

![image](https://user-images.githubusercontent.com/96309135/167095634-fa3cf606-5f85-485d-ba8c-69f6150844e3.png)

![image](https://user-images.githubusercontent.com/96309135/167095442-9998ab31-7ce1-441b-b718-f6845d7310bc.png)

**Comment by dsajwan2020** [comment]
- Other changes realted to https://github.com/ColoredCow/portal/pull/1360 

- Alignment of team memeber in project details

![image](https://user-images.githubusercontent.com/96309135/167096838-0937e528-555e-4119-b372-7db1fb9248ab.png)

- Project are alligned according  to client name sorted in alphabetic order 

![image](https://user-images.githubusercontent.com/96309135/167098116-1ca7f86f-049d-40ab-9507-e78520d6c614.png)

- Rename project management navbar to CRM

![image](https://user-images.githubusercontent.com/96309135/167098307-fd50444a-b9f7-4ab1-906b-85b0b37c8b3c.png)

- Remove reference-id from Projects page

![image](https://user-images.githubusercontent.com/96309135/167098596-a519968f-e894-4a5b-97e7-6413216e45db.png)

**Comment by deepankar-sajwan** [comment]
The feature is impemented  and integated in to production environment
