### ISSUE TITLE
Roles and permissions fixes

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1364]
**Describe the task**
There are following issues with user roles and permissions in the system:
1. A user with no roles still see some items in the main menu
2. All permissions do not work correctly and have not been placed in the codebase properly

**Expected behavior**
1. A user with no role should not see anything except for a message saying "You don't have any access. Please ask your admin to grant you access"
2. A user with certain role with certain permissions should be able to see only relevant screens/CTAs.
3. Role permission management screen is hidden. It should come back and should be visible only to super admins
4. Fix default permission seeders for all the modules

**Comment by deepakbarmola** [comment]
Closing the issue as the Linked PR is approved and merged.
