### ISSUE TITLE
Client Page Needs some refactoring

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1366]
**Is your feature request related to a problem? Please describe.**
We need some functionalities and fixes in client section. 
- [x] Client name should be sorted and also the partners should be sorted
- [x] Need search bar in client section

**Describe the solution you'd like**
The workflow of the client and project status should be as shown in the flow chart
![Cilent status flowchart](https://user-images.githubusercontent.com/54376313/167251904-4aec2ec0-a8fa-494c-ac79-dcac4c876c59.png)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by dsajwan2020** [comment]
- The client name and partner name is sorted 

![image](https://user-images.githubusercontent.com/96309135/167579726-920398dd-ea0a-4112-8262-fa266584b2b4.png)

- Search icon is availabe in Clinet page and is working as per requirement

![image](https://user-images.githubusercontent.com/96309135/167580404-4615140c-97e8-45e8-bb7f-85907c153c73.png)

**Comment by GauravGusain98** [comment]
This is implemented. Closing it now.
