### ISSUE TITLE
Disabling the Create button on single link.

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1369]
**Describe the bug**
When Create button is clicked simultaneously multiple times. Multiple creation of the entinties is available.  The issue needs to be fixed in all the modules where Create button is used.

**Comment by dsajwan2020** [comment]
The issue occurs under sales while we Create new prospects

![image](https://user-images.githubusercontent.com/96309135/167254346-4106f199-b249-4421-b1b2-6ee0d01054e4.png)

**Comment by abhishekkhanduri** [comment]
**The same problem is occurring at following places:**

- [ ] While creating a new client.
- [ ] While creating a new project
- [ ] While Adding new category  at  http://portal.test/knowledgecafe/library/book-categories.

**Comment by gautam071** [comment]
@abhishekkhanduri Revoming this `When we Create new prospects in Sales` because @dsajwan2020 already added.

**Comment by deepankar-sajwan** [comment]
Hi @gautam071 can you add following messages based on the scenraio mention

- While creating a new client   "Client created successfully"
- While creating a new project  "Project created successfully"
- HR module in Manage Tags when we Create new tag -  "Tag created successfully"
- When we Create new prospects in Sales - "Prospect created successfully"

**Comment by gautam071** [comment]
@deepankar-sajwan I have created the message for the following tags 

1. While creating a new client `Client created successfully`
2. While creating a new project `Project created successfully`

You can track them in the following PR #1408 

I will be working on the remaining tags today and will let you know once it's completed.

**Comment by gautam071** [comment]
@deepankar-sajwan I have created PR #1471 for the Invoice and Prospects.

**Comment by deepankar-sajwan** [comment]
The issue is fixed.
