### ISSUE TITLE
Fix Project number as per the invoice

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#1382]
**Describe the task**
Currently, project numbers are different than we have set up while sending the old invoices. We need to fix that numbers. 

**Expected behavior**
All the project numbers should match with this [sheet](https://docs.google.com/spreadsheets/d/1wrhmTybIxQGpig5JEHzZ6cF0GfslINyAa8G8aSkEMUI/edit#gid=1246529682). 

**References**
Specify any reference material / links

**Comment by deepankar-sajwan** [comment]
Hi @Shivam-Samant before merging code for generating invoice number we need implement this feature. Since client  id and project-id are not  correctly mapped.

**Comment by deepankar-sajwan** [comment]
Thanks @Shivam-Samant  I will  take care of this task

@pankaj-ag assigning this task to you as per the discussion with @mohitsharma-22
