### ISSUE TITLE
When Invoices status in paid then the Email column is empty

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1384]
**Is your feature request related to a problem? Please describe.**
The invoices have two status  **Paid** and **Sent**. If status is sent  then Email column contains **Send Mail** button icon, but in case status is Paid, then there is no information under Email column. Hence there is no consistency, when list of invoices is displayed.

Refer screenshot 

![image](https://user-images.githubusercontent.com/96309135/167574670-bce76cc0-b96c-4e96-ae63-262b702b3774.png)

**Describe the solution you'd like**
The Email column should be renamed as **Actions** , Also **Send Mail** button icon  should be displayed as **Late Payment Reminder**.  In case invoice status is **Paid**  then dispaly **No Action**

**Comment by dsajwan2020** [comment]
Hi @mohitsharma-22 can you please confirm, that are you comfortable with proposed solution.

**Comment by mohitsharma-22** [comment]
@deepankar-sajwan Can we think a bit more about what could be the solutions for this? 
Not 100% sure, if the below option is suitable.
`In case invoice status is Paid then display No Action`

**Comment by deepankar-sajwan** [comment]
Closing this issue as this task is not required as per current implementation as in below screenshot
<img width="1274" alt="image" src="https://github.com/ColoredCow/portal/assets/96309135/874954a2-6cff-4a9f-b471-9f1b50206a8e">
