### ISSUE TITLE
Sort the project name using order by function when creating a new invoice.

### ISSUE THREAD

**Issue by Shivam-Samant** [ColoredCow/portal#1412]
**Describe the task**
Sort the project name using order by function when creating a new invoice.

**Comment by deepankar-sajwan** [comment]
The feature has been tested on UAT

Refer screenshot for reference

![image](https://user-images.githubusercontent.com/96309135/168758430-0415e8f0-0191-461a-87e6-3e891339cff9.png)

**Comment by deepankar-sajwan** [comment]
Feature implemented in https://github.com/ColoredCow/portal/pull/1413
