### ISSUE TITLE
The content available in GST report is not as per the requiremnt

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1424]
**Describe the bug**
GST report does not have values as specified in [#1340](https://github.com/ColoredCow/portal/issues/1340)

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/169292634-71d0b5c4-f855-4942-bfcf-44990e5df00a.png)

**Comment by deepankar-sajwan** [comment]
Hi @Ayush8923  there are still some changes that are not been implemented as per requirement

Refer screen shot

![image](https://user-images.githubusercontent.com/96309135/169681950-e225e75a-bbe3-48ed-a33d-1330cfcf8202.png)

GST Column

**Export** should be available as option for international client
**GST number** should be available for indian client, if GST number not available, then add **B2C** instead of GST number

Type Column

**Indian** as option for indian client
**Export** as option for international client

Cgst column -- Amout of cgst is not available when client was from harayana
sgst column -- Amount is sgst not available when client was from harayana

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
