### ISSUE TITLE
In Client address form state, city and area code field needs update

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1428]
**Is your feature request related to a problem? Please describe.**
In client address form following modifictions are required

- state field should have dropdown containg states related to selected country. For instance if we select country as India, then state should have dropdown including all the states and UT of India.

- City field should have dropdwon containing all the cities, realted to selected state. For instance, if we select state as Harayana, then   City should have dropdown including all the cities of Harayana.

- Area code field should have area code based on selected city 

- Same procdeure should be followed if we select country other than india.

**Comment by rathorevaibhav** [comment]
Not needed right now.
