### ISSUE TITLE
Create table to store alerts details and other meta for projects.

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1496]
**Is your feature request related to a problem? Please describe.**
We need to add a column for capturing if the project exists in the effortsheet or not. For this, we need a table called `projects_meta` with the structure
 - project_id (BigInteger, foreign key to project table, Not nullable)
 - key (VARCHAR, Not nullable)
 - value (VARCHAR, nullable)
 - created_on (timestamp)
 - updated_at (timestamp)

**Describe the solution you'd like**
- [x] Create a migration file for the provided table
- [x] Create a model/entity for the table

**Describe alternatives you've considered**
NA

**Additional context**
- Check the naming convention of the migration file. Take reference from Laravel documentation or any other migration file that exists in Portal.

**Comment by abhishekkhanduri** [comment]
This is deployed, closing this issue
