### ISSUE TITLE
Functionality to mark an application "on hold" and send an email to the candidate

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1542]
**Is your feature request related to a problem? Please describe.**
There are instances when the recruitment team is not confident in calling a job applicant for an interview. Then the recruitment team can place the application on hold, and send a mail to the candidate conveying the same message. This will save time and energy for all the persons involved in the recruitment process. 
If the recruitment team is unable to evaluate the application of the candidate, based on their evaluation criteria then put the application on hold. Also, convey the same message to the candidate through email.

**Describe the solution you'd like**
1. On the edit application page, if an application is under the resume screening phase, provide a button saying `Put on Hold`, next to the Take action and Reject button. 
2. Clicking on which, a popup would appear that will ask the evaluating person if he/she wants to put the application on hold. Clicking on Yes, the application would move to the on-hold tab. 
3. Once an application is put on hold, an email should be triggered for the candidate. We need to create an email template for this, it can be treated as another issue.

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
