### ISSUE TITLE
In Monthly GST report if the user clicks on the next page to check records Months and Year filters are reset 

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1543]
**Describe the bug**
In monthly GST report the selects June month and year as 2022 the  records are availabele for June 2022. The records are available in different pages, which are displayed at bottom of records. When we select second page to view the next records, the fileter for months is reset to All Months and years is reset to  All Years. Hence records for all years are displayed.

**To Reproduce**
1. Go to Monthly GST report under Finance dropdown
2. Select June in Month filter and 2022 as Year
3. Records for June 2022 are available
4. Click on the 2nd page on the list of pages available at end of records
5. The Months are reset to All months and Years are set to All Years

**Expected behavior**
The records for June 2022 available in 2nd page shuould be available on screen

**Screenshots**
![image](https://user-images.githubusercontent.com/96309135/173176444-0b98d326-2258-4bb9-afd2-8c95c402a32f.png)

![image](https://user-images.githubusercontent.com/96309135/173176737-ad4c673f-5b1d-4ef1-a92a-41f7a96e1b2e.png)

**Comment by rathorevaibhav** [comment]
This is complete. Closing.
