### ISSUE TITLE
Segment name in Manage Evaluation to be mapped with Evaluation Round

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1554]
**Describe the task**
Currently while creating a new evaluation segment, we don't have the facility to map it with the application round. 

**Expected behavior**
Add a dropdown having all the application rounds when a segment is created in the `create segment` modal. If a user selects the round corresponding to the segment, it would be mapped in the database automatically. Refer to the screenshot below for the modal
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/173597241-957441ec-25ee-44d8-b17a-7fdcb3044f3e.png">

**Comment by deepankar-sajwan** [comment]
The task is complete please refer screenshot


![image](https://user-images.githubusercontent.com/96309135/180226997-0b39de44-30f1-4c74-ae86-e4f062cb6e41.png)


![image](https://user-images.githubusercontent.com/96309135/180227037-45d9fcd4-6d18-4e22-a5b7-65ef8b140fe2.png)
