### ISSUE TITLE
Button to show, count of applications in each round

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1571]
**Describe the task**
On the HR module listing screen, we would like to have a functionality to see the total number of applications in each stage. 

**Expected behavior**
1. When we are in the `Open` Applications screen, besides the `Campaign` button on the applications listing screen, provide a link named `Total Count`, clicking on which a popup should appear. The UI can be similar to all the other links. We can use font-awesome counter icon for this.
2. Inside the popup we can have a modal heading named `Total Open Applications - |*COUNT_OF_OPEN_APPLICATIONS*|`
3. Inside the popup, there can be all the application rounds listed, next to which we can have the count of applications corresponding to each round.
For example:
```
Resume Screening - COUNT
Introductory call - COUNT
```

**Comment by aquibmoin786** [comment]
@P4NK4J  Have an any references to done this task?

**Comment by P4NK4J** [comment]
@aquibmoin786 Currently we don't have any UI mockups or something. We need the total count button next to the campaigns button clicking on which the popup should appear. The theme and branding of the popup can be the same which is currently used in other places of the portal. Let me know if that's helpful, I can jump over a call and explain things if needed.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/35001775/177571805-46a05182-57d6-4153-85cf-cf0542bc06bc.png">

**Comment by P4NK4J** [comment]
> ![Screenshot (141)](https://user-images.githubusercontent.com/61320158/177979032-9841a04c-25b4-46af-851b-a11e6114936c.png) Hello @P4NK4J , I have design fronted yesterday. For backend design taking time. After reading documentation of Laravel. I will do that.

Great progress @aquibmoin786 👏 Take your time in understanding the backend and working on it. You post any comments, or doubts here itself.

**Comment by P4NK4J** [comment]
@aquibmoin786 Let's target checking only the open applications in the database. Open applications are those, who have status = `in-progress`, `new`, and `trial-program`. I missed adding it in the requirements, sorry for the inconvenience.

**Comment by aquibmoin786** [comment]
Hi @P4NK4J The updated requirement shared by you in previous comment has been implemented.

**Comment by P4NK4J** [comment]
yeah, I am closing this issue now
