### ISSUE TITLE
issue with installation 

### ISSUE THREAD

**Issue by LAKSHYA0501** [ColoredCow/portal#1606]
**Describe the bug**
As per the given documentation, i am trying to install the portal , but it is giving me error in the 5th  step of [the installation guide](https://github.com/ColoredCow/portal/blob/master/docs/installation.md)

![Screenshot (33)](https://user-images.githubusercontent.com/53862863/175273180-5d09108c-8d33-410c-b6f4-a073f2f7b5c6.png)

**To Reproduce**
1. For this error you must use a windows machine.
2. open cmd and start following the installation guide.
3. when you run the command `cp .env.example .env` you will get an error 

**Expected behavior**
The command should run and a copy of env file should be created.

**Screenshots**
attached above

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser NA
 - Version NA

**Comment by deepakbarmola** [comment]
Closing as related PR is approved and merged.
