### ISSUE TITLE
Phase 3 Hiring Guidelines and Resources

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1612]
**Describe the task**
We need to create a database schema for the hiring and guidelines resources

**Expected behavior**
Propose a DB schema for the workflow for the issue #1545 and share the URL here

**Comment by JCArya** [comment]
https://docs.google.com/presentation/d/1MJLAli-SMbh01PuwL_CLTdg2ZoqYA7Pow_Ni8kkeHZE/edit?usp=sharing

**Comment by P4NK4J** [comment]
Looks good 👍
