### ISSUE TITLE
Add functionality to send a verification email to the applicant when the applicant's application received

### ISSUE THREAD

**Issue by Shivam-Samant** [ColoredCow/portal#1613]
When the applicant's application is received the autoresponder email is sent to the applicant. Instead, the new template body has been emailed to the applicant. In the new template, there is a verification link, clicking on that the user redirects to the link where the autoresponder template will show. The verification link should look like this `http://portal.coloredcow.com/applicationverification/application_id`.

- [x] Create the verification mail template.
- [x] Use this email body when the applicant's application has been received.
- [x] Create the route for the application verification page.
- [x] If the application is successfully verified then the autoresponder template body has been emailed to the applicant.

**Comment by deepakbarmola** [comment]
Closing as PR associated is approved and merged.
