### ISSUE TITLE
Adding new Team member functionality should be disabled for Inactive Project and Halted Project

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1624]
**Describe the task**
In current implementation for Inactive Project, Halted Project the Adding new Team member functionality is available. The Inactive project and Halted Project should not have functionality to add new team member.

Refer screenshot for Halted Project

![image](https://user-images.githubusercontent.com/96309135/178756450-9204d052-d168-440b-a5c6-eafe69ddf934.png)

Click on Edit button and click on Team members Tab

![image](https://user-images.githubusercontent.com/96309135/178760352-cbfbb6f1-8f7e-4b5b-9c9b-8184d8dce6d5.png)

**Expected behavior**
Disable the Adding new Team member functionality from front end for Inactive project and Halted Project

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
