### ISSUE TITLE
Change color of search button on applications listing page 

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1633]
**Describe the task**
Currently, the search button on job applications page is having `black` color text. We need to make this button similar to the other ones present in the portal
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/35001775/175972223-7ffffb2e-230d-45d0-a539-4c340bf5346d.png">

**Expected behavior**
Change the color of `Search` button and make it similar to the other buttons on the portal.

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
