### ISSUE TITLE
Same Team member is added twice while adding team members in the project

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1634]
**Describe the bug**
When Project is created the team member involved in the project are added. When same team memeber is added twice, the system allows to save the details

**To Reproduce**
1. Go to CRM
2. Click on Projects
3. Click on the any project
4. Click on Edit button
5. Click on Project team members
6. Enter the Same Team member twice and click on Save

**Expected behavior**
Same team member should not be added twice in the system

**Screenshots**
![image](https://user-images.githubusercontent.com/96309135/176100766-3f13eeec-a5fc-4c29-8ea1-98c82fa2a800.png)

**Comment by deepankar-sajwan** [comment]
Hi @amanbhatt2022 can you please provide any updates about progress of this issue

**Comment by deepankar-sajwan** [comment]
Hi @chetanbhatt10 in case the user tries to same team member name, again in team member field, please display following message to the user

**Team member with similar name already added**

**Comment by rathorevaibhav** [comment]
Not happening anymore. Closing
