### ISSUE TITLE
Phase 5: Hiring guidelines and resources

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1637]
**Describe the task**
For adding resources categories, we would like to have a `Add category` button on the individual resource page adjacent to `Add resources button`. Also, rather than having `Add Resources` and `Add category` we would like to have `+ Resources` and `+ Category` buttons, where `+` icon can be displayed using font awesome.

**Expected behavior**
Clicking on `+ Category` button, a popup should appear, where input field should be present. This input field will be a text based field, where users can type in the resource category. Once this form is submitted, it should be saved in the `resources
_categories` table, and the slug for the database can be generated in the backend itself.

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
