### ISSUE TITLE
The number of estimated efforts to be input for  individual team member should have a limit

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1641]
**Describe the task**
In current implementation of the effort login of the individual team members, there is no limit to the number of hours, entered in the Estimated efforts for  individual team member.  
Since number of working days in a month range from 20 and 23, also number of working hours may vary from 8-12 hrs a day. Hence  a alert message should be dispalyed to the user.

**Expected behavior**
Set number of effort login for team number as 12 hrs a day, 60 hrs a week, and 276 for a month.
In case team member exceeds the effort login limit, a message box should be dispayed to user as "Are you sure" 
If he/she click yes then allow the effort login. 
In case he/she clicks No then remove effort login hours input by team member.

![image](https://user-images.githubusercontent.com/96309135/178487637-b4c44f30-c308-4ac4-91de-0ec33412de91.png)

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
