### ISSUE TITLE
Handling the scenario where there is mismatch of team member  mentioned in portal and effortsheet

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1644]
**Describe the task**
In case the team member are added in the effortsheet, but not added in the Project in the portal , then the efforts for team member are not displayed in the portal.

**Expected behavior**

- [ ] A label should be displayed in the **Status** column Project detail page, corresponding to the Project  for which team member are not added as  **Update Team Member**

**References**
Specify any reference material / links

**Comment by Himanshunegi0332** [comment]
sir can you explain the task.

**Comment by rathorevaibhav** [comment]
Not needed anymore. We'll figure out a different approach to tackle this.
