### ISSUE TITLE
When hovering over the HR dowpdown while Projects page is open there is problem in UI view

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1683]
**Describe the task**
When Project page is open to see list of projects, if user hover over HR dropdown the UI view is misligned.

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/176990494-a72772b4-1937-4da0-b7b3-1f40ac162b76.png)

Steps for issue recreation

1. Go to CRM click on Projects
2. Hover over HR dropdwon

**Comment by P4NK4J** [comment]
An issue #1673 is already created for this, hence closing this one
