### ISSUE TITLE
Change search and add client button similar to active clients

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1686]
**Describe the task**
Currently, the `search` and `add client` buttons are not in alignment with the other buttons. We would like the background color of both these buttons similar to the active clients.
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/35001775/176991823-44586897-ce6b-4710-82a8-787a6388a372.png">

**Comment by Tushar403** [comment]
sir can you explain it in detail please

**Comment by P4NK4J** [comment]
@Tushar403 In the screenshot above, you can see that the color of `Add Client` and `search` button is different from the other buttons in portal. It should be the same as `Active Client` button. Let me know if this is clear, or you need more details.

**Comment by Tushar403** [comment]
ok sir, thank you for explaining

**Comment by deepankar-sajwan** [comment]
The task has been done please refer screenshot

![Uploading image.png…]()
