### ISSUE TITLE
Show Team member effort in tooltip

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1688]
**Describe the task**
In project listing page, we want to show the effort booked by a particular team member in the tooltip where we see team member designation.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/54376313/176993848-b97ac910-f564-4bf8-acd7-4bab74bb9d8d.png">

**Expected behavior**
The efforts should be shown after the designation on next line.

For eg.     
```
Gaurav Gusain - Developer
Efforts: 80 Hrs.
```

**References**
Specify any reference material / links

**Comment by ASHISH-KOHLI** [comment]
please explain it

**Comment by ASHISH-KOHLI** [comment]
this task is already assigned to anshul saklani

**Comment by deepankar-sajwan** [comment]
The task has been complete please refer screenshot

![image](https://user-images.githubusercontent.com/96309135/178715090-118be0a8-8889-43a4-8d0c-594f24c12501.png)
