### ISSUE TITLE
Employees page is breaking on first date of the month

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1689]
**Describe the bug**
The employee page (Menu->HR->employees) breaks on the first date of the month. 

**To Reproduce**
1. change the date in your system to the first day of the month
2. Open the employees page
3. See the error

**Expected behavior**
This should work fine. 

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by deepankar-sajwan** [comment]
This issue is fixed refer screenshot

![image](https://user-images.githubusercontent.com/96309135/178500523-96c444d9-12f1-489b-ba3c-a98b17e35e08.png)


![image](https://user-images.githubusercontent.com/96309135/178500975-90d8f116-f334-4558-8a2e-af58fa7a40e5.png)
