### ISSUE TITLE
Users having HR permissions are getting 403 error on view application

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1708]
**Describe the bug**
While clicking on view button, in job applications listing, the page is throwing a 403 error for users having HR permissions.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/177134650-bcc0c6c4-8f1c-4b41-975d-25e35aadceab.png">

**To Reproduce**
1. Edit your system user role to HR
2. Click on HR in navigation, go to recruitment, a page with application listing would appear
3. Click on view button, the following error would appear.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/35001775/177134492-32b3657c-452c-4483-a19d-e8a34dc6798b.png">

**Expected behavior**
Application view page should open up on clicking the view button

**Comment by P4NK4J** [comment]
@NirmalNegi07 Try running the applications seeders, you can use `php artisan module:seed HR` command to run the specific seeders, currently you don't have any applications in your system

**Comment by NirmalNegi07** [comment]
@P4NK4J sir,its not working

**Comment by P4NK4J** [comment]
What's the issue ? can you share some screenshots ?

**Comment by NirmalNegi07** [comment]
application listing not visible !!!!!! After running this php artisan config:cache command same issue

**Comment by P4NK4J** [comment]
The listing is not visible because there is not data in your database. We use seeders to fill dummy data in the databases. To run the seeders, you need to execute some commands, in this case try with `php artisan module:seed HR`. You are not supposed to run `config cache command`. Once the command runs successfully, you will have dummy data in your database and applications would be listed. Please try running seeders and let me know if you succeed with that.

**Comment by NirmalNegi07** [comment]
sir,I try with php artisan module:seed HR , but then also i m facing the same issue

**Comment by P4NK4J** [comment]
can you share the results of the command you ran ? It must have shown something on your terminal, if you can share screenshot, that would help

**Comment by NirmalNegi07** [comment]
sir this also i have tried but then also the same issue

**Comment by P4NK4J** [comment]
@NirmalNegi07 Let's connect over a call on Google chat, and see if we can get the data populated.

**Comment by NirmalNegi07** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/85093163/177583350-97fabf97-2d3d-4041-b0b0-6837da1a5d5b.png)

**Comment by P4NK4J** [comment]
I see, the applications are present in the database, but not displaying on the browser. can you check in the codebase where the applications are listed. Maybe try dump and die the data, and try figuring out why the database applications are not being listed there ?

**Comment by NirmalNegi07** [comment]
But how sir?????

**Comment by deepankar-sajwan** [comment]
Closing as issue as it is  fixed

![image](https://user-images.githubusercontent.com/96309135/180237983-1ae74cf4-239d-4b82-a9f0-dffca1da2df1.png)
