### ISSUE TITLE
Enable all the customization options for tinymce editor on new opportunity page

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1712]
**Describe the task**
Currently on `Add new opportunity` page, the job description field provides only limited options for the TinyMCE riched editor to configure. We would want to enable all the customizations possible
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/177167440-01730250-101c-40fb-8990-aa9564fb7e4a.png">

**Expected behavior**
Enable the customization options possible in tinyMCE to make the description field customizable. The editor is already configured, we need to enable multiple options.

**References**
https://www.tiny.cloud/docs/configure/

**Comment by P4NK4J** [comment]
> @P4NK4J Which options are required to add in description field?

@aquibmoin786 As much as the number of customization options possible, please enable them. This can include, various items including increasing font size, image uploads, using heading and paragraph tags, etc. You can refer to the link below
https://www.tiny.cloud/docs/configure/content-formatting/

**Comment by deepankar-sajwan** [comment]
The task is complete please refer screenshot 

![image](https://user-images.githubusercontent.com/96309135/178673144-f16b176e-6c06-459c-877f-d928c33da830.png)
