### ISSUE TITLE
Disable save button in add category popup on guidelines page 

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1713]
**Describe the task**
On the guidelines and resources page, we have an add category button, which allows users to add a category field to database. We would like to validate the form field via JS for making it mandatory. 
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/35001775/177169610-1827c88d-5b1d-4d21-82db-5ba5e8457b2f.png">

**ToDos**
1. Go to HR->Guidelines and Resources (it's disabled as of now, can enable it from the codebase)
2. Click any job present on the listing page
3. Click on Add category button, and a popup would appear asking users to input the category
4. Disable the save button, till the category field is empty
5. Once the user fills in category the save button should be enabled
6. Use JS for these action items.

**Comment by deepankar-sajwan** [comment]
The issue has been fixed
