### ISSUE TITLE
Users who have read the book are misaligned in the library popup modal

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1716]
**Describe the bug**
When we login to employee portal, a popup of book appears. In that the list of users who have read that book is shown. If a book has been read by many user then the image of those users doesn't appear in next line and appears outside the popup section. See the image below. 

**To Reproduce**
1. Open portal
2. Inspect on the image of user once the popup appear
3. Now duplicate the HTML element multiple times which is showing the image.
4. Once you have duplicate the element 3-4 times, you will see that the image will appear outside the popup.

**Expected behavior**
The image of users should be wrapped if there are many users who have read the book

**Screenshots**
<img width="925" alt="image" src="https://user-images.githubusercontent.com/54376313/177210008-05e16788-d5bf-40c3-a4b4-b19fc8db84f0.png">

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by Tushar403** [comment]
sir not able to find an employee portal ,can you please guide me over this

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
