### ISSUE TITLE
Finance navigation dropdown UI

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1718]
**Describe the task**
Currently, on projects listing page, the finance dropdown is not working fine
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/35001775/177283863-0a8bad16-5140-4718-9be3-4b29836f17a2.png">

We would like the dropdown to appear in front of the title bar.

**Comment by P4NK4J** [comment]
@J0hn1975 I see this issue is already assigned to @belwalshubham. If you are interested in contribution, I can assign you a different issue 😄 . Let me know

**Comment by J0hn1975** [comment]
@P4NK4J This is my first ever contribution and looking for something relatively simple to start with. What other live unassigned issues do you have?

**Comment by P4NK4J** [comment]
@J0hn1975 You can pick this issue for getting started
https://github.com/ColoredCow/portal/issues/1708

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
