### ISSUE TITLE
Updates to installation guide regarding forbidden error in Apache

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1720]
**Describe the task**
When setting up the portal, @amisha296 faced an error that throws a page saying "Forbidden". There were some changes to the virtual host file that made it work.

**Expected behavior**
An optional step should be added to the installation guide at the time of virtual host step, with the proper error message in case a user sees and what to change/modify in the virtual host file.

**Comment by deepankar-sajwan** [comment]
The issue has been fixed refer screenshot

![image](https://user-images.githubusercontent.com/96309135/179158230-e92c1e6e-c64b-44da-93b5-57951a24e0ab.png)
