### ISSUE TITLE
Make cursor on books settings dropdown items as a pointer

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1722]
**Describe the task**
Currently, if you go to KnowledgeCafe, and select Library from navigation, you will land upon the books page. On clicking books settings, there are multiple options that have a normal cursor. We want the cursor to be updated to a pointer so that users can have a feeling of it's doing some actions and is clickable.
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/35001775/177342831-37759a4f-8599-4265-aa6b-b22a7477bdc1.png">

**Expected behavior**
Change the cursor on these items to the pointer.

**Comment by LavishRawat** [comment]
This issue is completed. Closing it.
