### ISSUE TITLE
UI correction on update category of books

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1723]
**Describe the task**
On the books page, under KnowledgeCafe->Library. If we click on the settings wheel, and the update category option, a popup appears with various categories in checkboxes. At the bottom of the modal, there is a functionality to add a new category, whose UI is a bit off. We would want to reduce the width of the input field so that the button text comes in a single line
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/177343603-49f1914c-1043-451d-871b-740c25dd65c4.png">

**Comment by LavishRawat** [comment]
This issue is completed. Closing it.
