### ISSUE TITLE
Books category delete UI inconsistency

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1724]
**Describe the task**
If we click on the delete button on the Books category page, a JS alert pops up. Clicking on `cancel` in the popup, the corresponding category becomes editable. We want there should not be any other action if we click on the `cancel` button.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/177344512-c4a18222-9079-4f73-9e93-45fa5807bbe0.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/177344797-8213740f-f034-473d-86f1-76575278c947.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/177344829-ce61f652-c917-4fb7-9494-95accc349179.png">

**Expected behavior**
Upon clicking `cancel` button, the alert should close without making category editable.

**Comment by Abhishek25081999** [comment]
@P4NK4J  i am trying  to resolve this issue from last 5 days but still did not get any hint . can you please tell me where should i make changes , i also tried to changes in app.js .

**Comment by P4NK4J** [comment]
@Abhishek25081999 You can proceed with the following steps:
1. Figure out which blade is rendering on the browser
2. Find the delete button
3. See which action is provided on clicking the delete button
4. You may find a JS code, which is triggering upon click of that button
5. You just need to toggle a Bootstrap modal, with the same on-click functionality
6. Try referring to the similar implementation done in these PRs
https://github.com/ColoredCow/portal/pull/1799/files), 
https://github.com/ColoredCow/portal/pull/1801

I hope this is helpful, you can take help from @amisha296 @akriti12negi

**Comment by deepankar-sajwan** [comment]
The issue is fixed
