### ISSUE TITLE
Increase scheduling frequency of sync:effortsheet command

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1735]
**Describe the task**
Currently we're running the sync effortsheet command 2 times a day 9 AM and 10 PM. We need to increase this frequency maybe 6 times a day i.e every 4 hours. 

**Why we need this**
Currently we facing many issues related to team members putting their previous day effort on next day after 10 PM, due to which their efforts are not captured and their FTE is coming less in the portal as the command only runs twice a day. So they have to wait for the next scheduling timing i.e 9 PM for their effort to get updated in portal till then their FTE comes less. 

To reduce this issue we can increase the command scheduling frequency. Instead of running it twice in a day we can run it every four hours. 

**Expected behavior**
- [ ] Schedule the command to run at different timings i.e (00:30, 04:30, 08:30, 12:30, 16:30, 20:30)

**References**
You can take reference from this document: https://laravel.com/docs/9.x/scheduling

**Comment by deepankar-sajwan** [comment]
The task is complete
