### ISSUE TITLE
Decsiption of monthly tax report is not as per format

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1736]
**Describe the task**
The monthly tax report description mentioned under Finance drop down is mentioned as Monthly tax report, the correct description should be **Monthly Tax Report**

Refer screenshot for inccorrect format
![image](https://user-images.githubusercontent.com/96309135/177518883-7dbe5e16-7016-4bde-933d-0deb155b3a71.png)

**Expected behavior**
A clear and concise description of what needs to be done.

**References**
Specify any reference material / links

**Comment by J0hn1975** [comment]
Hi Deepankar-Sajwan

This looks like a fairly simple typo in the dropdown that just needs to be corrected. Would you be happy for me to take a look?

Kind regards
John Wrafter

**Comment by deepankar-sajwan** [comment]
Hi @J0hn1975 this issue was already  fixed by internal team member

**Comment by deepankar-sajwan** [comment]
This issue has been fixed and verified please refer screenshot

![image](https://user-images.githubusercontent.com/96309135/178201297-02caa2f5-9bf1-4c7b-9533-d03599eadd9c.png)
