### ISSUE TITLE
Show projects count in projects listing page

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#1749]
**Is your feature request related to a problem? Please describe.**
Currently we only show the count of projects for which the tab is open. Instead of this want to show the count of all type of projects. Refer to screenshot below

**Describe the solution you'd like**
- [ ] Show the count of all type of project in the tab buttons
- [ ] Remove the current count that comes before the all-projects/my-projects Dropdown

**Current UI**
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/54376313/177568003-d6fe793e-a245-4101-8de5-78328751f1d8.png">

**Expected UI**
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/54376313/177567164-c972cbcd-ae1f-447a-936f-9730fc70de3f.png">

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by deepankar-sajwan** [comment]
The issue is fixed please refere screenshot

![image](https://user-images.githubusercontent.com/96309135/178670538-d5fbca40-20e6-4623-ab23-d72d7580348e.png)
