### ISSUE TITLE
Scheduler email to follow up with non verified applicants

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1757]
**Describe the task**
1. Create a scheduler, that will send an email to `pankaj.kandpal@coloredcow.in`, having a list of all the applications whose `is_verified` column in the database is set false. This will check all the applications after 6th July 2022, we don't wanna track the applications before 6th July 2022, for the functionality is yet to be speculated.
2. This scheduler should run at 7:00 pm every day.

The email template can be:
```
Hello Pankaj Kandpal, 

The following applications are present in the portal, those whose status is not verified. Please follow up with them via phone call

1. |*applicant_name1*| - |*applicant_phone_number*|
2. |*applicant_name2*| -  |*applicant_phone_number*|
3. ...............
4. ...... list will continue based on number of applications present.

Thanks, 
HR team, 
ColoredCow.
```

**Comment by belwalshubham** [comment]
@P4NK4J   could you please explain to me little bit more about this issue after creating the scheduler where should be changes reflect.

**Comment by GauravGusain98** [comment]
@belwalshubham Here is the breakdown of the issue, please follow these to complete the task

- [ ] Configure mail in system ([Link - step 12](https://github.com/ColoredCow/portal/blob/master/docs/installation.md))
- [ ] Create mail class for the functionality 
- [ ] Create command in Laravel
- [ ] Fetch non verified applications from database
- [ ] Create blade file for the mail
- [ ] Send the non verified application details to mail 
- [ ] Trigger mail 
- [ ] Send mail using queue

**Comment by belwalshubham** [comment]
![2022-07-07](https://user-images.githubusercontent.com/61574835/177817278-e1176804-0e21-4342-8a37-cd8a8279dd8a.png)
@P4NK4J  The issue  is related to which HR module ? and one more thing I have to add additional file ? which will sending remainder emails through cron in laravel

**Comment by belwalshubham** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/61574835/179174561-8d67c846-260d-474b-9204-44384bf9a139.png)
@P4NK4J  sir what I have to write under handle function given in photo

**Comment by P4NK4J** [comment]
@belwalshubham You can refer to other places what's supposed to be written in the handler. Let me know if that would help, or else we can connect offline about this.

**Comment by belwalshubham** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/61574835/179342587-798e1359-1e71-4293-b05c-650e851100f2.png)
@P4NK4J  sir why it is not running in my local machine when i write php artisan command ?

**Comment by P4NK4J** [comment]
@belwalshubham That's what you need to figure out. I see there is some error in your VS code, can you check and figure out what's wrong, also take reference how other schedulers are working

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
