### ISSUE TITLE
On the reports page for HR module, we need a count of verified applications on the tooltip

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1760]
**Describe the task**
On the tooltip present in the applications count report, in HR module. We would require adding a parameter `Verified applications : |*COUNT*|. Currently, we store the data in `is_verified` column of hr_applications table, if the applicant has verified his email, it would be 1, else it would be false. On the daily counter tooltip, we need the parameter showing number of verified applications each day
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/177720731-417b955d-1a55-4474-8559-5bbade9011cc.png">

**Comment by AnshulSaklani** [comment]
I cannot find is_verified column in hr_applications table.
![Screenshot (40)](https://user-images.githubusercontent.com/85075312/177933902-39570d30-bf0f-4e22-9d86-de2e1b125de0.png)

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
