### ISSUE TITLE
Books page, replace JS alert with modal

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1761]
**Describe the task**
Currently, when we click on delete button for a book, a JS alert appears for confirmation. We would like to replace it with a modal, that would ask users for deletion in the same manner, with a `Yes` and `Cancel` button. The background of Yes button should be red and text should be white in color. For the Cancel button, it should be gray background with white text
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/35001775/177724442-76c59163-ef18-47f0-ba6c-bf2633461e73.png">

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
