### ISSUE TITLE
Replace books count JS alert with modal form

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1765]
**Describe the task**
Currently, to update the copies available of books, under Knowledge Cafe, we use JS alert. Replace the JS alert with a modal having a form, with an input field, that will ask users to enter a number of copies. Upon clicking the save button in modal, the data should be saved in the database, as happens in the case of JS alert. We simply need to replace the alert with a modal having a form inside it. 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/35001775/177763255-06a6368c-a827-4e36-95ce-2b922d393b78.png">

For the UI of the modal, you can take references from other modals in the portal, like the ones in the evaluation section of the HR module.

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
