### ISSUE TITLE
Opportunity IDs in Job opportunity seeder

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1768]
**Describe the task**
Currently, the job opportunity seeders used to fill data in the hr_jobs table gives 0 in the opportunity id column. We want the opportunity ID to be a random number while running the seeders.

Post that, whenever we add an application from the portal, submitting this form gives an error of the required opportunity ID, we would like to have a hidden input field in this form, that will have value as an opportunity ID corresponding to the job selected from the dropdown in the same form.

You can pass job opportunity ID as an `id` tag in select job dropdown options, upon selecting any job, the input hidden field would populate the ID corresponding to the selected dropdown item. You can use JS for the same.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/177777106-762f3e28-ed43-4fd6-bfd6-64428a08851a.png">

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
