### ISSUE TITLE
Sort By Filter in HR applications listing

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1773]
**Describe the task**
Currently, in the job applications listing page under the HR module, the applications are listed as `new application` first. We would like to have a `Sort By` dropdown, next to the University dropdown. Upon clicking this dropdown, there would be two, options
```
Date
Name
```
Selecting any one of them should refresh the page and the applications should be sorted by the selected parameter.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/177937653-1a183bce-0153-4dce-bc62-3c7ab5e9fb2a.png">

**Comment by deepankar-sajwan** [comment]
The task is complete please refer screenshot
 
![image](https://user-images.githubusercontent.com/96309135/181696161-8a2282c6-3348-4e1e-9c90-8f65be22eb1a.png)

![image](https://user-images.githubusercontent.com/96309135/181696234-b1f9a9a5-d8e8-4985-9b44-dd54a834c536.png)

![image](https://user-images.githubusercontent.com/96309135/181696313-b117ab1b-ccb2-4a17-b37f-11c5480a9c89.png)


![image](https://user-images.githubusercontent.com/96309135/181696425-1e43b1aa-de8a-4ddd-b35c-0f4e27dde19c.png)
