### ISSUE TITLE
Replace the JS alert with a modal on User Management 

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1784]
**Describe the task**
In the Settings->User Management section, if we click on the remove user option, a JS alert pops up, we need to replace it with bootstrap modal, with two options `Yes` and `Cancel`, clicking on `Yes` would delete the user and clicking on Cancel button would close the modal.
The `Yes` button background can go red with text white, while the `cancel` button can be gray background with white text.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/177998777-5e3ab878-62e6-4b6e-bbe4-94620f348da9.png">

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
