### ISSUE TITLE
Add coming soon template to Leads page

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1788]
**Describe the task**
Currently, the Leads page on the portal is having an off-themed landing page. We want to change it into a coming soon page template, with Employee portal theme, branding and navigation
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/178101901-3b6b1662-3dc9-460d-9647-1d6c00ab0b2f.png">

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
