### ISSUE TITLE
On the HR recruitment reports page, add a count of total verified applications

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1789]
**Describe the task**
On the HR recruitment page, we have a count of applications appearing on daily basis. We would like to have a label next to Analytics heading, named `total verified applications - |*COUNT*|`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/178102058-0465c784-243f-40a2-873d-642f8ddcf770.png">

**Comment by LavishRawat** [comment]
@P4NK4J Do I only have to add Label (total verified applications - |*COUNT*|) or a count function next to Total Verified Applications?

**Comment by P4NK4J** [comment]
@LavishRawat Let's count the applications only those who are added after July 6th.

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
