### ISSUE TITLE
My profile UI alignment 

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1793]
**Describe the task**
When we go to my profile page after clicking on avatar icon. The image, name and email are misaligned with the edit button. We would want the profile content to be lifted up a bit, to be in the same line with edit button.
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/35001775/178200066-591cdf29-d09d-4880-842b-80397a25f45c.png">

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
