### ISSUE TITLE
Title and input alignment to be fixed on HR reporting page

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1794]
**Describe the task**
Under the HR module, while we go to the reports section, there is a misalignment between the input fields and the Analytics heading, we want them to be on the same line.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/35001775/178201741-13434bf4-d6e9-47ee-bde5-ae3acae01488.png">

**Comment by deepankar-sajwan** [comment]
The task is done pleas erefer screenshot

![Uploading image.png…]()
