### ISSUE TITLE
Error is diplayed to user on clicking A Book A Month field, available under Library dropdown in KnowledgeCafe 

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1795]
**Describe the bug**
When user clicks on the A Book A Month field, available under Library dropdown in KnowlegeCafe, the page is not loaded instead error is displayed to the user.

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/178203999-71eeeb92-73a1-4e11-b469-abd7afe26646.png)

On click on A Book A Month error is dipayed

![image](https://user-images.githubusercontent.com/96309135/178204119-e40b335f-af82-455f-b631-6b5892f8285d.png)

![image](https://user-images.githubusercontent.com/96309135/178204977-fb94801c-f4de-4fbb-bf7c-a9e7b9abcab0.png)

**To Reproduce**
1. Go to KnowledgeCafe 
2. Click on Library
3. Click on to A Book A Month
4. Error is displayed on screen

**Expected behavior**
Page should be loaded and error should not be displayed to the user

**Comment by Abhinegi2** [comment]
@deepankar-sajwan  in my portal it is not displaying any error.

**Comment by P4NK4J** [comment]
@Abhinegi2 Try adding a couple of books to your database. You will get the error

**Comment by Abhinegi2** [comment]
> @Abhinegi2 Try adding a couple of books to your database. You will get the error

@P4NK4J  i have added 5 books in my database , still not getting any error
![book](https://user-images.githubusercontent.com/108608673/178231739-b8f775c8-c97c-4741-ae9b-ddd8ab19e737.png)
![books](https://user-images.githubusercontent.com/108608673/178231763-78f63a1d-7e73-4248-84dd-5b2e55129901.png)

**Comment by Abhinegi2** [comment]
@P4NK4J , need to import here?
![here!](https://user-images.githubusercontent.com/108608673/178237858-219f8b32-300b-4596-94ed-f932b3a182ac.png)
 
 or here?
 
![HERE](https://user-images.githubusercontent.com/108608673/178237923-7dc580fb-7fca-4013-ab92-bbd7e95087a4.png)

**Comment by P4NK4J** [comment]
@Abhinegi2 You need to import the SQL dump into your database. This means, it would be done on the tool, where you can access the database. In your case, it is PHP My Admin. Let me know if that makes sense.

**Comment by Abhinegi2** [comment]
ok , i will try

**Comment by Abhinegi2** [comment]
this error comes
![error](https://user-images.githubusercontent.com/108608673/178245025-625f8ba6-0325-4313-91a4-b296753848a3.png)

**Comment by P4NK4J** [comment]
@Abhinegi2 Take your time and try figuring it out with some research. Also, you can try taking help from other fellows around
