### ISSUE TITLE
Capturing of email address input in CC and BCC field when sending email related to invoice  

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1804]
**Describe the task**
In current implementation the email  template, used for sending email to client for  invoice payment, reminder, and payment confirmation does not capture, additional email addresses that are added in CC and BCC field manually in database. It is required as every time the addidional email are added manually.

**Expected behavior**
There should be a functionality to capture the email addresses, which are added manually in CC and BCC field in email template. used for sending email to client for  invoice payment, reminder, and payment 

**References**
Specify any reference material / links

**Comment by deepankar-sajwan** [comment]
Hi @abhishekkhanduri following are the updated  requirements

- Create fields in Contact person  tab of client details to capture email to be updated in CC and BCC field
   - The contact person role will be **Secondary billing contact** it will contain email to be updated in CC field
   - The contact person role will be **Tertiary billing contact** it will contain email to be updated in BCC field
   
Also a information message should be added next to the Role field in ? symbol as following
If Role is Primary billing contact -  Email id will be used in To field of email sent to client
If Role is Secondary billing contact -  Email id will be used in CC field of email sent to client
If Role is Tertiary billing contact -  Email id will be used in BCC field of email sent to client

Refer screenshot for reference

![image](https://user-images.githubusercontent.com/96309135/179681465-5c44946a-171f-4909-94c5-109c52f39eda.png)


The email captured in the contact person tab based on the role will be available in the email sent to client

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/179683016-ab6c3031-0721-4430-9b8d-8b8b921bb627.png)

**Comment by deepakbarmola** [comment]
Seems completed as associated PRs are approved and merged hence closing the issue.
