### ISSUE TITLE
Modification required in Pending Invoice Mail  sent to client

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1807]
**Describe the task**
In current implementation, the mail is sent to client in case, payment for invoice is not recived till due date.
The mail is sent  by clicking on to Reminder Button, which opens a Pending Invoice Mail form, in which the mail body does not mention Invoice number, invoice term and invoice pdf. These are required so that client can easily refer  the invoice for which payment is due at their end.

**Expected behavior**

Following addition are required in Mail body available in Pending Invoice Mail form 

- For Client level  Invoice reminder

Hi Billing person name,

I hope you are doing great. 

I’m sure you’ve already noticed, but I just thought to check with you on the last invoice. Not sure if you could get a chance to process. 

We simply wanted to drop in with a gentle check on it. Do let us know in case there’s anything we could help with or if you’d like to share. 

The  invoice [invoice_number] for the projects for the period of [term] [year] and the total amount of this invoice is [invoice_amount]. Please find an attached copy of the invoice for your reference. 

Thanks and Regards, 
Mohit

- For Project level  Invoice reminder

Hi Billing person name,

I hope you are doing great. 

I’m sure you’ve already noticed, but I just thought to check with you on the last invoice. Not sure if you could get a chance to process. 

We simply wanted to drop in with a gentle check on it. Do let us know in case there’s anything we could help with or if you’d like to share. 

The  invoice [invoice_number] for the project [project name] for the period of [term] [year] and the total amount of this invoice is [invoice_amount]. Please find an attached copy of the invoice for your reference. 

Thanks and Regards, 
Mohit

- Also attach invoice Pdf should be sent with reminder mail

**Comment by deepankar-sajwan** [comment]
Hi @mohitsharma-22 can you please confirm whether the mail content to be sent to client in invoice reminder as per your requirement.

**Comment by deepankar-sajwan** [comment]
The update content for mail body available in Pending Invoice Mail form should be as following

Hi Billing person name,

I hope you are doing great.

The total amount of this invoice [invoice_number] is [invoice_amount]. Please find an attached copy of the invoice for your reference.

Thanks and Regards,
Mohit

**Comment by mohitsharma-22** [comment]
@deepankar-sajwan Just want to confrim that we are not removing the original content of the email?
Please check below and confirm

The complete content of the email will be 

```
Hi, Billing person name,

I hope you are doing great.

I’m sure you’ve already noticed, but I just thought to check with you on the last invoice. Not sure if you could get a chance to process it.

We simply wanted to drop in with a gentle check on it. Do let us know in case there’s anything we could help with or if you’d like to share.

The total amount of this invoice [invoice_number] is [invoice_amount]. Please find an attached copy of the invoice for your reference.

Thanks and Regards,
Mohit
```

**Comment by deepankar-sajwan** [comment]
> @deepankar-sajwan Just want to confrim that we are not removing the original content of the email? Please check below and confirm
> 
> The complete content of the email will be
> 
> ```
> Hi, Billing person name,
> 
> I hope you are doing great.
> 
> I’m sure you’ve already noticed, but I just thought to check with you on the last invoice. Not sure if you could get a chance to process it.
> 
> We simply wanted to drop in with a gentle check on it. Do let us know in case there’s anything we could help with or if you’d like to share.
> 
> The total amount of this invoice [invoice_number] is [invoice_amount]. Please find an attached copy of the invoice for your reference.
> 
> Thanks and Regards,
> Mohit
> ```

Hi @mohitsharma-22 I confirm that we are not removing orginal content of mail.

**Comment by deepankar-sajwan** [comment]
The task is complete please refer screenshot

![image](https://user-images.githubusercontent.com/96309135/181688904-e728970b-d374-4f72-8267-68821982e995.png)
