### ISSUE TITLE
Daily alert to team member if  efforts logged are  less than expected in a Project 

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1817]
**Describe the task**

There are some  projects in which team members do not logs their efforts regularly . A daily alert email should be triggered everyday at 9 am to individual team member, associated with the project(s), alerting about the team member that their  effort logged are less than expected.

The email template will contain 4 elements 
- Date : Displays previous day date
- Project Name: Display project name in which team member efforts are less
- Hours Booked: Displays efforts logged by team member
- Expected Hours: Displays expected hours for team member

The email template can be like:
```
Hello {name of team member},

We found that your logged efforts are less than your expected efforts. Please update your effort in the following project(s)

Date | Project Name | Hours Booked | Expected Hours


                                                                     
Thanks
Portal Team
ColoredCow
```

**Comment by GauravGusain98** [comment]
### Action Items
- [ ] research how we can make a custom command in Laravel
- [ ] Create a command with name `DailyEffortsAlertNotification` 
- [ ] Setup mailtrap. You can take reference from portal installation guide
- [ ] Create a mail template blade file. for now you can just type a hardcoded message in the blade file.
- [ ] Create Mail file for the `DailyEffortsAlert`. 
- [ ] Setup the mail setting in the Mail File
- [ ] From the command created above try to send a test mail
- [ ] Once you are able to send the mail, update the template based on the provided email template in the description
- [ ] Create a logic in the command file to get the projects of the user in which the hours booked are less than the expected effort
- [ ] For each such user send the mail


### Optional Efforts
- [ ] Seed the efforts of the users. For this you can use the `ProjectTeamMemberEffortSeeder` in the Project Module.

**Comment by rathorevaibhav** [comment]
Not needed anymore. We'll revisit this once we know why and how we should alert users.
