### ISSUE TITLE
Channel for job applications

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1818]
**Describe the task**
We would like to track application channels in HR module, from which channel the applications are entering in the portal. For this, we would require the following items.

- [ ] Create a migration to create a table `hr_channels`, it will have the following items:
        ```
         id - autoincrement, unsignedBiginteger
         Name - Text
        ```
- [ ] Create seeders for channels, by default we would want the following channels in the database:
       1. LinkedIn
       2. Indeed
       3. Website

- [ ] Create a migration to alter the `hr_applications` table by adding a column `hr_channel_id`, this would be a foreign key referring to the table created in first step. By default, it would be mapped to ID of channel - `website` (website would be added to channels table via seeders)

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
