### ISSUE TITLE
Portal dashboard page, under books the UI is off for longer wishlist

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1823]
**Describe the task**
In the portal dashboard, if there are more items in the books `wishlist` or `you have read` section, the UI is breaking. We need scrollable content, like the project card.
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/35001775/178673134-1a8e1c0d-aa3f-4138-8834-86a63e50201b.png">

**Comment by deepankar-sajwan** [comment]
The task is  complete
![image](https://user-images.githubusercontent.com/96309135/181080131-4e6fdcd0-44a5-4d0b-b372-ee534e0e13c8.png)
