### ISSUE TITLE
The error is dispayed on screen when clicking on View button availabe in  Analytics 

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1828]
**Describe the bug**
When View button availabel in the Analytics page is clicked  then error is diapyed on screen

Refer  screenshot

![image](https://user-images.githubusercontent.com/96309135/178706732-94695195-8b1b-458f-878e-f5ce6b258a0d.png)

![image](https://user-images.githubusercontent.com/96309135/178706829-38e8d3d4-2553-426f-999c-36080f4d2dc8.png)

**To Reproduce**
1. Go to HR
2. Click on Recruitment
3. Click on Reports
4. Click on View button 

**Expected behavior**
Error should not be dispayed to the user on screen.

**Comment by Abhinegi2** [comment]
@P4NK4J  hey, can you tell me where should i need to change ?? "controller.php" or "blade.php"

**Comment by deepankar-sajwan** [comment]
The issue has been fixed

![image](https://user-images.githubusercontent.com/96309135/179482584-fed0ec31-7d7c-4201-a520-4b2af97a716d.png)

**Comment by deepankar-sajwan** [comment]
The task is complete please refer screenshot

![image](https://user-images.githubusercontent.com/96309135/180844285-89e33708-1da5-4a99-a4d2-a2c9d9e280b6.png)
