### ISSUE TITLE
Bulk upload applications in HR jobs

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1831]
**Is your feature request related to a problem? Please describe.**
Currently, we have an application mechanism in the portal for the website only. We would require functionality to upload the applications from an excel sheet.

**Describe the solution you'd like**
We can give a bulk upload feature, where the applications can be uploaded from an excel sheet. There is already an existing implementation created (start researching with this [route](https://github.com/ColoredCow/portal/blob/master/Modules/HR/Routes/web.php#:~:text=Route%3A%3Apost(%27/excel%2Dimport%27%2C%20%27ApplicantController%40importExcel%27)%2D%3Ename(%27hr.applications.excel%2Dimport%27)%3B)). We will start with tweaking the particular section.

**Dev process to follow:**
1. Figure out a way to run the current implementation, and see to which extent it is working
2. Once we get an idea of the code changes we need to do, create issues for fixing the uploading of applications, and what's working and what's not.  **BREAKING IT DOWN IS A MUST**
3. After the applications are created, and proper mapping is done in the database, we need to figure out the best way to upload the resume corresponding to each application. We do have an existing functionality that moves portal resumes to CC websites in WordPress. We need to check if moving the resumes to S3 would be the best option (yet to be researched)
4. Bulk uploaded applications will have channels specified (database structure would be completed after issue #1818  is resolved
5. Post bulk upload, we will also include a telephonic interview round in the evaluation
6. Extensive testing would be required whether the application is created as per the website flow.
7. Post this import functionality, we will implement a telephonic interview round for this

**You are not alone**
- Reach out for help on the portal hangout channel, to get help in understanding the workflow, breakdown of tasks 

**GitHub workflow**
It would be a huge functionality, hence we will do it in a feature branch
1. Create a `feature/bulk-import-applications` branch, this branch would be like the `master` branch of the portal.
9. Breakdown the bulk upload into different phases and each phase would have a PR which upon review will be merged into  `feature/bulk-import-applications`, the main branch would then be merged into master, once the functionality is completed.
10. We will create different issues for breakdown items.

**Comment by Bahugunajii** [comment]
The issue stated above could be broken down into the following phases:
P1: Add an import excel button beside the `Add new application` button.
P2: On clicking the button, a modal should appear containing mandatory fields like `job` and `upload excel file` 
P3: Once the import is started, all applications should be mapped in the `hr_applications` table
P4: The path of the resume corresponding to each application will be saved in the `resume` column in the database

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
