### ISSUE TITLE
Pagination in Project listing page

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1836]
**Describe the task**
As the number of projects increase the projects displayed in the project listing page will also increase. 
This result in slow page loading, as the number of records are huge. 

Refer screenshot for project listing page

![image](https://user-images.githubusercontent.com/96309135/178799360-4e37c6c8-343e-4cd2-b8f1-9dd7dd945804.png)

**Expected behavior**
Pagination should be applied in the project listing page, so that it results in faster page loading. Display 10 records in each page.

**References**
Specify any reference material / links

**Comment by Abhishek25081999** [comment]
@deepankar-sajwan Sir as I have to paginate the inactive and haulted project pages but I'm unable to change the status of an active project into haulted or inactive project.

**Comment by Abhishek25081999** [comment]
@deepankar-sajwan Sorry it's Halted project instead of Haulted.
