### ISSUE TITLE
Invoice form changes to be added in Invoice modal in Project Stage billing

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#185]
We added several new fields and also changed the form layout in the invoice to create/edit screens. Those changes are not implemented in the form to create the invoice from Project Stage Billing section.

We need to add all those relevant changes here:

- [ ] Check and add missing fields.
- [ ] Fields show/hide based on invoice status.
- [ ] Change layout of the form.
- [ ] Test the complete functionality of invoice generation.

**Comment by mohitgusain** [comment]
@rathorevaibhav  , and @pankaj-ag 
I am new to  **Vue.js**, so for this issue i need to learn about **vue.js** functionality and how it works. It will take time to complete.
