### ISSUE TITLE
Replace edit button with edit icon

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1855]
**Describe the task**
Currently in Evaluation Segments, we have edit button for editing the segments, it seems like standard text, while clicking the `edit` a popup appears. We want the `edit` text to be replaced by, the edit icon shared. in second screenshot
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/35001775/178983981-f3a127d8-391f-44a4-99b4-05fa9a6ebd53.png">
<img width="536" alt="image" src="https://user-images.githubusercontent.com/35001775/178984036-34e0181a-6226-49eb-912d-0dc983ef0025.png">

**Comment by deepankar-sajwan** [comment]
The task is complete please refer screenshot

![Uploading image.png…]()

**Comment by deepankar-sajwan** [comment]
Task is complete please refer screenshot

![image](https://user-images.githubusercontent.com/96309135/180490720-f4ce33b0-8de1-4892-9b0d-e9d20a2cd84e.png)


Clicked on Edit icon and modal opens

![image](https://user-images.githubusercontent.com/96309135/180490894-f733eb76-0c77-4737-974a-4b6dfb1af194.png)


Updated and saved updated segment

![image](https://user-images.githubusercontent.com/96309135/180491592-94db1b2c-a692-44c3-bda6-7570e9eaec2f.png)

![image](https://user-images.githubusercontent.com/96309135/180491697-91a84a1d-70d2-4a88-87d3-c5abbfba0eca.png)
