### ISSUE TITLE
Close icon on add resources and add category modal

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1865]
**Describe the task**
We would like to have a close icon on the `Add resources` and Add category` modals, under HR->guidelines and resources section. Please add a close icon, clicking on which, the modal should close 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/179168718-655aff1d-8f4c-4a20-bc8f-e2edcd48eca2.png">
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/35001775/179168803-84c787b5-d72c-4992-bf28-4eaec82f1413.png">

**Comment by P4NK4J** [comment]
@gauravwsr Glad, you took interest in collaborating with us, These issues are assigned for internal training of interns in our organization. Could you pick this issue to work on #1752

**Comment by deepankar-sajwan** [comment]
Close icon is added  refer screenshot

![image](https://user-images.githubusercontent.com/96309135/180269111-39e6d36a-c785-4f7a-9d55-0d8b040d9d05.png)
