### ISSUE TITLE
Disable save category bug

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1866]
**Describe the task**
Currently the `add category` modal under HR resources, the save button is not enabled even if it has input. We want this to be functional in such a way that, if the input is empty, the button should be disabled and once there is an input, the button should be enabled.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/179169351-9b51fb05-3589-4111-883b-bd57ca8afec8.png">

**Comment by deepankar-sajwan** [comment]
The task is complete please refer screenshot

![image](https://user-images.githubusercontent.com/96309135/179671326-f3e36e89-98aa-448e-ba0e-fc905d164659.png)


![image](https://user-images.githubusercontent.com/96309135/179671348-7cc9c183-796c-4112-942f-ceeb9b94db23.png)
