### ISSUE TITLE
JS validation for Add Resources modal

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1867]
**Describe the task**
Currently, we have a modal to add resources in HR->Guidelines and Resources. Upon clicking the `Add resources` button, there appears a popup, we would like to have the following validations for the modal form. If submit button is clicked, the form should be validated with JS, and the form won't be submitted if validation fails

1. Resource URL - `Required and URL format validation` 
2. Select Category - `Required`

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/35001775/179169772-ad13aa97-730e-48c3-a551-29ee67d704ac.png">

**References**
[URL validation for JS](https://www.freecodecamp.org/news/check-if-a-javascript-string-is-a-url/)
[Required validation for JS](https://www.w3schools.com/js/js_validation.asp)

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
