### ISSUE TITLE
Disable the Save and Remove button available in the Project team member tab for Halted project

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1869]
**Describe the task**
When the Project status is updated from Active to Halted, the team member are available in the Projcet team member tab. Hence there can be instance, when somebody by mistake removes or update details of projcet members. This would result 
in issues with the projcet rsource management and project billing.

Steps to reach Projcet team members tab:

1. Go to CRM
2. Click on Projects, then click on Add new project
3. Fill form and select status as Active, then click on Save button
4. Click on the project created in step 3
5. Click on Edit button and then change status to halted 
6. Click on save button
7. Click on Projcet team member tab

**Expected behavior**
Disable the Save and Remove button in front end for Halted projects

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
