### ISSUE TITLE
The filter for selecting start date and End date for displaying FTE should be dynamic

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1871]
**Describe the task**
Currently the filter selecting start date and End date for displaying the FTE is static, as the start date is set as 1st day of  current month, and end date is set as last day of current month. Therefore only FTE of current month is dipalyed. Hence there is no methord to check FTE of past month.

Refer screenshot for refernce

![image](https://user-images.githubusercontent.com/96309135/179198864-f3957a12-50d2-4a4b-8702-fc214b21eade.png)

Procedure to reach FTE details page
- Go to CRM and click o Projects
- Click on the any project under Project Name
- Click on FTE button

**Expected behavior**
The filter for selecting start date and End date should be dynamic. On selecting start date and end date for previous month, the FTE for past month should be dispayed

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
