### ISSUE TITLE
Change reports landing page into different cards

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1877]
**Describe the task**
Currently we have reports section created in HR module, where the daily applications count appears on the landing page, if we click on reports. We would like to have different cards on the landing page, similar to screenshot shared below. The first card can have the name `Daily Applications Count`, clicking on this card, a new page would appear on which the current applications count graph would be present.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/179341538-2995fbaa-3bff-4724-97f9-7908f2c0bb5b.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/35001775/179341546-a63eee2f-37ad-41fb-8ff0-45c08d804cb7.png">

**Comment by belwalshubham** [comment]
sir according to question you said after click on report section  daily application will be appear but i dont see such things in my portal.
![Screenshot (12)](https://user-images.githubusercontent.com/61574835/180377459-c0070387-24ef-41dc-a4aa-007d2ec5be49.png)

**Comment by deepankar-sajwan** [comment]
Reports have a landing page

![image](https://user-images.githubusercontent.com/96309135/180845977-d5370198-a74b-4d2c-9f10-de1903bb4767.png)

On clicking the daily application count card we have the analytics page

![image](https://user-images.githubusercontent.com/96309135/180846293-461bf3ea-f391-4b8e-927a-554812bed3ff.png)
