### ISSUE TITLE
Functionality to add channels through UI

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1882]
**Describe the task**
On the add application page, we need a button, saying `create channels`. Clicking on which, a modal would appear. It will ask the user to input a Channel name, and upon saving the channels would be saved in the database.
The UI of the button can be similar to the one shared in the screenshot below: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/179353258-38539879-9ea1-4699-9a2a-702a93cf6aba.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/179353298-4a941d75-29ea-4244-b212-2f99bcaef7e6.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
