### ISSUE TITLE
The Last refreshed at Tag does not contains upated timestamp, when efforts are synced using refresh button

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1902]
**Describe the bug**
The **Last refreshed at**  Tag stores the updated the timestamp, when latest efforts are captured from efforthseet. When refresh button is clicked to sync latest efforts, the timestamp is not updated with latest timestamp.

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/179567397-dd6f73a3-0cdf-4016-83ac-67377f8cfdd7.png)

Clicked on refresh button

![image](https://user-images.githubusercontent.com/96309135/179567655-0f2a9697-2f34-4e5d-abc5-1f90e77a7752.png)

Time stamp not updated on **Last refreshed at**

![image](https://user-images.githubusercontent.com/96309135/179567956-3a307b1b-7b38-4745-a5a3-69859838849f.png)

**To Reproduce**
1. Go to CRM
2. Click on Project
3. Click on tooltip available under Velocity column
4. Click on Refresh button available at the bottom of page, next to project name

**Expected behavior**
**Last refreshed at**  Tag should be updated with  latest timestamp when refresh button is clicked

**Comment by GauravGusain98** [comment]
This is deployed and tested.
