### ISSUE TITLE
Change the filter available in the job applications page under the Recruitment dropdown of HR module

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1906]
**Describe the task**
Currently two filter are avilable which takes input as start year and end year of graduation. This fuctionality needs to be modified.

Please refer screenshot 

![image](https://user-images.githubusercontent.com/96309135/179708796-d619b990-18a3-4db5-be5a-a603f626f407.png)

**Expected behavior**
 We require only single filter  which takes input as year of graduation only. Once year of of graduation is selected, then on click  search icon it should display, all the applicant who have graduated in the year selected as year of graduation.

Please refer screenshot

![image](https://user-images.githubusercontent.com/96309135/179710506-c5a86e7f-5ea5-4680-9f20-fe1845252235.png)

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
