### ISSUE TITLE
Insert HR channel ID in applications table, if application is created from website

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1917]
**Describe the task**
Since we are working on a bulk import feature for the applications, we would like to have the hr_channels column used in the database for the applications table. When an application is registered from the website, we would like to save the corresponding channel ID in the database. The code logic can simply stand in the `create application functionality`. This way we will have a default value for `hr_channels_id` as a website. 
With Bulk import, we will flag the channel later.
The following steps need to be done in this task

- [x] The application creation process starts with Applicant Controller, where the applicant is created and then saveApplication is called to create an application in the database. Your first task would be to figure out that logic and build an understanding of how it's being done
- [ ] Once you figure it out, pass a variable in the controller function, to where the application is created. That variable can have the value `Website`, and within core logic, figure out a way to pick the Id of the `website` channel from the hr_channels table.
- [ ] For data in the HR channels table, you need to run the `HrChannelsTable` seeder, it will feed by default 3 values in your database.
- [ ] Once you get the channel ID, save it in the application along with the application data.

**Comment by rathorevaibhav** [comment]
LGTM
