### ISSUE TITLE
Expected hours colum available in Check FTE page should contain no of days for which efforts are expected

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1922]
**Describe the task**
No of days for Expected hours for team member should be available, under the Expected hours column available in the Check FTE page.

For Reference reference  screenshot of  No of days for Expected hours for team member, availabe in project details page

![image](https://user-images.githubusercontent.com/96309135/179948567-3251c0aa-a079-4d5f-b150-c5fe3ecfcac5.png)

Steps to reach check FTE page
1. Click on client availabel under CRM
2. Click on the Add client and fill the form to create client
3. Click on projects availabel under CRM
4. Click on add new project button, fill the form details and select client created in step 2
5.  Click on the new project created and Edit details by clicking on Edit button
6. Click on Project team member tab and add new team member
7. Click on save button, then click on check FTE page

**Expected behavior**
No of days for Expected hours for team member should be available, under the Expected hours column available in the Check FTE page.

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/179949186-7fd8c611-d2a6-4114-9095-7bde0ec59e00.png)

**Comment by rathorevaibhav** [comment]
This is working. Closing.
