### ISSUE TITLE
Backend validation for evaluation segments

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1924]
**Describe the task**
Currently, the evaluation segment on the HR evaluation page can be added if we remove the required from browser dev tools. We would like to have an additional layer of security, with backend validation. Whenever an empty submission is made, we would like to form a submission to be validated through the backend, for segment name and round name, for a required field. Once everything is in place then form submission should take place.

We can use ajax form submission method to achieve the same.

**Comment by P4NK4J** [comment]
### Breakdown

- [ ] Submit the add channel form using ajax call in JS instead of normal PHP submit. [Reference Link](https://linuxhint.com/submit-ajax-forms/)
- [ ] Check how you can pass URL from PHP to JS
- [ ] Check how you can get errors in ajax call
- [ ] Once you get an error show the errors in the add segment modal instead of showing it on the add application form
- [ ] If you don't get the error then close the modal. (Need to check how to close modal using js)
- [ ] In the backend part where you are receiving the ajax request, instead of returning a view, return a success or fail message, which will be received by the ajax request.

**Comment by GauravGusain98** [comment]
Working fine. Closing the issue
