### ISSUE TITLE
Job domain validations

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1933]
There are few issues with the implementation in adding a job domain
 
When user does not input any input domain name and clicks on save changes button, the error is displayed in background, and modal disappears,. Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/180140599-00f3cf7e-fd60-4885-8876-3faf584cbc95.png)

![image](https://user-images.githubusercontent.com/96309135/180140074-a3dec817-e8e4-48cd-b51c-d8b70adc4c44.png)

Solution: Enable save changes button only when any input is provided for damian name.

 Also single domain is added multiple times. 

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/180140979-f736b8ae-69e8-4754-93b2-7f90cb018abc.png)

Solution: If domain name with similar name is added, please dispay message to user as **Domain with similar name already exist**.

**Comment by P4NK4J** [comment]
### Breakdown

- [ ] On submitting the add segment form make a ajax call in JS instead of normal PHP submit. This will prevent the page to get reload [Reference Link](https://linuxhint.com/submit-ajax-forms/)
- [ ] Check how you can pass URL from PHP to JS as ajax call will make a request to this URL. For this you may need to check the data attribute 
- [ ] When the form data is submitted from Ajax, you will either get success or error.
- [ ] For errors, check how you can get errors in ajax call
- [ ] Once you get an error, show the errors in the add segment modal instead of showing it on main page. Till now your modal should also remain opened
- [ ] If you don't get the error then close the modal and show a success message for maybe 5 seconds. (Need to check how to close modal using js, You will need to check bootstrap elements for this step)
- [ ] In the backend part where you are receiving the ajax request, instead of returning a view, return a normal text message which will tell you if your data is processed successfully or not.

Laravel Validation - [Link](https://laravel.com/docs/9.x/validation#creating-form-requests)

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
