### ISSUE TITLE
If any active project is not found in the effortsheet, Projcet NA tag should be availabele corresponding to projcet 

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1935]
**Describe the task**
Efforts related to project are captured from the effortsheet, in case the project is not availabel in the effortsheet, then efforts are not captured for a specific projcet.

**Expected behavior**
If case efforts are being captured for a active project, and the project is not available in the effortsheet. Then there should be **Projcet NA** Tag available for that project under tha Tags column in the project listing page.
Also a informtion message should be available along with the tag, dispaying message as **Unable to find the project in the effortsheet**

**References**
Specify any reference material / links

**Comment by GauravGusain98** [comment]
### Action Items
- [ ] New keys in project Meta
    key Name - is_project_available_in_effort_sheet
    key Value - `1`/`0`
- [ ] Create config variable in project module, for example
   ```
   tags=>[
        'no-contract' => [
               'slug' => 'no-contract',
               'database-key-name' => 'no_contract',
               'title' => 'No Contract',
               'comment' => 'The project does not have a contract file'
         ]
   ]
   ```
- [ ] Show Tag as `Project unavailable`
- [ ] Show Tag definition when hover over the Tag
