### ISSUE TITLE
Team member are efforts are not preserved when adding team member for first time in the project

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1937]
**Describe the task**
Team members are added in the project, after creation project creation. Currently while adding team member when new team member is added. The efforts of previous members are lost, when adding efforts in weekly and monthly column.

![image](https://user-images.githubusercontent.com/96309135/180171843-998066b4-b8e4-4627-9157-1882b108bb43.png)

![image](https://user-images.githubusercontent.com/96309135/180171926-4d074137-a385-4d32-a7f4-6f776b54eb3c.png)

o Reproduce

Go to CRM
Click on Projects
Click on any project that has no team member
Click on Edit button and then click on Project Team members tabs
Click on Add new team member
Enter name ,designation and efforts for team members in weekly or monthly column
Click on Add new team member

**Expected behavior**
The efforts for previous team memebr should be preserved on addition of new team member

**References**
Specify any reference material / links

**Comment by rathorevaibhav** [comment]
Not happening anymore.
