### ISSUE TITLE
Can u share a link for temporal tryout or link with demo portal?

### ISSUE THREAD

**Issue by johnfelipe** [ColoredCow/portal#1951]
Can u share a link for temporal tryout or link with demo portal?

**Comment by deepankar-sajwan** [comment]
Hi @johnfelipe thanks for showing intrest in portal. If you are comfortable in having a short virtual meet, I would like to show you live demo of portal.

**Comment by johnfelipe** [comment]
Can u share a video demo.
I want to know if is good for our university for data portal.

**Comment by deepankar-sajwan** [comment]
Hi @johnfelipe sorry to inform you that, if you want demo video of portal it will take some time.  I would recommend you for a live demo, through virtual meet as per your convenience.

**Comment by deepankar-sajwan** [comment]
Closing this task as the  video demo was not available
