### ISSUE TITLE
Change color of total count text and icon

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1953]
**Describe the task**
We need to change the color of the total count button and its icon. We need to match it with the same color as others

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/35001775/180368708-d9033344-6765-40d7-b530-ecfff516fb9d.png">

**Comment by deepankar-sajwan** [comment]
The task is complete please refer screenshot

![image](https://user-images.githubusercontent.com/96309135/180494178-378fa019-3d42-41f6-b6aa-c383ee738743.png)
