### ISSUE TITLE
In clients page provide image icon  of the employee assigned as key account manager

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1957]
**Describe the task**
The clients page dispays all the clients and key account manager asscociated with those clients, hence we require a image icon next to person assigned as key account manager.

**Expected behavior**

![image](https://user-images.githubusercontent.com/96309135/180376610-4d1bd77b-2119-46b6-b9d9-37e38f7ae6a5.png)

**References**
Specify any reference material / links

**Comment by rathorevaibhav** [comment]
@deepankar-sajwan I think we can just keep the icon like we show in the HR page and remove the name of the user.

Then name can come up when user hovers on the user profile icon. Like the image below:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/12053186/180403992-efd9afeb-1357-4a9e-80b6-0744f291489b.png">

**Comment by deepankar-sajwan** [comment]
Thanks for update @rathorevaibhav we will keep the implementation as mentioned by you in your comments

**Comment by deepankar-sajwan** [comment]
Hi @tarunnjoshi please find updated requirement as follows

- The image icon should be available under the key account manager
- On hovering the image icon the name of the person  should be availabel
