### ISSUE TITLE
Fix Books page. Not able to add books on the page

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#1958]
**Describe the bug**
Books page  ((https://portal.coloredcow.com/knowledgecafe/library/books). Is not working. I am not able to add books on the page. Please fix it.

**Screenshots**
<img width="1111" alt="Screenshot 2022-07-22 at 12 41 33 PM" src="https://user-images.githubusercontent.com/16541548/180384501-88932408-44e5-4e2f-abe5-fcb04401cf02.png">

**Comment by P4NK4J** [comment]
There is already a ticket created for this, #1825 Hence closing this one.
