### ISSUE TITLE
Create functionality to store the history of invoice email 

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1959]
**Describe the task**

Finance department sent email realted to invoice to client in following scenarios

Requesting payment for a project work, done by the company for the client
Reminder in case payment for the project work, not received from the client.
Payment confirmation in when, payment for the project work received from the client.

At present there is no implementation for checking history of invoice email sent to client.

**Expected behavior**
We require a functionality through which we can view the history of invoice email sent to client.

- [x] #1960
- [x] #1961
- [x] #1962

**References**
Specify any reference material / links

**Comment by GauravGusain98** [comment]
We need to show the time format in this form
<img width="323" alt="image" src="https://user-images.githubusercontent.com/54376313/180599856-fd035628-ec48-4b0f-8ed9-57f4f7b7cf1d.png">
