### ISSUE TITLE
Count of resources needed in job opportunities

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#1964]
**Describe the task**
On the job opportunities listing table, we need editable two columns. One will have a table cell next to the opportunity type, where we can add the count of resources needed. The heading of this column can be `Resources Required`.  Next to this, we can have an edit option (with an edit icon similar to as shared in the screenshot), clicking on which a modal should appear, which will ask for a number of resources needed, clicking on saving, would submit the form and save the resources required corresponding to each job opportunity.
This data would be saved in the hr_jobs table, we need to create a separate column `required_resources` and save the information in that column.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/180388949-16367d66-3e6b-4442-a480-93593269e29d.png">
<img width="155" alt="image" src="https://user-images.githubusercontent.com/35001775/180389740-71728bcd-fb91-4816-843d-153beea065ac.png">

Once these details are saved, on the listing page under details, we would like to have a tooltip icon next to job title, upon hover, we will have the following information:
Total resources required - |*COUNT*| (fetched from `resources_required` column)
Total applications available - |*COUNT*| (this will have all the applications with status `in-progress` and `new` corresponding to the job role)
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/35001775/180390115-db517111-3d05-45f1-94c9-027b6238782c.png">

**Comment by P4NK4J** [comment]
Breakdown of the issue:

- [ ] Create a migration to alter table `hr_jobs`, to add an integer column named `resources_required`
- [ ] Provide two columns next to job opportunity type, as per the screenshot above
- [ ] First column will have count of resources required per opportunity
- [ ] second column will have edit icon, clicking on which a modal would appear asking for user input corresponding to job opportunity
- [ ] Clicking on save button in the modal should update the resources required count in the database
- [ ] On the listing page, under details add a tooltip
- [ ] This tooltip will have the information of total resources count corresponding to the job role/opportunity and total applications available in `Open` section, open applications mean they have `in-progress` or `new` status in the database.

You can check for existing queries available in model file, if not, you may need to create one to fetch the details
- [ ]

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
