### ISSUE TITLE
Add start date and end date for fixed billing projects

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#1966]
**Describe the task**
We need to track the project duration so that we can determine the team allocation status. Right now, there are some projects which have zero actual effort but there are team members assigned to those projects.

These projects are a problem because they do not give a clear projection of the project status and for how long the project will be open.

**Expected behavior**
- [x] When creating a new project, if the user selects fixed budget project type, two fields should show up. When user selects any other option than fixed-budget, these fields will be hidden. 
- [x] The two new fields will be non-mandatory and will capture start and end date for the projects.
- [x] When editing a project, if the project already has fixed budget selected, these two fields should show up.
- [x] When editing a project, if the project is monthly billing, then these fields should NOT show up. When the project type is changed and selected to fixed-budget, then these two fields should show up again.
- [x] We already have `start_date` and `end_date` columns in the `projects` table. No need to create two new columns. We'll use them.
- [x] Upon creating and editing projects, these two fields should be saved in DB.
- [x] In the project view page (`/projects/{project-id}/show`), add these two fields as readable fields.

**Comment by GauravGusain98** [comment]
working fine. Closing
