### ISSUE TITLE
In dashboard page the Library template headers need improvement

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1992]
**Describe the task**
Currently the headers of the Library template are not uniform is allignmemnt. 

Please refer screenshot

![image](https://user-images.githubusercontent.com/96309135/180729469-6a298d12-5ccd-4712-bbd7-4ecd30c66dae.png)

Steps to reach Dashboard page
- Click on Employee Portal  next to HR 
- Dashboard page is available

**Expected behavior**
The allignmnet of the headers for Library template should be as shown in screenshot below

![image](https://user-images.githubusercontent.com/96309135/180730328-f7d7ea90-3f4a-473e-afe2-ab0eb159e289.png)

**References**
Specify any reference material / links

**Comment by deepankar-sajwan** [comment]
Hi @saurabhpatel123456 can you please add your profile pic in the GitHub

**Comment by saurabhpatel123456** [comment]
done sir

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
