### ISSUE TITLE
Need improvemnet in  the date format for graph dipalying the efforts for the project

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1997]
**Describe the task**
Currently, efforts logged by all the team members are captured and displayed in the graph. The graph includes the Bar plot for each day, and also the date under it. Instead of the date, we should mention the day and month like 01-July.

Please refer screenshot for the current implementation

![image](https://user-images.githubusercontent.com/96309135/180772791-299c75ff-b58f-4125-aad3-9a9f20ef9ae2.png)
  

**Expected behavior**
The date under the bar plot of the graph should be replaced by the day of the month and month like 01-July

**Comment by deepankar-sajwan** [comment]
Hi @akriti12negi can you please add your profile pic to the your GitHub profile

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
