### ISSUE TITLE
Apply pagination in client listing page

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#2001]
**Describe the task**
Apply pagination on the client listing page. The number of clients per page should be 20

Steps to reach Clients page
- Go to CRM
- Click on Clients

**References**
Specify any reference material / links

**Comment by deepankar-sajwan** [comment]
Hi, @gulshan81 please refer the screenshot of the page where you have to apply pagination. You have to apply pagination for both Inactive and Active clients.

![Uploading image.png…]()

**Comment by rathorevaibhav** [comment]
Not needed right now.
