### ISSUE TITLE
Button alignment fixes on HR job application listing page

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2003]
**Describe the task**
The add new application button and search button are a bit off in vertical alignment, we would want them both to be on the same line. 
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/35001775/180834398-33aecf5d-e0a2-422e-9a83-30af7e68fc4f.png">

**Comment by GauravGusain98** [comment]
Looks fine on UAT closing
