### ISSUE TITLE
HR module reporting phase 1

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2005]
**Describe the task**
On the HR reporting page, we would like to have a card adjacent to Daily Applications Count, this card should be named, `Job Role Engagement`.

On clicking this card, a horizontal bar graph should appear, with different colors, indicating each job role and the number of applications we have received. The graph is of the following UI, where the highest applications job role would be on the top and followed by decreasing ones. 
On the Y axis, we can map the job roles

<img width="607" alt="image" src="https://user-images.githubusercontent.com/35001775/180850559-e695b6b6-43f7-4cd1-9f68-ca37df8b1326.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
