### ISSUE TITLE
Automated email to Key Account Manager if a fixed budget project surpasses end date but is still active

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#2011]
**Describe the task**
For fixed budget projects, we need to identify inactivity and let key account manager take action if the project end date is in past and the project is still active.

**Expected behavior**
Every day at 9am, an automated email should go to key account managers for whom their fixed budget projects have surpassed end date but the project is still inactive.

The email content will be:
```
Hi username,

There are some projects that have reached their end date but are still marked as active. We need you to take action so that the team can get clarity on active projects, the team's availability and assign other projects accordingly.

1. Project name - Link
2. Project name - Link

To view all your projects, you can use this link (there will be a link to my projects page).

Thanks
ColoredCow Portal
```

In the email above, the following things will be dynamic for every email recipient:
1. Username
2. Project name and link

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
