### ISSUE TITLE
Filter by date button in HR reporting daily applications count is showing error

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2013]
**Describe the task**
Currently, if we select the date filter in the HR date-wise filter, the portal is throwing an error. We want to fix the date filters
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/180997977-c188901d-fd16-4aa4-acc1-2d937058b759.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/180997993-99a3eb1d-a7a9-478b-ae99-c5d5d0595d02.png">

**Comment by GauravGusain98** [comment]
this is working. Closing it now.
