### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2020]
**Describe the task**
Currently, we have a block in readme, where we need to change the project path. We have defined `path/to/your/project` as a placeholder. But in readme, we have written `Copy the absolute file path for the public directory of the project and paste it below where your_project_path is written`. Replace `your_proejct_path` with `/path/to/your/project` in the sentence written above.

```
<VirtualHost *:80>
    ServerName portal.test
    DocumentRoot "your_proejct_path"
    <Directory "your_proejct_path">
        DirectoryIndex index.php
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>

```

**Comment by Jkishan544** [comment]
resolved

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
