### ISSUE TITLE
Tooltip available in the project listing page should be right alligned

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#2024]
**Describe the task**
The tooltip available on the project listing page is currently left aligned.

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/181174967-739bdb5c-f19b-4d03-8e79-3d9788ed0da3.png)
 

**Expected behavior**
The tooltip should be right-aligned

![image](https://user-images.githubusercontent.com/96309135/181178576-a5a73f57-4143-41a1-82bd-adb0312de676.png)

**Comment by rathorevaibhav** [comment]
Unclear requirements. Closing.
