### ISSUE TITLE
Salary deduction breakdown based on gross salary

### ISSUE THREAD

**Issue by Abhishek-Khanduri** [ColoredCow/portal#2026]
**Describe the task**
As we have breakdown the salary in some parts, based up on gross salary, we now need to further breakdown salary deduction for a month.

Here's what need to be added:

- Employee ESI
- Employee EPF
- TDS
- Loan Recovery
- Food Deduction
- Total Deduction
- Advance Salary
- Net pay

**Expected behavior**

- [x] The above fields should be read only and should dynamically change (reactive) as the user edits the gross salary.
- [x] If the gross salary is already set, these fields should be calculated on page load.
- [x] Deduction fields should be highlighted in both employee salary page and global setting page.

#1971, #1844, #1438

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
