### ISSUE TITLE
Toast message should be  shown to user while adding new invoice or updating invoice status 

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#2033]
**Describe the task**
When a new invoice is added or the status of an existing invoice is updated, then a success message is shown to user on screen.

Procedure to add a new invoice 
1. Go to Finance
2. Click on Invoices
3. Click on Add new invoice
4. Input details, add the sent date as 10th June, and the due date as 17th June, and click on create button.

Procedure to add update invoice status
1. Go to Finance
2. Click on Invoices
3. Click on the invoice number of the invoice
4. Update the status of the invoice as paid and click on the save button

Please refer screenshot for the current implementation

Success message in invoice creation

![image](https://user-images.githubusercontent.com/96309135/181218469-c07e5b0d-f913-4b93-b01f-800311399088.png)

Success message on updating the status of the invoice

![image](https://user-images.githubusercontent.com/96309135/181219832-eb76f481-ee51-4e1e-afa7-d667aa887123.png)

**Expected behavior**
The user should display a toast message in case a new invoice is added or the status of the existing invoice is updated. The content of the message should be the same as shown screenshot available in the description of the task

Please refer implementation of the toast message done while adding a new client and updating the client details.

Refer to screenshot of toast message available on adding a new client 

![image](https://user-images.githubusercontent.com/96309135/181233976-5ceb485f-ac53-447f-b6fd-2d461dbf6f0c.png)

**Comment by GauravGusain98** [comment]
this is working fine.
