### ISSUE TITLE
The timeline should be available in the project details and check FTE page

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#2039]
**Describe the task**
The project efforts are logged in between the start date and end date available in the month, based on the start date of the project. Hence efforts are logged in the project based on a specific timeline. Therefore we require a timeline to be specified on the project details page and check the FTE page.

1. Go to CRM
2. Click on Clients
3. Click on Add client button, and update the form, then click on the save button
4. Go to CRM
5. Click on Projects
6. Click on Add new project and update form, then click on the save button
7. Click on the project created in step 5, then clicks on the Edit button.
8. Click on the Team members tab and add team members for the project
9. Click on the save button

**Expected behavior**
Please refer screenshot for the display of the timeline in projects details and Check FTE page

![image](https://user-images.githubusercontent.com/96309135/181462236-671522cc-0189-469f-8c2a-fd33a5c34181.png)

![image](https://user-images.githubusercontent.com/96309135/181461823-5e6f4b26-82aa-4306-8536-7a565036fdfd.png)

**References**
Specify any reference material / links

**Comment by LavishRawat** [comment]
Closing the issue as it is completed.
