### ISSUE TITLE
Google chat integration with portal for sending messages related to invoice

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#2043]
**Describe the task**
Currently, the finance team sends a message on the Billing channel, created in google chat to the project team member for confirming billing hours.  When an invoice for the project is sent to the client, through email then a message is sent to team members updating that invoice is sent for the project

**Expected behavior**
Integration of google chats with portal so that the finance can send, messages to project team members related to invoices through the portal.

**Comment by GauravGusain98** [comment]
This is done. Closing this now.
