### ISSUE TITLE
Toast message should be added in the library module 

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#2045]
**Describe the task**
Currently, there are no messages available in the library module in the following scenario
- New book added 
- New category for book added
- Updating category for the books

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/181438201-f43f1a65-daad-4963-a0ee-1a8b0118caab.png)

![image](https://user-images.githubusercontent.com/96309135/181438262-af4d6775-8b5a-42b3-9f31-03dcab2a5b3e.png)

Steps to recreate the above scenario
- Go to Library
- Click Add New Book
- Click on Book Category and then click on Add Category
- Click on the Edit button and update the book category

**Expected behavior**
The following message should be available and should be displayed as a Toast message
- New book added   
   Message: Book added successfully
-  New category for book added  
   Message: Category for books added successfully
- Updating category for the books
   Message: Updated  category for books 

For reference check the implementation of the Toast message when adding a new client or adding a new project.

**Comment by GauravGusain98** [comment]
Tested and working fine. Closing
