### ISSUE TITLE
Addition of message in user management

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#2047]
**Describe the task**
In the current implementation, there is no message displayed to the user in the following scenarios
- User role is updated
- User is removed
- Permission related user is updated

Please refer screenshot for user management

User role is updated by Manage user roles 
User is removed by Remove user
User permissions are updated in the Roles tab

![image](https://user-images.githubusercontent.com/96309135/181485407-80e487e6-6eb8-495c-b9e7-113b77c74e74.png)

 

**Expected behavior**
Toast messages should be available to the user in the following scenarios
- User role is updated
   Message: User role updated successfully
- User is removed
   Message: User removed successfully
- Permission  related to the user is updated
  Message: User  permissions updated successfully

Please refer implementation of the toast message done while adding a new client and updating the client details.

Refer to screenshot of toast message available on adding a new client 

![image](https://user-images.githubusercontent.com/96309135/181233976-5ceb485f-ac53-447f-b6fd-2d461dbf6f0c.png)

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
