### ISSUE TITLE
Flagging applications for desired resume 

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2049]
**Describe the task**
Current while the resume is filtered, we would like to have an option of flagging the resume which seems to be the desired one for a particular job role. You need to follow these steps to achieve the functionality

- [x] Create a migration to alter table, `hr_applications`, that would add a column `is_desired_resume` which would store binary values 0 or 1. By default, this column would have a value as 0
- [x] On the resume screening page, when we click on the resume icon, there opens up a dialog box with close and open in new tab icon. we would like to have a flag button icon, next to the `open in new tab` icon, clicking on which a popup should appear, having a text editor, asking users, `why do you think this is a desired resume`? Users can fill in the form. Upon submission, an ajax call should go in the backend, changing the `is_desired_resume` value to 1 corresponding to the application. Simultaneously it should store the value of the input in the `hr_application_meta table`, with the key `resume-flag`. 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/35001775/181494642-91afae0b-39ab-4107-a0f1-ff1741664b90.png">

- [x] On the resume screening section, in evaluation. We will be needing a `sample desired resume` link, which would open up in a new tab, the landing page should have a table with two columns, the resume icon (clicking on which the resume should open up as per the dialog box in second step), and the second column should have user inputs added `why you think the resume is desired`. 
<img width="793" alt="image" src="https://user-images.githubusercontent.com/35001775/181494448-95fc9a3b-e1eb-4a8f-be8a-e19fcc8bbd47.png">

- [x] Remember this link should have a resume on the basis of job role, we would require only those applications corresponding to which we are clicking on the `sample desired resume`. You can achieve this by passing job ID in GET parameter of the landing page URL, then mapping the application ID with the Job ID.

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
