### ISSUE TITLE
Email-id of Contact person assigned as Tertiary billing contact is not availabel in BCC field 

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#2052]
**Describe the bug**
Client details contain the contact person details based on their role. The contact person whose role is assigned as the tertiary billing contact, his email-id is used in the BCC field of email sent to the client for payment request, payment reminder, and payment confirmation. 

**To Reproduce**
1. Go to Clients
2. Click on the Contact person
3. Input details of the tertiary contact person
4. Click on save 

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GauravGusain98** [comment]
This is working fine. Closing
