### ISSUE TITLE
On clicking on the image of Key account manager FTE details are available

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#2058]
**Describe the bug**
In the client listing page under the key account manager column clicking on the image, results in displaying FTE details of the key account manager.

Refer to screenshot for error

![image](https://user-images.githubusercontent.com/96309135/181605263-f9c41813-493a-493d-963f-7cb1e8f4abdd.png)

![image](https://user-images.githubusercontent.com/96309135/181605344-47f2feb1-0687-400a-9f91-d0d50908d8f6.png)

**To Reproduce**
1. Go to CRM
2. Click on Clients
3. Click on the image available under key account manager

**Expected behavior**
FTE details of the Key account manager should not be displayed to the user

**Comment by GauravGusain98** [comment]
Tested and working fine. Closing
