### ISSUE TITLE
Store Custom Template File name in Database

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2073]
**Describe the task**
Need to create a UI for inserting custom invoice templates name for the Client. This is needed to fetch the invoice template for the client while generating the invoice. Currently, we are storing it in the env. We want to fetch this data from database 

**Expected behavior**
Store the template file name in DB

**References**
NA

**Comment by deepakbarmola** [comment]
Closing the issue as linked PR is approved and merged.
