### ISSUE TITLE
Authorization checks on routes

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#208]
Authorization checks are currently applied on controllers. To add another level of security, apply authorization on routes.

**Comment by Satendra-SR** [comment]
@rathorevaibhav 
please let me know what type of authorization are you talking about.
In web.php file, authorization is already there. the following middleware is already in use.

`Route::middleware('auth')->group(function () { }`

**Comment by Satendra-SR** [comment]
> @rathorevaibhav  **and I have discussed on this issue and what I understood is:**
* The **_authorization checks_** are present there in **controllers** but we have to insure the **security**. So what we deiced that there should be some kind of **authorization** there in  the **_routes_** aswell.

**Comment by Satendra-SR** [comment]
What  I understand yet is, We have various **_Middlewares_** that are already defined in `kernel.php`.

![screenshot from 2018-06-19 17-04-23](https://user-images.githubusercontent.com/39792899/41595270-c2d3189c-73e3-11e8-978b-8a2d9ed5434b.png)
@rathorevaibhav 
@nishanth-kd 
So, should I use one of these **Middleware** (most probably : **_role_**) or should I define new **_Middlewares_** for **_authorization_** purpose.

**Comment by rathorevaibhav** [comment]
@Satendra-SR 

Here are the links you can visit to know more about authorization checks in routes:
1. Spatie Laravel permission package (we're using this)
    https://github.com/spatie/laravel-permission#using-a-middleware
2. Laravel authorization documentation
    https://laravel.com/docs/5.6/authorization#via-middleware

**Comment by Satendra-SR** [comment]
@rathorevaibhav 
#208
based on the [conversation](https://github.com/ColoredCow/employee-portal/pull/526#discussion_r203722450), should we continue to do this, or we have any other way to implement this?
