### ISSUE TITLE
Change color of Total Count 

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2088]
**Describe the task**
On the HR listing page, we need to change the color of the Total Count section and make it similar to the other tabs. Refer to screenshot below for reference.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/182125830-7a196cb7-49c4-48a4-9ad9-aa83dc02d649.png">

**Comment by Jkishan544** [comment]
@P4NK4J  please review
