### ISSUE TITLE
Manage Evaluations Round wise segments

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2097]
**Describe the task**
On the Manage evaluations page under HR navigation, we have all the segments listed currently. We would like to categorize these segments into different rounds on UI, as per their mapping of the database.
If a segment is associated with Resume Screening, then we can have an accordion Resume Screening, and all the segments related to this round, can be listed in that accordion. We can keep the segments table UI the same, enclosing it inside a Bootstrap accordion.
For accordion, you can take UI reference from the applications edit page, under the canvas of accordion can go the segments table. For this page, let's keep the background of accordion as the current page color is
If a new segment is created, it should appear inside an accordion of the respective round.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/182329483-cc4d5374-5098-416a-92e0-3d3be3e0fa8d.png">
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/35001775/182330335-a7ea4d6d-49f5-47f9-91db-10c9ad04f73a.png">

**External references**: We store evaluation segments corresponding to HR Round in HR evaluation Segments table

**Expected behavior**
A clear and concise description of what needs to be done.

**References**
Specify any reference material / links

**Comment by LAKSHYA0501** [comment]
Sharing the breakdown and approach
- [ ] read about bootstrap accordion.
- [ ] convert the table on the UI into accordion.
- [ ]  test the segememnts whether edit and delete is working fine after adding or deleting
- [ ]  in the controller data is being passed modify it in such a way that it should return all the segments corrosponding to a round, it can be a multi-dimensional key value pair array.
- [ ] to get the all the segments corresponding to a round you can use laravel relationships [hasmany] for one round and belongs to for segement.
- [ ] you can look checkout the existing code base for refernce how relationship works.
- [ ] once we have the data in blade file create different accordians as per the data  structure.
- [ ] accordions should appear only for those rounds for which segments are present in db.
- [ ] test the overall segment functionality whether edit or delete is working fine or not.
- [ ] upon adding a new segment corresponding to a round it should populate to a UI.

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
