### ISSUE TITLE
Show Total Estimated Hours for fixed billing projects

### ISSUE THREAD

**Issue by Abhinegi2** [ColoredCow/portal#2112]
**Describe the task**
We need to trace the  Total Estimated Hours for fixed budget billing.

**Expected behavior**
- [x] When creating a new project, if the user selects fixed budget project type,  ` Total Estimated Hours ` should show up. When user selects any other option than fixed-budget, this fields will be hidden. 
- [x] The   ` Total Estimated Hours `  field  will be non-mandatory .
- [x] When editing a project, if the project already has fixed budget selected, this  field should show up.
- [x] When editing a project, if the project is monthly billing, then this field  should NOT show up. When the project type is changed and selected to fixed-budget, then this field should show up again.
- [x] We already have ` Total Estimated Hours `  column in the `projects` table. No need to create  new column. We'll use them.
- [x] Upon creating and editing projects, this field should be saved in DB.
- [x] In the project view page (`/projects/{project-id}/show`), add this field as readable fields.

**Comment by rathorevaibhav** [comment]
This is done. Closing.
