### ISSUE TITLE
Show user profile on employee page

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2113]
**Describe the task**
Show the profile page basic details section that is shown in the below image on the employee page. On employee page create a new tab with name `profile details`. On clicking on this tab the profile details of the user should be shown.

**Expected behavior**
Show this 
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/54376313/182550223-db69d5ae-bcc7-4fbb-880f-172795adeb22.png">

On this Page 
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/54376313/182550346-fe8c199c-7eef-4762-990d-672ae8e7e289.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
