### ISSUE TITLE
Make library page responsive

### ISSUE THREAD

**Issue by mdshamoon** [ColoredCow/portal#2118]
**Describe the task**
The library page does not look good on mobile screen. We should make the page responsive so that it looks good on every screen size.

**Expected behavior**
There should be a maximum of two cards on the mobile screen and text should be within the card.

**Screenshots**
<img width="294" alt="image" src="https://user-images.githubusercontent.com/32592458/182594975-3d3a959c-0b2e-45fc-9a42-1e0b32b94897.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
