### ISSUE TITLE
Interview duration

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2155]
**Describe the task**
This issue needs to be done in two phases
 Phase 1 : Update UI for current screening page
- [x] Separate the Date and Time inputs into two different fields. `Scheduled Date`, `Scheduled Time`.
- [x] #2261
- [x] Test the existing form flow, when updating a schedule with the changed structure, the functionality should work as it was working earlier.
<img width="745" alt="image" src="https://user-images.githubusercontent.com/35001775/183371224-1b881d23-3ba5-4162-b5fd-131aae5335e9.png">
Phase 2: Add the finish Interview button

- [x] Create a migration for `hr_application_round` table, adding a column `meeting_duration` next to `scheduled_end` column. 
- [x] For rounds only where we need calendar events, provide a `Finish Interview` button left to the pencil icon, clicking on which, an ajax call should go in the backend and save the interview time in the column created in first step. Interview time would be the difference between, `scheduled_date` timestamp and the time when `Finish Interview` button is calculated.
<img width="755" alt="image" src="https://user-images.githubusercontent.com/35001775/183372492-862715fa-7140-4337-972f-4505e40c9743.png">

- [x] Once the duration is saved, the interview duration should appear in place of the `Finish Interview` button. You can add a spinner in UI meanwhile the backend is processing, but that's optional. 
- [x] When a round is completed, we get `Accepted in this round` and `conducted date` information on the card title, you can add below them the interview duration UI piece.

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
