### ISSUE TITLE
Add location column in library books table

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2160]
**Is your feature request related to a problem? Please describe.**
In library books table create a location column of type string and nullable

**Describe the solution you'd like**
- [x] Create a migration file to create the column 

**Describe alternatives you've considered**
NA

**Additional context**
Take reference from [this link](https://laravel.com/docs/9.x/migrations#creating-columns)

**Comment by tarunnjoshi** [comment]
@GauravGusain98 sir, Please describe it more i am not understanding the problem.

**Comment by GauravGusain98** [comment]
> @GauravGusain98 sir, Please describe it more i am not understanding the problem.

@tarunnjoshi you need to add `location` column in the database table `library_books`. For this you need to read migration concept in Laravel
