### ISSUE TITLE
Active job application tab while evaluating internship application

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2161]
**Describe the task**
Whenever we evaluate an internship application, the ` Job application` tab becomes active, while the internship tab should be active
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/35001775/183644723-b942f9f5-980d-405e-b0bf-7e35848c7372.png">

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
