### ISSUE TITLE
The project details are not getting stored

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2169]
**Describe the bug**
When we save the project details in the project edit page and the project billing level field is not selected, in that case success message comes up while saving the details but we actually get error from the backend that billing level is required. 

Step 1: Donot select any option in billing level field and also update any other field to check if the data is getting saved or not
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/54376313/184074754-e90f6e1d-7f70-47bb-bef9-001fa119ac0c.png">
 
Step 2: Save the form
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/54376313/184074864-cc14323e-db93-42c0-88e4-1a006d7af0b4.png">

Step 3: Check the error in network tab
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/54376313/184075035-6a085743-7f65-46fc-bf1b-f88fe6004f32.png">

**Expected behavior**
If there is any error coming from backend, we need to show error messages and the success message should not come 

**Additional context**

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
