### ISSUE TITLE
Book borrowers can't be greater than the number of copies available

### ISSUE THREAD

**Issue by mdshamoon** [ColoredCow/portal#2170]
**Describe the bug**
A book having two copies has three borrowers. This can't be possible in real life.
We need to add a restriction that does not allow borrowing a book if the number of copies and borrowers are same.

**To Reproduce**
1. Go to books page
2. Try to borrow a book with one copy that is already borrowed by someone. 
3. The system allows you to do that

**Expected behavior**
It should not allow the user to borrow the books if the number of copies are finished. It should show an error saying `Sorry ! No more copies of this book available right now.`.

**Screenshots**

A book having two copies and three borrowers
<img width="416" alt="image" src="https://user-images.githubusercontent.com/32592458/184076812-1b517a77-3dfa-4905-9a94-53e68a663f55.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
