### ISSUE TITLE
Redirection links to individual projects page

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2172]
**Describe the bug**
In `Projects->My projects`, the redirection to the individual project are not provided. 

**Screenshots**
<img width="1440" alt="Screenshot 2022-08-11 at 12 54 23 PM" src="https://user-images.githubusercontent.com/73119570/184084657-9f7b5b95-b840-4aa8-bb77-546cb1c1849c.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Projects->My Projects
2. There is no redirection link present in each project name.

**Expected behaviour**
- The redirecting link should be preset only for the projects under `My Projects` tab.

**Comment by deepakbarmola** [comment]
The task is implemented hence closing the issue.( Redirection link to project is present)
<img width="1251" alt="image" src="https://github.com/ColoredCow/portal/assets/104838291/235cbeb3-28c9-4845-90c9-c6dad9874e82">
