### ISSUE TITLE
CC and BCC field available in the email body does not have email validation

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2174]
**Describe the task**
When pending invoice email or payment confirmation mail is sent to client from portal, then the email body used was sending email contains **CC**  and **BCC** field do not have email validation. If we mention the email address as **abcdgmail.com** in BCC and CC fields, the mail is sent without any error displayed to the user.

Procedure to check pending invoice  reminder mail 
1. Go to Finance
2. Click on Invoices
3. Click on Add Invoice
4. Fill the form input sent date as 10th June 2022 and due date as 18th June 2022
5. Click on the save button
6. Change status as Pending on Invoice page
7. Click on the Reminder button available under the Email column
8. Fill in details in the form and check the error

Refer screenshot
![179501701-78589cce-6dfe-49eb-9e7b-54625e6c3b2a](https://user-images.githubusercontent.com/73119570/184133815-f799e660-6afa-4066-9226-a2b08175b4b4.png)

**Comment by deepakbarmola** [comment]
Closing the issue as linked PRs are approved and merged.
