### ISSUE TITLE
CC and BCC field available in the email body does not have email validation

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2175]
Procedure to check the payment confirmation mail 
1. Go to Finance
2. Click on Invoices
3. Click on the project available under Project Name
4. Update the status of the invoice from sent  to paid
5. Click the to send a confirmation mail
8. Fill in details in the form and check the error

Refer screenshot

![image](https://user-images.githubusercontent.com/96309135/179501503-07d4994d-fcb4-4258-b346-9961e86a2dcc.png)

**Expected behaviour**
The email should not be sent if the mail format is not correct. Also, the message should appear as available in the screenshot 

![image](https://user-images.githubusercontent.com/96309135/177751982-5de0d659-b2b1-4098-89e0-a8553a7ee7d2.png)

For reference check mail validation applied in the **From** field of the mail template

**Comment by deepakbarmola** [comment]
Closing the issue as associated PR is merged with acceptance.
