### ISSUE TITLE
Team Interaction Round email

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2178]
**Describe the task**
Whenever we send someone in a team interaction round, we invite them to the office for a meeting. Currently, whenever we move someone to a team interaction round, the system triggers an email for scheduling their team interaction interview. We want the system to send a customized email based on some input information. You need to perform the following tasks

- [x] Create an email template for the Team interaction round through seeders, taking reference from Resume screening and introductory call. This email template would be a scaffolding for the email and will be available in settings area, like others. The email template can be 
```
Hello |*APPLICANT NAME*|, 

We are very pleased to inform you that you have been selected for Team Interaction Round at ColoredCow. For the proceedings, we would like to invite you to our office at  |*OFFICE LOCATION*| on |*DATE SELECTED*| between |*TIME RANGE*|. 

Your presence would be awaited. In case you have any questions, feel free to reach out.

Thanks, 
HR team, 
ColoredCow
```

- [x] When an application is moved to the team interaction round, currently, it awaits for calendar schedule and functions accordingly. You can test it out. We would like to remove that functionality. When an application is moved to the Team interaction round, we would like to invite applicants to the office location, hence we need some custom inputs from the interviewer moving an application to Team Interaction Round

- [x] When the `Take action` button is clicked after moving an application, a popup should appear. This popup would contain three different fields, Office location, Date, start time, and end time. In the end, there can be a `Generate Email` button

- [x] After filling in this information and clicking on `Generate Email`, an ajax call should go in the backend and replace the variables in the template created in the first step. The start time and end time will be shown in email template like, (10:00 am - 3:00 pm) The final email would then appear in the rich text editor as shared below
<img width="800" alt="image" src="https://user-images.githubusercontent.com/35001775/184209292-9eef379a-bf1e-4275-89d3-90241bfd1eef.png">

- [x] There should be required field backend validations for these fields, and error messages should be displayed correctly. 

- [x] If a user wishes to edit the email, he/she can do it in the editor. Clicking on confirm would move the application to the team interaction round, and send the email address as well

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
