### ISSUE TITLE
Add the efforts in the project tab on dashboard

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2182]
**Is your feature request related to a problem? Please describe.**
- In the dashboard, we just show the list of projects of the particular user
<img width="354" alt="Screenshot 2022-08-12 at 11 59 33 AM" src="https://user-images.githubusercontent.com/73119570/184297692-3275f85b-7ac0-4c2b-9374-13d104c02203.png">

**Describe the solution you'd like**
- Make it a table structure and show the individual person's hour and the team's effort in the project dashboard section.

**Comment by deepankar-sajwan** [comment]
closing as feature has been implemented
