### ISSUE TITLE
Sort by book categories 

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2185]
**Describe the task**
Right now if a user wants to see the books by category is not possible. 
<img width="1440" alt="Screenshot 2022-08-12 at 1 29 48 PM" src="https://user-images.githubusercontent.com/73119570/184311962-b544afa1-e91d-48da-94ae-7f360c4ed43a.png">

**Expected behaviour**
- We can add a dropdown field with all the categories. Show the books from selected categories.

**Comment by deepankar-sajwan** [comment]
closing as task is implemented 
<img width="885" alt="image" src="https://github.com/ColoredCow/portal/assets/96309135/e8a46a68-abb3-46c5-b429-6891e5512909">
