### ISSUE TITLE
Delete the prospect

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2190]
**Describe the task**
There is no way to delete the prospect from the system. Create functionality to delete the prospect and his details stored in DB
<img width="1273" alt="Screenshot 2022-08-12 at 7 58 05 PM" src="https://user-images.githubusercontent.com/73119570/184376569-44f3e042-6d5b-4871-9815-b30a19a64e54.png">

**Screenshots**
<img width="640" alt="Screenshot 2022-08-12 at 7 59 56 PM" src="https://user-images.githubusercontent.com/73119570/184376522-a66070b2-2e2e-4202-889f-ad442a7d5b85.png">
<img width="457" alt="Screenshot 2022-08-12 at 8 03 36 PM" src="https://user-images.githubusercontent.com/73119570/184376848-846b297e-0852-4b61-9d2a-d9274b5c9be7.png">

**References**
- If needed an example see how the deletion of an invoice works

**Comment by deepakbarmola** [comment]
Closing the issue as associated PRs are approved and merged.
