### ISSUE TITLE
Delete button on the Manage Evaluation

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2191]
**Describe the bug**
- When you visit the `Manage Evaluation->HR tabs` the delete button is not working. 
<img width="1440" alt="Screenshot 2022-08-13 at 1 12 36 PM" src="https://user-images.githubusercontent.com/73119570/184474423-38bbb47b-6b11-4f5d-86c8-6a34f89115df.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to **HR**
2. Click on 'Manage Evaluation'
3. Delete any row in the table
4. It won't be deleted. 

**Expected behaviour**
When the delete button is clicked, we need to delete the data from DB.

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
