### ISSUE TITLE
Text changes in applications report page

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2193]
**Describe the task**
- The naming on the reports page is not aligned perfectly. 
<img width="1277" alt="Screenshot 2022-08-13 at 2 34 46 PM" src="https://user-images.githubusercontent.com/73119570/184477068-2124435f-28a5-426d-8f7b-b6e8798475f7.png">

**Expected behaviour**
- Move the `Total Verified Applications:0` below to a new line. 
<img width="1272" alt="Screenshot 2022-08-13 at 2 36 41 PM" src="https://user-images.githubusercontent.com/73119570/184477104-495734a5-9c88-4a99-a6f4-5afcacc231e8.png">

**References**

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
