### ISSUE TITLE
Filtered date is not visible on the chart

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2197]
**Describe the bug**
The filtered date is not visible on the `Applications Per Jobs Roles` chart

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `HR->Recruitment->Report->JobWiseApplicatonReport`
2. Enter the date on the filters on the right side. 
3. You won't able to see the data on the filters. 

**Expected behaviour**
- The selected date should appear in the filter

**Screenshots**
<img width="1280" alt="Screenshot 2022-08-13 at 4 34 22 PM" src="https://user-images.githubusercontent.com/73119570/184483873-c344a3be-b711-49bd-95a9-7510549a58d0.png">
<img width="639" alt="Screenshot 2022-08-13 at 4 34 33 PM" src="https://user-images.githubusercontent.com/73119570/184484022-66934edd-ff7f-49f8-8dd7-88deaf07580e.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
