### ISSUE TITLE
The chart filtered start date should not be greater than the end date.

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2198]
**Describe the bug**
- When the date filter is selected the start date should not be greater than the end date.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `HR->Recruitment->Report->JobWiseApplicatonReport`
2. Enter the date on the filter's start date should be greater than the end date. 
3. See the chart

**Expected behaviour**
- The error message should appear like this
<img width="1275" alt="Screenshot 2022-08-13 at 4 52 19 PM" src="https://user-images.githubusercontent.com/73119570/184485984-627ad813-5c04-4068-bc2f-5ecb2dead1c3.png">

**Screenshots**
<img width="1279" alt="Screenshot 2022-08-13 at 4 48 30 PM" src="https://user-images.githubusercontent.com/73119570/184485274-6a41f5f6-c84f-489e-9181-d9d553836fa8.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
