### ISSUE TITLE
The dropdown is not appearing properly in the prospect page

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2200]
**Describe the bug**
- The nav dropdown is not appearing properly on the `Sales->Proespect` page.
<img width="637" alt="Screenshot 2022-08-13 at 5 26 08 PM" src="https://user-images.githubusercontent.com/73119570/184493760-37efa4f5-6e74-40e4-90ff-41567a81a2e4.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `Sales->Proespect`
2. Click on `Sales dropdown`
3. See the dropdown is behind the table

**Expected behaviour**
The dropdown should appear on top of the table
<img width="1274" alt="Screenshot 2022-08-13 at 5 52 25 PM" src="https://user-images.githubusercontent.com/73119570/184493886-f05f702e-1072-43bf-92fe-888c245c831f.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
