### ISSUE TITLE
Replace the pagination from the project page.

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2207]
**Describe the task**
- The pagination should be removed from the `CRM->Projects` and the lazy loading should be implemented in place of that.  
<img width="1440" alt="Screenshot 2022-08-15 at 4 21 26 PM" src="https://user-images.githubusercontent.com/73119570/184622898-cb08551f-18a1-4072-8ae2-c946a0875678.png">

**Expected behaviour**
- The pagination should be removed from the `CRM->Project` page.

**Comment by rathorevaibhav** [comment]
Not needed. Closing.
