### ISSUE TITLE
No Contract label UI change

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2214]
**Describe the task**
The `No Contract` button on the `CRM->Project` page doesn't look good. We need to make the button UI friendly to the user. 
This is how it looks
<img width="1440" alt="Screenshot 2022-08-16 at 12 53 42 PM" src="https://user-images.githubusercontent.com/73119570/184822257-9c7d4960-02b1-4b71-bfbd-5545af56dc26.png">
 

**Expected behaviour**
Can we change the label to something like in the below screenshot
<img width="1440" alt="Screenshot 2022-08-16 at 12 54 51 PM" src="https://user-images.githubusercontent.com/73119570/184822425-afc5d57c-7b32-4598-8074-0c79888ed9e8.png">

**Comment by deepankar-sajwan** [comment]
Closing as No contract label is updated
