### ISSUE TITLE
show team members Total efforts in Projects.

### ISSUE THREAD

**Issue by Abhinegi2** [ColoredCow/portal#2216]
**Describe the task**
We need to show team members daily , weekly, monthly  Total expected efforts in hours for projects .

**Expected behavior**
![total](https://user-images.githubusercontent.com/108608673/184860921-04831b86-ab1a-4e99-8547-37018c75c8e9.png)

**References**
Specify any reference material / links

**Comment by rathorevaibhav** [comment]
This is done. Closing.
