### ISSUE TITLE
Basic structure to store media on the Portal

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2233]
**Is your feature request related to a problem? Please describe.**
We are clicking a lot of photos these days. All of us do, but when we need photos for any poster, post or another purpose, it is always difficult to find them. So many good images are lost.

**Describe the solution you'd like**
- [x] Create a new module in the portal called `Media`
- [x] Add a page for it 
- [x] Create a CRUD controller 
- [x] Create Required Tables from this [document ](https://docs.google.com/presentation/d/1VB98HauQHnz0Oaz23WsCyV4tIq4yqv0zeNpnPy5h4pI/edit#slide=id.g144f70f4d61_0_0) using mirgatons 
- [x] Add some sample photos in the local storage and create seeders for the initial data
- [x] Add an upload photo button and on click add a modal to collect the required details mentioned in the schema.
- [x] Store all the details in the Database

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
