### ISSUE TITLE
Wishlist the books from the individual book page

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2235]
**Is your feature request related to a problem? Please describe.**
- There is no way for a user to wishlist the book from the book library or the individual book page
<img width="1440" alt="Screenshot 2022-08-18 at 10 28 29 AM" src="https://user-images.githubusercontent.com/73119570/185315515-f42e4698-e6ef-475f-8183-71597fa0ec7a.png">

**Describe the solution you'd like**

- [ ] Can we add a button to wishlist the book and the book should mark as wish listed book by a label 
- [ ] Also can we use the same button to remove from the wishlist 

Can we add the button here? 
<img width="1440" alt="Screenshot 2022-08-18 at 10 28 46 AM" src="https://user-images.githubusercontent.com/73119570/185317658-6b5caca6-094b-4f93-9df9-09251023b75a.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
