### ISSUE TITLE
The UI is not working properly on the P&L page

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2237]
**Describe the bug**
- Each time the user has to scroll the page left and right to see the content. Can we make this user friendly 
<img width="1440" alt="Screenshot 2022-08-18 at 11 59 04 AM" src="https://user-images.githubusercontent.com/73119570/185341471-c0439c75-ff96-46f2-96eb-fbaa19f648e1.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `Finance->P&L report`

**Expected behaviour**
Make the table fit the screen

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
