### ISSUE TITLE
View the wish listed books 

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2238]
**Is your feature request related to a problem? Please describe.**
- There is no way for a user to see all his wish-listed books on the `Books page`. 
<img width="1440" alt="Screenshot 2022-08-18 at 1 07 22 PM" src="https://user-images.githubusercontent.com/73119570/185342270-f44f8ced-782f-486b-9e2d-16c9a38c995d.png">

**Describe the solution you'd like**
- Can we add a button to show all the wish-listed books on the books page 
<img width="1440" alt="Screenshot 2022-08-18 at 1 07 13 PM" src="https://user-images.githubusercontent.com/73119570/185342393-d9768323-23a2-4e62-98dc-c2f32f72c3aa.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
