### ISSUE TITLE
Part 1: Freeze Functionality on project team member

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2245]
**Is your feature request related to a problem? Please describe.**
- Right now, the hours on the calculation of the team member in the project is not working as expected. 
<img width="1440" alt="Screenshot 2022-08-19 at 12 20 30 PM" src="https://user-images.githubusercontent.com/73119570/185560982-4a37cc45-b610-4382-8830-c9a5443a2fe6.png">

**Describe the solution you'd like**
- We need to add a freeze functionality for each team member for each project. 
<img width="1440" alt="Screenshot 2022-08-19 at 12 20 16 PM" src="https://user-images.githubusercontent.com/73119570/185561114-6e755dc6-8de8-4a84-91b7-f651210d9472.png">

**Break Downs**

- [x] Create a freeze column in the database
- [x] Make a dropdown in the project edit page
- [x] Collect the value in controller.
- [x] Store the required value in the database

**Comment by rathorevaibhav** [comment]
Not needed anymore.
