### ISSUE TITLE
Delete functionality for sales & Marketing Reports 

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2249]
**Is your feature request related to a problem? Please describe.**
There to delete the report from the `Sales->Report` Reports page 
<img width="1440" alt="Screenshot 2022-08-19 at 3 13 05 PM" src="https://user-images.githubusercontent.com/73119570/185592366-4c3d2ac0-57a3-45c5-968b-63cbadec8429.png">

**Describe the solution you'd like**
- Can we add a delete functionality for each sales report 
<img width="1440" alt="Screenshot 2022-08-19 at 3 18 22 PM" src="https://user-images.githubusercontent.com/73119570/185593020-812d182b-e0c2-43ce-94ec-2e3b2e4d7ade.png">

**Comment by deepankar-sajwan** [comment]
closing task as it has been implemented
<img width="1269" alt="image" src="https://github.com/ColoredCow/portal/assets/96309135/6443c506-2035-47ab-87a0-6a8d01929f69">
