### ISSUE TITLE
FTE alert, resource recommendation and job requisition

### ISSUE THREAD

**Issue by junaid1010** [ColoredCow/portal#2250]
**Overall description** 
- In the employees section under the HR module.
- There is an employees table which delivers some information about the employees as shown below.
- But initially, there is not any option to individually manage the workload of the employees based on their FTE.

![Capture](https://user-images.githubusercontent.com/58073430/185625327-0ec273ca-7aff-464b-9365-c35cb802ca6f.JPG)

**Description About the feature to be added.**
- The current FTE column shows the calculated value of actual_effort & total_effort_in_effortsheet, which overall represents the workload on an employee.
- If the current FTE value is more than 1 then there should be an alert icon displayed beside it & on clicking it a page should open up, having majorly 2 sections.

1. **Recommendations** -> It will recommend employees from the same domain who are having current FTE of less than 0.7
2. **Add Requisition Button** -> it will show the job requisition form 

- submit the job requisition form through ajax call. 

- make a job requisition table that contains the following columns 

1. id
2. domain_id
4. job_opportunity_id
5. Status->pending bydefault

- make a new column name **Resource Requisitions** in the HR dropdown list.

- Clicking on the **Resource Requisition** page should appear having two tabs.
- **Pending** and **Completed**

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
