### ISSUE TITLE
Project Contract Module Scaffolding

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2252]
**Is your feature request related to a problem? Please describe.**
- We need a place to store all the project contracts of the upcoming client. Also, we need a place to see the contract of the clients

**Describe the solution you'd like**
- [x] Create a new module in the portal called `Project Contract` Under CRM. 
- [x] Add a page for it 
- [x] Create a CRUD controller 
- [x] Create Required Tables from this [document ](https://docs.google.com/presentation/d/1FbiGJruKhzu6FCMU-lsiN1kBoEjyjPoG4kSWbfHqYC0/edit?usp=sharing) using migrations.  
- [x] Add a form to collect the values from the input field with validation

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
