### ISSUE TITLE
Edit the authors review

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2260]
**Describe the bug**
- The user is unable to edit their thoughts shared in the books.  
<img width="1381" alt="Screenshot 2022-08-21 at 11 57 05 PM" src="https://user-images.githubusercontent.com/73119570/185805707-62e9a008-f9da-4173-96af-c50ef7b27390.png">
<img width="1440" alt="Screenshot 2022-08-21 at 11 57 28 PM" src="https://user-images.githubusercontent.com/73119570/185805717-4fa58190-c482-4209-b353-1e1f9e047df2.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `Books`
2. Click on any book
3. Leave a review 
4. Edit the review the review won't be available 

**Expected behaviour**
- The user must be able to see the review which he shared.

**Comment by deepakbarmola** [comment]
Closing the issue as linked PR is approved and merged.
