### ISSUE TITLE
Part 2: Freeze Functionality on project team member

### ISSUE THREAD

**Issue by Himanshunegi0332** [ColoredCow/portal#2265]
**Reference**
- #2245 

**Is your feature request related to a problem? Please describe.**
- Right now, the hours on the calculation of the team member in the project is not working as expected.

**Describe the solution you'd like**
- As added the freeze column and saved it in the database, now in this part the freeze functionality should work according to the selected freeze column or function. 
- In this, there are 3 options, daily, weekly, and monthly efforts. 
- If we click on any one of these columns its respective field should freeze and it should be freezed for the next month also and calculate its efforts according to the column freezed. 
![Screenshot (54)](https://user-images.githubusercontent.com/108523408/186353084-6d91f401-e084-42c7-9644-2403e475273e.png)

**Describe alternatives you've considered**
- If we freeze daily efforts(e.g. 8) for this month then, for the next month its daily efforts should be 8 only and according to no. of working days, its weekly and monthly efforts should be calculated. 
- Same should happen for the weekly and monthly efforts if we freeze any of them.

**Comment by Abhinegi2** [comment]
updates->
1-we need to create two new columns in database Weekly Effort and Monthly Effort in Database table.
2-After that we need to save those values in DB.
3- If we click on any one of Freeze columns its respective field should freeze and it should be freezed for the next month also and calculate its efforts according to the column freezed.
4- we need to add permissions for that Freeze functionality.

**Comment by rathorevaibhav** [comment]
Not required right now. We will revisit later.
