### ISSUE TITLE
Centre align the sales automation text

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2285]
**Describe the bug**
The Sales Automation text is not centre-aligned and it looks odd. Can we centre-align the text `Sales Automation` Text?
<img width="1440" alt="Screenshot 2022-08-25 at 7 02 31 PM" src="https://user-images.githubusercontent.com/73119570/186685082-fd092e9d-d7e1-4dea-a0b1-abf06d31ecc6.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `Sales->Sales Automation`
2. See the leading on the left side

**Expected behaviour**
Make the Sales Automation in the centre
<img width="1440" alt="Screenshot 2022-08-25 at 7 40 40 PM" src="https://user-images.githubusercontent.com/73119570/186688000-7f5c00fa-ce28-4abb-9ac8-0ba3a8cd284a.png">

**Comment by Ayush8923** [comment]
Working Fine.
