### ISSUE TITLE
Add a ability to add more revenue category in the system. 

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#2301]
Is your feature request related to a problem? Please describe.
Currently, the only revenue item in the portal which invoices but we have some more ways also to get the revenue like Interset on FD, Commission as ISV, Cashback, and so on.
So we need a way to store that information in the system.

Describe the solution you'd like
To start with we can go very simply simple approach. Just add a form on the finance page which will list all the other revenues.
The form can consist of the following columns.

1. Name
2. Category
3. Date of Received
4. Currency
5. Notes

We can also list these revenue items on the finance list with all the other ops actions like edit and delete.
We will not allow users to delete /edit the expense if it's in the system for more than 10 days.

**Comment by Abhishek25081999** [comment]
**Describe the solution you'd like**
- [ ]  Add a form on the finance page which will add all the other revenues. 
- [ ] Create table in database and collect data from the new form.
- [ ] Show the added revenue in a table.
- [ ] Make every row of table editable and removable.
- [ ] Don't allow users to delete /edit the expense if it's in the system for more than 10 days

**Comment by gautam071** [comment]
@Abhishek25081999 Can you create a schema for the database as well and share it here

**Comment by Abhishek25081999** [comment]
[https://docs.google.com/presentation/d/1wTlZKyNNnosngHB4z1leIJqYIcyskYZN7Tm8ywjJn8A/edit?usp=sharing](url)

**Comment by Abhishek25081999** [comment]
[Database schema for the revenue table.pptx](https://github.com/ColoredCow/portal/files/9477171/Database.schema.for.the.revenue.table.pptx)

**Comment by pankaj-ag** [comment]
We need to add amount also. Please add that.

**Comment by Abhishek25081999** [comment]
@pankaj-ag Okay!

**Comment by Abhishek25081999** [comment]
@pankaj-ag have a look on it. https://docs.google.com/presentation/d/1wTlZKyNNnosngHB4z1leIJqYIcyskYZN7Tm8ywjJn8A/edit?usp=sharing

**Comment by pankaj-ag** [comment]
Amount and currency will be required fields. Let's change this and then we are good to go.

**Comment by Abhishek25081999** [comment]
@pankaj-ag sure!
