### ISSUE TITLE
Send an email to the Project key manager if the project is a fixed budget and its empty

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2315]
**Is your feature request related to a problem? Please describe.**
- An email should be triggered to the key account manager saying your project is not having an end date. 

**Condition**

<img width="1438" alt="Screenshot 2022-08-30 at 4 40 05 PM" src="https://user-images.githubusercontent.com/73119570/187422235-7c3cdcda-7351-4962-8d0a-709bb92c1926.png">

**Describe the solution you'd like**

- [ ] Create a query to get all the project which are `Fixed budget` and doesn't have `End date`. 
- [ ] Get the Key account manager's Email address using the User's table. 
- [ ] Write a functionality to trigger email
- [ ] Email content (Will be shared shortly).

**Comment by Ayush8923** [comment]
@Anshgupta456 If the project is on a fixed budget and has no end date, I am sharing its mail template.

```
Hi, KeyAccountManager

There are some fixed-budget projects which are not having any project end-date where you are assigned as a key account manager, please update these projects:

  	Project Name

1.	ProjectName (Link)
2.	ProjectName (Link)

Thanks,
Portal Team
ColoredCow

```
