### ISSUE TITLE
Trigger an email to the key account manager that end date is nearing up in the project. 

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2321]
**Is your feature request related to a problem? Please describe.**
- A Email should be triggered before 5 days saying that the end date of the particular project is nearing 
<img width="1438" alt="Screenshot 2022-08-30 at 4 40 05 PM" src="https://user-images.githubusercontent.com/73119570/187603841-98672fc0-3069-4f65-9b94-15bbf434aa46.png">

**Describe the solution you'd like**
- [x]  Create a query to get all the project which are Fixed budget and doesn't have End date.
- [x]  Get the Key account manager's Email address using the User's table.
- [x]  Write a functionality to trigger email
- [x]  Email content (Will be shared shortly).

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
