### ISSUE TITLE
Show all the borrowed books in the portal

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2337]
**Is your feature request related to a problem? Please describe.**
- There is no way to see all the borrowed books in the portal
<img width="1440" alt="Screenshot 2022-09-02 at 12 19 01 PM" src="https://user-images.githubusercontent.com/73119570/188076083-56ad1a02-6dc1-41a7-84a5-5f7917e555f3.png">

**Describe the solution you'd like**
- Create a new tab called `Borrowed Books` and once a user clicks on it show all the borrowed books
<img width="1440" alt="Screenshot 2022-09-02 at 12 18 55 PM" src="https://user-images.githubusercontent.com/73119570/188076226-55adf687-c8e8-4077-98e7-9319c49332bf.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
