### ISSUE TITLE
Add an option to filter the books by category

### ISSUE THREAD

**Issue by mdshamoon** [ColoredCow/portal#2338]
**Is your feature request related to a problem? Please describe.**
We have books with various categories defined and I want to filter the books by a category. Right now we have no option to do that.

**Describe the solution you'd like**
Add a filter option just besides the search box to filter the books by category. Filter category and search should work together as well.

The filter option should be a multiselect that gives user the option to select multiple categories at once.

![image](https://user-images.githubusercontent.com/32592458/188083465-3b5131a2-a81f-43f5-a9ac-3c4302968668.png)

**Comment by LavishRawat** [comment]
Closing the issue as it is completed.
