### ISSUE TITLE
Add loading spinner until the books will not appear

### ISSUE THREAD

**Issue by Shivam-Samant** [ColoredCow/portal#2341]
**Describe the task**
1. Go to KnowledgeCafe -> Library.
2. When the books are not loading completely it looks like the below screenshot.

![Screenshot (358)](https://user-images.githubusercontent.com/91321534/188110129-3fdb7962-d949-4c9f-9662-5288f32d3edd.jpg)

**Expected behavior**

1. Remove the above screenshot data.
2. Make a loading spinner in the center of the page.
3. That loading spinner showed on the page until the books are not shown.

**References**
Bootstrap spinner: https://getbootstrap.com/docs/4.2/components/spinners/

**Comment by deepankar-sajwan** [comment]
The feature has been implemented the loader is available at centre of screen until books are not loaded
