### ISSUE TITLE
Manage evaluation add new segment button UI 

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2345]
**Describe the task**
Change the add new segment button similar to `add new book` button

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/35001775/188137823-bc85c3ac-43c0-40e9-9697-6b92f9fc3e5c.png">

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/35001775/188137779-9aa61fa6-ec46-42f6-ae52-8489e351b56c.png">

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
