### ISSUE TITLE
We need to convert the New Sales Area page to bootstrap modal form.

### ISSUE THREAD

**Issue by Ayush8923** [ColoredCow/portal#2356]
**Describe the task**
- Go to Sales -->  Sales Automation -> Sales Area
- When you click on the `New Sales Area` button of any sales area a new page opens. Which sometimes takes time.
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/54376313/230958505-74fa4ffb-aafa-4905-900d-6624324d774a.png">

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/80516839/230953325-cbb7fb08-066e-47bb-9ad5-b980e99e0485.png">

**Expected behavior**
- We need to convert this  `New Sales Area` page to bootstrap modal form. 
- When we click on the  `New Sales Area` button of a sales area, the modal should be open and it should contain all the input fields of the sales area edit form. Like it is in edit sales area page right now. As edit segment modal form is created.  As shown in the image below.

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/80516839/230954195-51860d07-3c6f-45a7-a291-f6be30405fad.png">

**References**
Bootstrap model:- https://getbootstrap.com/docs/4.0/components/modal/

**Comment by GauravGusain98** [comment]
@Ayush8923 Can you also mention how the page should look like. If you convert the fields into modal then I guess only 4 options will remain in the page which will not look good.

**Comment by Ayush8923** [comment]
@GauravGusain98 

**Current Behaviour**
- Now if there is no data in the sales area then it just shows an empty table. as shown in the below screenshot
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80516839/230956349-bd3f2458-1329-4acc-8bbb-8a67ea7459ca.png">

**Expected Behaviour**
- Now if there are no sales added in the sales area then instead of showing an empty table now need to do something like this as shown below screenshot.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80516839/230956199-794fa308-021f-4424-87e9-7d05dd54cff1.png">

- We can use this image. to show `No Data Found`.
![image](https://user-images.githubusercontent.com/80516839/230957309-1e9dca9e-7941-40a4-9e88-fd0b46c8a4ab.png)

**Comment by Ayush8923** [comment]
@GauravGusain98 

**Current Behaviour**
- Now if there is no data in the sales area then it just shows an empty table. as shown in the below screenshot
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80516839/230956349-bd3f2458-1329-4acc-8bbb-8a67ea7459ca.png">

**Expected Behaviour**
- Now if there are no sales added in the sales area then instead of showing an empty table now need to do something like this as shown below screenshot.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80516839/230956199-794fa308-021f-4424-87e9-7d05dd54cff1.png">

- We can use this image. to show `No Data Found.
![image](https://user-images.githubusercontent.com/80516839/230957309-1e9dca9e-7941-40a4-9e88-fd0b46c8a4ab.png)

**Comment by Priyanka-Kaintura** [comment]
Task Breakdownn: 
- [ ] Reading on Bootstrap modal - 1 hr
- [ ] Adding image - 10 min
- [ ] Connverting new sales area page to bootstrap modal- 1.5 hr

**Comment by Priyanka-Kaintura** [comment]
@Ayush8923 Sir, I'm unable to insert the image while everything else works. Is there something I'm missing about placing images with this project? Also I wanted to ask where should the image be saved in the project.

This is how it comes out. 
![image](https://user-images.githubusercontent.com/112419110/235321395-b994b6ff-2003-4ef2-a9c5-86ce2b722df0.png)

**Comment by Ayush8923** [comment]
> @Ayush8923 Sir, I'm unable to insert the image while everything else works. Is there something I'm missing about placing images with this project? Also I wanted to ask where should the image be saved in the project.
> 
> This is how it comes out. ![image](https://user-images.githubusercontent.com/112419110/235321395-b994b6ff-2003-4ef2-a9c5-86ce2b722df0.png)

@Priyanka-Kaintura You need to save the image in this path `public/images/coloredcow.png`. 
Then you can use it like this.
```
<img src="{{ public_path() . '/images/image-name' }}" alt="">
```

Please let me know If there are any other questions.

**Comment by Priyanka-Kaintura** [comment]
@Ayush8923 Sir, it still doesn't work. 
![image](https://user-images.githubusercontent.com/112419110/235431110-1f0cea0f-da9a-4d44-9a73-c4b53aa2d153.png)
