### ISSUE TITLE
Team interaction round applications shouldn't be marked for followup

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2359]
**Describe the task**
Currently, the applications sent into Team Interaction Round, are marked as `Need Followup` in the front end after 2 days. You will find it in the codebase, we have a scheduler that marks the applications for `need follow up`. We would like to avoid this when moving an application into Team Interaction Round.

Steps to replicate:
1. Send any application into Team Interaction Round
2. Adjust the dates of your system for 3-4 days later
3. Run the `need follow up` scheduler using the artisan command, you will find this in the codebase

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
