### ISSUE TITLE
Trigger an email to the team member if the expected hours is zero

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2375]
**Is your feature request related to a problem? Please describe.**
- A Email should be triggered if the particular employee if the expected hours are zero
<img width="1440" alt="Screenshot 2022-09-06 at 2 58 23 PM" src="https://user-images.githubusercontent.com/73119570/188600130-ed15f6ca-750a-40da-a0c2-ecdccb9bdeee.png">

**Describe the solution you'd like**
- [x]  Create a query to get all the project which has zero expected hours.  
- [x]  Get the project team member's Email address using the User's table.
- [x]  Write functionality to trigger email
- [x]  Email content (Will be shared shortly).
- [x] Create a cron job to send this email every Tuesday 11.00 AM

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
