### ISSUE TITLE
Total count of Employee

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2385]
**Describe the task**
On the employee page, we would like to have a total count of Employees. The count can go in brackets adjacent to the Employees heading. By default the count should show current employees, if `previous` is selected, the count of the previous employees should be displayed in that bracket
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/35001775/188842813-309893e3-675b-4a5b-b1e3-ce17efdee832.png">

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
