### ISSUE TITLE
Change the text of the button on sales report page

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2416]
**Describe the bug**
- Change the text of the button in the sales and marketing report. 
<img width="1440" alt="Screenshot 2022-09-13 at 10 27 59 AM" src="https://user-images.githubusercontent.com/73119570/189813057-6e44eee2-fd20-43bb-8305-3c66f87e600f.png">
 

**To Reproduce**
1. Go to `Sales-> Report`
2. Change from `Add report` to `+ Add New Report`
**Note: The plus symbol should be an icon**

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
