### ISSUE TITLE
Change the text in the button on universities

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2417]
**Describe the bug**
- The button text should be replaced on the button on the universities page. 
<img width="1440" alt="Screenshot 2022-09-13 at 11 28 39 AM" src="https://user-images.githubusercontent.com/73119570/189831471-4ff5219c-4f9c-4e83-8fed-2b3ae4c97815.png"> 

**To Reproduce**
1. Go to `HR-> Universities`
2. Change from `Add University` to `+ Add New University`
**Note: The plus symbol should be an icon**

**Comment by P4NK4J** [comment]
@gautam071 Do you think we are adding multiple universities with a single button ? I think the button text should be `Add new university`, let me know what you think

**Comment by gautam071** [comment]
@P4NK4J My bad, updated the issue accordingly

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
