### ISSUE TITLE
Correct Functionality of Applications- Round Wise Filter

### ISSUE THREAD

**Issue by Abhinegi2** [ColoredCow/portal#2418]
**Describe the task**
Currently when we Apply filter on  Assignee its  working.
![image](https://user-images.githubusercontent.com/108608673/189836240-f4a8f437-c487-4479-be99-d05b9efac40e.png)

And now if we apply Round wise filter .
![image](https://user-images.githubusercontent.com/108608673/189836639-20c386e2-2162-4bce-ae55-0858167ed471.png)

Round wise filter removes Assignee Filter and shows all Applications According to round wise filter.
![image](https://user-images.githubusercontent.com/108608673/189836966-bac69491-60aa-4ed3-9922-d7cbc80acca5.png)

**Expected Behavior**
 Round wise filter should work properly if there is any filter is  already working.

**Comment by LavishRawat** [comment]
This issue is completed. Closing it.
