### ISSUE TITLE
Basic details in employee page

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2431]
**Describe the task**
currently, we have options to add basic details of an employee in My profile section, we want this to be applicable to Hr Employees section as well. 
Put the details, and provide a functionality to edit the same, like its happening in my profile section. Form submission and validation should be through ajax

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/35001775/189958970-589fb4e4-3b6c-4e32-aca6-f27d23552fdd.png">
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/35001775/189959101-743ba87c-6801-47e3-a56a-6d3a90584f52.png">

**Comment by LAKSHYA0501** [comment]
Sharing the breakdown and approach

- [x] In Hr Employee's basic details section we want the same interface as present in the basic details under My Profile functionality.
- [ ] We can use the same as it already exists.
- [x] The working and functionality of the `EDIT` button should also be the same as in the My Profile functionality.
- [ ] Check whether on editing the data is updated properly or not.
- [ ]  In the edit dialog box the submission and validation of the form should be done through ajax call.
