### ISSUE TITLE
Change the text from Library to Books

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2449]
**Is your feature request related to a problem? Please describe.**
In the portal, we have many places where we have written books and in some places the library. 
<img width="1440" alt="Screenshot 2022-09-15 at 11 52 28 AM" src="https://user-images.githubusercontent.com/73119570/190329963-cb79fd5e-3ae5-4123-b34e-9f37acbbe1ce.png">

**Describe the solution you'd like**
Let's make it consistent by changing the `Library` to `Books`

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
