### ISSUE TITLE
Not able to edit the Project details 

### ISSUE THREAD

**Issue by dhruvshrinet1** [ColoredCow/portal#2452]
Getting 'Project_type' not defined 
![image](https://user-images.githubusercontent.com/46843563/190337642-2558bfa7-4a2a-487a-96fe-587a7ebf389f.png)

Steps to replicate:
1. CRM->Projects->Select any project 
2. Click on Edit Button at Top right corner
3. Make changes 
4. Click on Save

**Comment by LAKSHYA0501** [comment]
@dhruvshrinet1 take the latest pull and also sync the changes in your branch as well, also update your master at every release
