### ISSUE TITLE
Segregate the employees by roles 

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2461]
**Is your feature request related to a problem? Please describe.**
- Right now, all of the employees are displayed on the employee page
<img width="1440" alt="Screenshot 2022-09-15 at 2 16 54 PM" src="https://user-images.githubusercontent.com/73119570/190358989-bcb760fa-8cf6-43a7-8400-e0c97ca02160.png">

**Describe the solution you'd like**
- Separate the employees into the following Roles **Employees, interns, contractors, and support staff**

**Things to do**
- [ ] Add the individual tabs for **Employees, Interns, Contractors, and Support Staff**. These tabs can be placed next to Employee blue tab. Also, add the icons in the tabs
- [ ] Add two new roles in the system, Contractors and Support Staff 
- [ ] Each employee will have these roles assigned by User Management
- [ ]  On Click of the tabs displays the employees according to their roles.

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
