### ISSUE TITLE
Fix the UI of the yearly invoice report table

### ISSUE THREAD

**Issue by Shivam-Samant** [ColoredCow/portal#2469]
**Describe the task**
In the yearly invoice report table, the horizontal scroll bar is shown. So make the responsive UI.

<img width="950" alt="Screenshot 2022-09-16 110627" src="https://user-images.githubusercontent.com/91321534/190564772-8d5e03a6-2a83-4c5b-b5e5-ff42902203f9.png">

**Comment by deepankar-sajwan** [comment]
closing as issue is fixed
