### ISSUE TITLE
User profile meta options

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2478]
**Describe the task**
Currently on the user profile page, we have only available information listed, while there is no way to edit the user meta information. In the Edit profile popup, we would like to have all the fields from user_profile table to be populated. Upon successful edit form submission, the details should be visible on user profile
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/35001775/190859228-4d0c63da-d868-4a08-8f18-2978df05b351.png">
<img width="778" alt="image" src="https://user-images.githubusercontent.com/35001775/190859250-0af16c0b-e9bf-42df-b721-ccbd586d2f49.png">

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
