### ISSUE TITLE
Change the title from Wishlist books to Wish listed Books

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2490]
**Describe the bug**
Change the title of the section name from **Wishlist books** to **Wish listed Books**
<img width="1440" alt="Screenshot 2022-09-19 at 4 25 07 PM" src="https://user-images.githubusercontent.com/73119570/191005698-96adf484-759e-4505-9f18-50dc3cc8333f.png">

**To Reproduce**
1. Go to knowledge -> books

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
