### ISSUE TITLE
Change the text in the recommended section

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2497]
**Is your feature request related to a problem? Please describe.**
- In the Dashboard change the text from `Books recommended for you. COMING SOON` to `COMING SOON`.

<img width="1440" alt="Screenshot 2022-09-20 at 10 44 55 AM" src="https://user-images.githubusercontent.com/73119570/191173301-67b7b750-0f75-48e6-8d26-5f4e0f2ddcca.png">
<img width="1440" alt="Screenshot 2022-09-20 at 10 44 45 AM" src="https://user-images.githubusercontent.com/73119570/191173228-d5f1bd1b-6b03-453a-8604-0bb7d8270ddd.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
