### ISSUE TITLE
Create Designation section in HR dropdown

### ISSUE THREAD

**Issue by rohit123-rawat** [ColoredCow/portal#2511]
**Describe the task**
Currently, there is no way we can edit the designation so we need to add a designation section where we can create new designations.

**Comment by deepankar-sajwan** [comment]
Closing as feature is implemented
<img width="1056" alt="image" src="https://github.com/ColoredCow/portal/assets/96309135/b08432b5-4df9-4267-95c7-4392fe6df8f0">
