### ISSUE TITLE
Fix Error in the Universities Section.

### ISSUE THREAD

**Issue by LAKSHYA0501** [ColoredCow/portal#2520]
**Describe the task**

1. In the Universities listing page inside the HR module, there is a bug when we click on the `Add university` button,.
2. It is an undefined variable has been passed, is needed to be checked and fixed.
![image](https://user-images.githubusercontent.com/53862863/191725706-24a8adff-1e03-4006-934b-3deda71157f1.png)

3. Also remove the `Add university` button from each university edit page and just show it on the main listing page of the university.
![image](https://user-images.githubusercontent.com/53862863/191725805-19aecd36-5490-46d4-bf08-7538e6dfa585.png)

**Thing to do**
- [ ] Fix the `Add University` button.
- [ ] Also remove the `Add University` button from edit page.

**Comment by deepankar-sajwan** [comment]
closing as issue is fixed
<img width="1284" alt="image" src="https://github.com/ColoredCow/portal/assets/96309135/65fe53b0-7920-40ac-830d-94a74717e854">
