### ISSUE TITLE
Display the count of the borrowed books and wish-listed books

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2533]
**Is your feature request related to a problem? Please describe.**
- Display the count of books preset in the whitelisted and borrowed books 
<img width="1440" alt="Screenshot 2022-09-24 at 12 28 27 PM" src="https://user-images.githubusercontent.com/73119570/192084658-deafb486-40b3-4690-9b0b-9af2f0eb452c.png">

**Comment by deepankar-sajwan** [comment]
closing as task is complete
<img width="1101" alt="image" src="https://github.com/ColoredCow/portal/assets/96309135/1064dd7e-3641-4e8e-9013-6790e334ec98">
