### ISSUE TITLE
The wishlisted books is not working as expected

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2534]
**Describe the bug**
- When we select the whitelisted books all the books are displaying 
<img width="1437" alt="Screenshot 2022-09-24 at 12 28 15 PM" src="https://user-images.githubusercontent.com/73119570/192084738-f46e9f55-822d-4444-b6bf-4f8245e4622b.png">

**To Reproduce**
1. Go to `Knowlagecafe-> Books`
2. Click on `Whislisted`

**Expected behavior**
- Only the whislisted books should display

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
