### ISSUE TITLE
Project FTE UI enhancement

### ISSUE THREAD

**Issue by AkhileshNegi** [ColoredCow/portal#2537]
**Describe the bug**

**To Reproduce**
1. Go to Portal Home
2. Click on any of the Projects that are listed under `My projects`
3. Click on the `Check FTE` button
4. Click on the Year dropdown
5. There are two entries for the current year

**Expected behavior**
Each year in the dropdown should appear only once

**Screenshots**
<img width="581" alt="image" src="https://user-images.githubusercontent.com/40158831/192086493-dc880fb0-c1fa-4de4-bd1e-b522d46a44e9.png">

**Comment by deepankar-sajwan** [comment]
closing as issue is fixed
<img width="631" alt="image" src="https://github.com/ColoredCow/portal/assets/96309135/781e476a-65ea-476b-8d2e-7affd73ee567">
