### ISSUE TITLE
Add policies and enable the permission, and implement shareable link 

### ISSUE THREAD

**Issue by tarunnjoshi** [ColoredCow/portal#2553]
**Describe the task**
In CRM->project Contract We need to add create page and sharable link / Public link for the create page and also we need to add policies for it . 

1. Create new create page for clients where all the details of clients were shown. 

2. Make this create page as public page (Shareable URL) 
    so, anyone can access this Link when we send it to anyone.

3. Create new permissions for project contract .

4. Create a new Policy for Project contract.

**Reference**
https://laravel.com/docs/9.x/authorization

**Comment by rathorevaibhav** [comment]
Not needed anymore.
