### ISSUE TITLE
[Bug]  Incorrect velocity calculation for the project

### ISSUE THREAD

**Issue by AmishaBisht** [ColoredCow/portal#2556]
**Describe the bug**
The project's velocity is comes different in the project listing page and different in the project FTE page.

**Screenshot**
**Project Listing page: velocity=0.67**
<img width="824" alt="image" src="https://user-images.githubusercontent.com/54376313/202968201-899ff26d-8280-419b-8565-8bb44c015c11.png">
**Project FTE page: velocity=0.43**
<img width="540" alt="image" src="https://user-images.githubusercontent.com/54376313/202968285-10796f01-c6c8-48bc-a6df-4caa4c2dce91.png">

**Formula**
Velocity = Current hours in project / Total expected hours in the project till date

**Expected behavior**
Velocity should be the same on both pages.

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
