### ISSUE TITLE
Unflagging desired Resume and editing reason for flagging.

### ISSUE THREAD

**Issue by 11karangm** [ColoredCow/portal#2566]
**Describe the task**
Go to HR->Recruitment->go to the name column on the table that is displayed->click on the view button->Applicant Details->Click on Resume->click the flag button on the top right corner of the resume->Add the edit and delete button on the table that is shown.

**Expected behavior**
Add two buttons
**Edit button** : should allow the user to edit the reason for desiring the resume.
**Delete button** : should unflag the resume to undesired.

**Comment by 11karangm** [comment]
![resumepage2](https://user-images.githubusercontent.com/59615903/193402361-50206625-e8af-4489-aabf-c2ebe493f224.png)
![resumepage](https://user-images.githubusercontent.com/59615903/193402367-32e8bdd0-05aa-4c94-872f-eb71a6e04b95.png)

There is no button that redirects me to the table that contains all the desired resumes.
When I click on the resume I just get a tides link.

Please resolve this issue. So that I can start with my task.

**Comment by P4NK4J** [comment]
@11karangm This resume file is coming from ColoredCow website, so you can update the URL of resume in database to https://coloredcow.com/wp-content/uploads/2022/08/sample.pdf. This would open up the file.

**Comment by 11karangm** [comment]
Ok sir, What about the button or link that is supposed to take me to the page which displays all resumes in table format?

**Comment by P4NK4J** [comment]
> Ok sir, What about the button or link that is supposed to take me to the page which displays all resumes in table format?

That link will appear once a resume is flagged for the applications corresponding to a job role

**Comment by 11karangm** [comment]
![ResumeFlag](https://user-images.githubusercontent.com/59615903/193406973-7dcea73b-ab89-4ee7-ad7f-9f5f48eb2fb2.png)
Sir when I changed the resume file to 'Sample.pdf' the flag button dissapeared.

**Comment by P4NK4J** [comment]
How about npm run dev ? or. taking a latest pull from main branch

**Comment by 11karangm** [comment]
![FlagSuccessful](https://user-images.githubusercontent.com/59615903/193407564-2a8b6fed-b88d-4986-b53e-0065d53d9b7b.png)
Sir I successfully flaged, where shall I click to go to the page containing all flaged applications?
I tried clicking on 'resume', 'Application Evaluation', 'Reason for eligibilty' and 'pencil icon'.
