### ISSUE TITLE
The Nav bar is not showing up properly

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2567]
**Describe the bug**
- The navbar of sales is not showing up correctly in the UI 
<img width="1440" alt="Screenshot 2022-10-03 at 11 14 41 AM" src="https://user-images.githubusercontent.com/73119570/193509023-a3139e24-a6a0-449b-9b9f-a77f1f17d393.png">

**To Reproduce**
1. Go to 'CRM->Project Contracts'
2. Click on 'Sales in the navbar'

**Expected behavior**
It should be something like this 
<img width="1440" alt="Screenshot 2022-10-03 at 11 15 10 AM" src="https://user-images.githubusercontent.com/73119570/193509044-120ab25a-96d4-4846-9cc9-8574ad638e04.png">

**Comment by rathorevaibhav** [comment]
This seems fixed. Closing.
