### ISSUE TITLE
Change the text in search input field on books page 

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2574]
**Describe the bug**
- Change the text in the search in put field on the books page
<img width="1440" alt="Screenshot 2022-10-06 at 11 04 20 AM" src="https://user-images.githubusercontent.com/73119570/194223209-de813c63-409e-4461-894a-479da3dd140f.png">

**To Reproduce**
1. Go to `Knowledge Cafe->Books`

**Expected behavior**
Change the text to the following shown in the image
<img width="1439" alt="Screenshot 2022-10-06 at 11 04 04 AM" src="https://user-images.githubusercontent.com/73119570/194223338-73822388-430a-41e4-b0ac-809135dc912e.png">

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
