### ISSUE TITLE
Change the text on the button

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2581]
**Describe the bug**
- The button text should be replaced on the button on the Expense page
<img width="1440" alt="Screenshot 2022-10-10 at 12 17 46 PM" src="https://user-images.githubusercontent.com/73119570/194812132-e58e8bd5-2f98-4bea-a7ea-febb4f5d3be5.png">

**To Reproduce**
1. Go to `Finance-> Expense`
2. Change from `Add new Expense` to `+ Add New Expense`
**Note: The plus symbol should be an icon** 
For reference check other places in the portal

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
