### ISSUE TITLE
ColoredCow Working Staff 

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2603]
**Describe the task**
We would require refactoring the Employee page into the working directory, for which the following action items are needed.

- [ ] Rename the employee nav item to Working Staff
- [ ] Add a column in the `employees` table - `staff_type`, this can be a simple text field as of now (in the future, we can think whether we need an enum here or something else)
- [ ] Create a working staff type array in the config, this will have the following in the slug-title pair:
1. employee => Employee
2. intern => Intern
3. contractor => Contractor
4. support-staff => Support Staff

- [ ] On the user management page, 
1. Replace the remove user button with the delete icon
2. Create a new settings icon next to Remove user button, clicking on which a popup should appear, with title `Set user's type in working staff`. The popup should have a dropdown with a label `Working Staff Type`, and in the dropdown all the options created in config (in third step) should appear. Upon saving, the key of option should go in `staff_type` column in database.

- [ ] On the Working Staff page, update the listing based on the `staff_type` set in employee table. All the members should appear in the listing as per selected in the type. Rest of the columns would remain the same, designation, projects, FTE etc, the listing based on query would be updated.

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
