### ISSUE TITLE
The Nav bar is not showing up properly

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2620]
**Describe the bug**
- The navbar of sales is not showing up correctly in the UI 
<img width="1429" alt="Screenshot 2022-10-18 at 3 15 18 PM" src="https://user-images.githubusercontent.com/73119570/196397657-a4b1daf3-e1e2-4ac7-be5d-45ac2122f061.png">
<img width="1440" alt="Screenshot 2022-10-18 at 3 19 13 PM" src="https://user-images.githubusercontent.com/73119570/196397673-229739e5-9681-4257-a54e-f64c4913139c.png">

**To Reproduce**
1. Go to 'CRM->Project Contracts'
2. Click on 'Sales in the navbar'

**Expected behavior**
It should be something like this 
<img width="1440" alt="Screenshot 2022-10-03 at 11 15 10 AM" src="https://user-images.githubusercontent.com/73119570/193509044-120ab25a-96d4-4846-9cc9-8574ad638e04.png">

**Comment by rathorevaibhav** [comment]
This is fixed.
