### ISSUE TITLE
Align the edit button on the media module

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#2628]
**Describe the bug**
- Align the edit button according to the edit button.
<img width="1440" alt="Screenshot 2022-10-26 at 11 36 39 AM" src="https://user-images.githubusercontent.com/73119570/197947548-e2abc522-4706-4c3b-93fb-b2ffd95cb8fa.png">

**To Reproduce**
1. Go to 'Media'
2. Click on 'Click on any image'

**Expected behavior**
- The button height should be similar to the delete button

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
