### ISSUE TITLE
Reject Option in Resume Screening Evaluation Dialog

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2672]
Feature requested by 
@P4NK4J 

**The Goal**
Streamline application evaluation in the employee portal

**Is your feature request related to a problem? Please describe.**
At ColoredCow, we believe that talent is a myth, and given the right platform and exposure, we can create talent. Most of the fellows at ColoredCow are an outcome of the same philosophy. As we are on a growth journey, to achieve scale, we would require talents at all levels. For candidates to join us via the outbound method, we have the job openings listed on our [website](https://coloredcow.com/career/). 
Whenever a person applies for a particular job, we use employee portal to execute the lifecycle of the application. Once it is received into the system, the first step is to evaluate their CV/Resume. The resume helps us to know the candidate better, including:
1. Past project experience, the ecosystem in which they worked
2. Native place
3. Skillset matching out requirements etc.

To evaluate these pointers, we have a system in place, where a resume is evaluated on the basis of several questions. In the current system, If a resume is not relevant, the HR team has to circle back on the details, for taking a `Reject` action. Having the reject option placed during evaluation would help in an efficient evaluation. 

**Describe the solution you'd like**

- [ ] Once we click the `Application Evaluation` button, a dialog box appears, sharing the screenshot below for reference. If HR team selects `No` for the first question, instead of next button, we need the functionality to reject the application, similar to what we have on the application details page. 

Application Evaluation button

<img width="754" alt="image" src="https://user-images.githubusercontent.com/35001775/205021220-f18721d1-d235-4530-93f5-41fd58868bc6.png">

Evaluation dialog box

<img width="836" alt="image" src="https://user-images.githubusercontent.com/35001775/205021270-7a3ee456-9217-469f-8a64-83fad0347edf.png">

If `No` is selected, instead of the Next button, the Reject option should appear

<img width="805" alt="image" src="https://user-images.githubusercontent.com/35001775/205021317-6de9fcbd-9260-4e48-80a9-f26968348dd2.png">

Reject button on application details page

<img width="754" alt="image" src="https://user-images.githubusercontent.com/35001775/205021458-0affe8f9-b4c3-4e12-b208-d6a484fa4b10.png">

- [ ] Clicking on the reject button, should open the same popup as shared in the screenshot below. Once a user clicks confirm button, the application should be rejected, and if emails are selected, they should be sent out.

Sample popup that appears once `Reject` action is selected on application details page.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/35001775/205021554-a619dd58-78e8-4d70-9007-583edf3cd8e7.png">

**Acceptance criteria**
The reject button in application evaluation dialog box, should function the same as the one in application details page.

**Comment by rajatsajwan** [comment]
![Screenshot_20221205_120304](https://user-images.githubusercontent.com/117888235/205566235-f49f238f-090d-42ef-8549-fc4cb6e45d06.png)

**Comment by rajatsajwan** [comment]
sir in my system resume looks good    is not showing

**Comment by P4NK4J** [comment]
@rajatsajwan Try adding the segments and parameters from manage evaluations, or try running HR module seeder, that will populate the data required.
