### ISSUE TITLE
Show project details link to all team members

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2678]
**Feature Requested By**
@GauravGusain98 

**Describe the task**
Whenever a team member comes to the project listing page he is not able to open his project and see project details. This creates a problem for the key account manager of that project to edit the project as he is not able to open it. 

Currently, only the admin and super admin can open the project details from the project listing page using the link as shown in the image below
<img width="623" alt="image" src="https://user-images.githubusercontent.com/54376313/205438420-84ddf491-566d-4f65-9240-42138608bb81.png">

The link on the project name is not available for users with roles below admin. This should be fixed and the link should be available to all members of that project

**Expected behavior**
- [x] The link should be available to super-admin, admin and, all members of that project

**Additional info**
The link is disabled for users with the role below admin. So there might be a permission check that has been added to enable and disable the link. We just need to remove that check.

**Comment by GauravGusain98** [comment]
### Action items

- [ ] Find and understand the logic that is used to show and hide the link on the project name
- [ ] Allow the link to all types of user. So that the link of all projects should be available to you
- [ ] Read how we can print a value in Laravel using `dd()` 
- [ ] Try printing `hello` using `dd` function
- [ ] Figure out how you can get details of the login user. Try printing it on the screen
- [ ] Figure out how you can find role of the user. Try printing it on the screen
- [ ] Learn about Model/Entities in Laravel. Put your understanding in the comment in your own language.
- [ ] Learn about View In Laravel. Put your understanding in the comment in your own language.
- [ ] Learn about Controller in laravel. Put your understanding in the comment in your own language.
- [ ] Learn about relationships in laravel. [Link](https://laravel.com/docs/8.x/eloquent-relationships#main-content)
- [ ] Read about accessors in Laravel. [Link](https://laravel.com/docs/8.x/eloquent-mutators#accessors-and-mutators)
- [ ] Now based on your understanding of above topic, try to check if the user is a member of a project or not
- [ ] Based on output, show and hide the link in the project name, so that the link is shown only on projects where the user is a team member of the project 
- [ ] Compare the functionality with the expected behaviour of the task, it should work on all cases

**Comment by Gauravchamoli1997** [comment]
As my understanding till now Model is used for questioning data from the table within the database as well as insert new records in the table

**Comment by Gauravchamoli1997** [comment]
view provide us a convenient  way to put or place all of our HTML in a separate files. View show us user interface.

**Comment by Gauravchamoli1997** [comment]
printing "hello" using dd function,
![Screenshot (2)](https://user-images.githubusercontent.com/121275531/210775360-e0b9d496-9b76-41de-8c25-6f56bd24344e.png)

**Comment by Gauravchamoli1997** [comment]
Printing Details of User profile using dd function
![Screenshot (3)](https://user-images.githubusercontent.com/121275531/210775613-fc21becf-c3aa-4ff1-89eb-9a37bb2e8d76.png)

**Comment by Gauravchamoli1997** [comment]
In MVC architecture C stands for Controller. Controller controls the behavior of a request. It generally handles request from routes.

**Comment by Gauravchamoli1997** [comment]
yes, user is a Member of project.
![Screenshot (7)](https://user-images.githubusercontent.com/121275531/210944358-6e2fe7a8-94b8-45f0-86b4-38291adc351d.png)

**Comment by GauravGusain98** [comment]
> In MVC architecture C stands for Controller. Controller controls the behavior of a request. It generally handles request from routes.

This is not explained properly. It can be explained better. What is the routes here?

**Comment by Gauravchamoli1997** [comment]
> > In MVC architecture C stands for Controller. Controller controls the behavior of a request. It generally handles request from routes.
> 
> This is not explained properly. It can be explained better. What is the routes here?

Route helps us to mapped all requests with the associate controller. 
Route is a way of creating request URL for an application.

Controller are class based php files.
Controller can group related request handling logic into a single class. 
Controller fetch data from model and send to the view.

**Comment by Gauravchamoli1997** [comment]
Controller interact with model with the help of logics we created in controller then model takes data from database and sends it to controller.
