### ISSUE TITLE
Ability to add feedback in Application evaluation dialog box

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2682]
Feature requested by 
@P4NK4J 

**The goal**
Streamline application evaluation in the employee portal

**Is your feature request related to a problem? Please describe.**
At ColoredCow, we believe that talent is a myth, and given the right platform and exposure, we can create talent. Most of the fellows at ColoredCow are an outcome of the same philosophy. As we are on a growth journey, to achieve scale, we would require talents at all levels. For candidates to join us via the outbound method, we have the job openings listed on our [website](https://coloredcow.com/career/). 
Whenever a person applies for a particular job, we use the employee portal to execute the lifecycle of the application. Once it is received into the system, the first step is to evaluate their CV/Resume. The resume helps us to know the candidate better, including:
1. Past project experience, the ecosystem in which they worked
2. Native place
3. Skillset matching out requirements etc.

While evaluating the resume of a candidate, in the application evaluation dialog, a member of the HR team may want to put in any specific feedback. Adding this feedback can help to save why they think the resume is a good fit or not. With the current system, they can add comments, outside the evaluation dialog box, and then save it, for further feedback, they again need to get back to the evaluation dialog box. This leads to a bad user experience and there might be chances of data loss during the back and forth. 

Current comment feedback text box
<img width="740" alt="image" src="https://user-images.githubusercontent.com/35001775/205875749-5e096d12-d351-4bb1-8e8d-cad1d4b4c141.png">

Application evaluation dialog box
<img width="812" alt="image" src="https://user-images.githubusercontent.com/35001775/205875931-320a81a8-5a26-4396-82d6-5c019a989cca.png">

**Describe the solution you'd like**
To provide a better user experience, we would like to have a comment text box inside the evaluation dialog box, on the first and second steps.
First step
<img width="812" alt="image" src="https://user-images.githubusercontent.com/35001775/205875993-64a3030e-a192-4548-bc57-895d9afe9495.png">

Second step
<img width="823" alt="image" src="https://user-images.githubusercontent.com/35001775/205876023-0e8be126-12ca-4635-9c1e-0fea771d3521.png">

Filling this comment box will save the data exactly at the same place in the database, where the overall feedback is captured (the first screenshot). If a user clicks on the next button, the comments added in the first step should be preserved in the comment box. 
These comments would be reflected in the outer and inner comment boxes. 

**Acceptance criteria**
- [ ] Create a comment box in the application evaluation dialog box
- [ ] Upon submission, the data should be saved in the `hr_application_round_reviews` table. 
- [ ] The data should be populated in inner and outer comment boxes, upon submit action. 
- [ ] If a user clicks on `Next` in the application evaluation dialog box, the comment area should remain the same, without previous data loss

**Comment by rajatsajwan** [comment]
![Uploading Screenshot_20230111_105117.png…]()

**Comment by rajatsajwan** [comment]
![Screenshot_20230111_105048](https://user-images.githubusercontent.com/117888235/211724062-fb451e6c-b063-4763-8f96-2a039ac2bd29.png)
![Screenshot_20230111_105117](https://user-images.githubusercontent.com/117888235/211724091-95d6ded4-ad4b-43a3-858d-156d153127a3.png)

**Comment by rajatsajwan** [comment]
sir UI should be like this.?

**Comment by rajatsajwan** [comment]
or UI should be like this.
![Screenshot_20230111_121212](https://user-images.githubusercontent.com/117888235/211736173-2f469c1e-fa73-4dbe-a66e-e6c8eae6fc54.png)
![Screenshot_20230111_121224](https://user-images.githubusercontent.com/117888235/211736186-5b61d868-0c30-4376-b1a6-eeaf7845b87c.png)
