### ISSUE TITLE
Store invoice term in database

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2737]
**Enhancement Suggested By**
@GauravGusain98 

**Is your feature request related to a problem? Please describe.**
To manage finance we should have all the information of the invoice captured with us. This will help us to fetch all the necessary information regarding an invoice whenever needed. 

One of the important such information is terms of the invoice. The term of the invoice defines the period for which the invoice is raised. 

We already have the columns `term_start_date` and `term_end_date` present in the database where we want to store the start and end date of the invoice term. In this task we need to write the logic to populate those columns in the database.

**Additional context**
Once we are able to store the term of the invoice then we don't have to calculate the term every time and we can directly use this information while creating invoices and sending mails corresponding to invoices.

**Related issues**
https://github.com/ColoredCow/portal/issues/2732

**Point of Contact for guidance**
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action Items

- [ ] Find the logic in the codebase where invoice entry is created. 
- [ ] Figure out the logic to calculate the term start date and end date.
- [ ] Discuss the term calculation logic with @GauravGusain98 
- [ ] Once the logic is reviewed and approved, add code to store term data in the `term_start_date` and `term_end_date` columns of invoices table

**Comment by Hemrajbharti123** [comment]
### **term start date and term end date is added **
![image](https://user-images.githubusercontent.com/121417679/213139655-7a3b494b-78a9-4379-bfe0-8791f0f41068.png)

**Comment by Hemrajbharti123** [comment]
### Form data is printing on screen using dd() function

![image](https://user-images.githubusercontent.com/121417679/213338379-ef567664-5744-490d-9bda-42e770669a03.png)

**Comment by Hemrajbharti123** [comment]
Invoice data along with start date and end date 

![image](https://user-images.githubusercontent.com/121417679/213384315-32734523-37b0-4915-8dae-9a7d5747c406.png)

**Comment by Hemrajbharti123** [comment]
### Dummy function which returns true.

![image](https://user-images.githubusercontent.com/121417679/213624407-12e42fd5-f733-44dd-b5ad-ea53bcff551d.png)

**Comment by Hemrajbharti123** [comment]
### getTermStartAndEndDate function

![image](https://user-images.githubusercontent.com/121417679/213637451-dfe43650-3672-4cf3-994e-ca7ecca22666.png)

**Comment by Hemrajbharti123** [comment]
### Ready to send invoice

![image](https://user-images.githubusercontent.com/121417679/213643470-f5a0f3fc-d313-4d49-b448-56fa290dedb0.png)

**Comment by Hemrajbharti123** [comment]
### Lines responsible for generate invoice pdf
![image](https://user-images.githubusercontent.com/121417679/215734962-7be6b235-54f4-41af-ae9c-f668411abba7.png)

**Comment by Hemrajbharti123** [comment]
### Use of dd() in InvoiceService

![image](https://user-images.githubusercontent.com/121417679/216020842-41b02dba-d159-48df-95e7-c22f16126d5b.png)

**Comment by Hemrajbharti123** [comment]
### Use of dd() in InvoiceService

![image](https://user-images.githubusercontent.com/121417679/216021046-0e277da4-22cc-4be9-8604-85cfcf28b72a.png)

**Comment by Hemrajbharti123** [comment]
### The flow of code is define in  InvoiceService file 

![image](https://user-images.githubusercontent.com/121417679/216030988-fdc9ed0d-283d-461e-958b-f0702da65d30.png)

**Comment by Hemrajbharti123** [comment]
### Function getTermStartAndEndDate is called from invoiceService 

![image](https://user-images.githubusercontent.com/121417679/216247605-c6c121a3-401e-49dd-90e8-c66fe957f539.png)

![image](https://user-images.githubusercontent.com/121417679/216247633-01bcafdd-df5b-4b64-93ef-6671311d6a53.png)
