### ISSUE TITLE
When a user is an administrator, invoices can be deleted.

### ISSUE THREAD

**Issue by belwalshubham** [ColoredCow/portal#2739]
When a user deletes specific invoice information as an administrator, it is not deleted; however, if the user is a super-admin or another, it is deleted.

We have invoices in the finance module, and after clicking on the invoices and then on a specific invoice number, that invoice information can be deleted. On the network tab, you can see the error shown in the screenshot below.

![portl](https://user-images.githubusercontent.com/61574835/209783631-9a5d4420-97dc-43a3-ab7d-47aa8afed221.PNG)

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
