### ISSUE TITLE
Make the functionality to `Add Role` in User Management  

### ISSUE THREAD

**Issue by belwalshubham** [ColoredCow/portal#2741]
**Is your feature request related to a problem? Please describe.**
- We need to make the functionality to Add the new roles in the User Management `Role` Section.

**Describe the solution you'd like** 
- [ ] We need to Add the `Add New Role` Button in the User Management `Role` Section.

**ScreenShot shared for reference**
![image](https://user-images.githubusercontent.com/80516839/210199596-6f93f7cd-5b20-4d29-aacf-f03952ed7747.png)

- [ ] When Clicking on the `Add New Role` Button then One modal has been opened, In this Model, users fill out the Role Details. 

**ScreenShot shared for reference**
![image](https://user-images.githubusercontent.com/80516839/210199659-6c7586f4-7f90-4093-9e3d-5f054a2659b1.png)

**Comment by deepakbarmola** [comment]
Closing the issue as linked PR is approved and merged.
