### ISSUE TITLE
Phase 1.2: CodeTrek Module

### ISSUE THREAD

**Issue by Ayush8923** [ColoredCow/portal#2743]
**Feature Suggested By**
@Ayush8923 

**Parent Issue:-** https://github.com/ColoredCow/portal/issues/2704

**Related Issue**
https://github.com/ColoredCow/portal/issues/2734
https://github.com/ColoredCow/portal/issues/2736

**Is your feature request related to a problem? Please describe.**
In ColoredCow, CodeTrek is a journey that most of the interns do. In it, they learn the basics of software development and hone their skills. Now, we want to track and capture this journey of all the interns in Portal. This will help us to monitor the progress of each individual and see where we can or they can do better. 

For this, we have introduced Codetrek Module in the previous [task](https://github.com/ColoredCow/portal/issues/2736). In this task, we will be creating the page that will be used to display the applicant's list and details.

**Point of contact for guidance**
@GauravGusain98

**Comment by nishant22029** [comment]
Bootstrap Modal
•Bootstap Modal allows users to create modal windows (pop-up windows) on their webpages.
•It can be used to display additional information, such as images, forms, videos, and more. 
•Bootstrap Modal is a JavaScript library that provides an easy way to create responsive and customizable modal windows.

Html forms
•HTML forms are used to collect user input.
• Forms are created using the <form> tag and contain various types of input elements such as text fields, radio buttons,
  checkboxes, and submit buttons.

Actions attribute in forms
•The action attribute is used to specify the URL of the page that will process the form data.
•It is used to tell the browser where to send the form data when it is submitted.

Methods attribute
•The method attribute specifies how to send form-data.
•The form-data can be sent by using URL variables with method="get" or  HTTP post transaction with method="post".
  get:
  •Never use get to send sensitive data as it will be visible in the URL
  •It is useful for form submissions where a user wants to bookmark the result
  •get is better for non-secure data, like query strings in Google
  post:
  •It appends form-data inside the body of the HTTP request data is not shown in URL
  •It Has no size limitations
  •Form submissions with post cannot be bookmarked

**Comment by GauravGusain98** [comment]
### Additional Requirement 
- [ ] In add new applicant form, also add a text field for capturing phone number. 
The field label should be `Phone`

**Comment by nishant22029** [comment]
ok sir
