### ISSUE TITLE
Add new options in project financial details

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2754]
**Is your feature request related to a problem? Please describe.**
In the portal, there are a few categories of projects like hourly billing, fixed budget, and AMC. Among these AMC projects are the projects where we are only responsible for the system maintenance and no new features or enhancement is covered in this.

The contract period for these AMC projects is of 1 year or more based on contract terms and the invoice for AMC projects goes quarterly i.e every 3 months. 

We want to send invoices for AMC projects quarterly. For this we need to have options of `Per Month`, `Per Quarter`, `Per Year` in the project financial details

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/54376313/210788037-09a00915-8b50-4077-bbf5-5ce98d492c92.png">

**Describe the solution you'd like**
- [x] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [x] Read about Model in Laravel. Share your understanding of why we use them in the task comment in your own language
- [x] Read about Views and blade files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [x] Find the code for the project financial details section
- [x] Figure out how options are shown in dropdown
- [x] Add new options in the dropdown
- [x] Read how we can print a value in Laravel using dd()
- [x] Try printing hello world using dd function
- [x] Now read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [x] Now read about how forms are submitted in Laravel. Share the data flow from form to backend using a rough diagram. Post the image in the comment. 
- [x] Check how the data is getting stored in the database. Share the list of functions in a sequence that are being used while execution of the whole flow.

**Additional context**
Once this is implemented we can use this detail to generate invoice for AMC projects. For that we will create new tasks. 

**Point of Contact for Guidance**
@GauravGusain98

**Comment by Hemrajbharti123** [comment]
Controller are class based php files . controller can group related request handling logic into a single class, Basically it acts as a intermediator between model and view. Controller call model and insert data into view. 
types of controller laravel provide 
1. Basic controller 
2. Single action controller 
3. Resource controller

**Comment by GauravGusain98** [comment]
> Controller are class based php files . controller can group related request handling logic into a single class, Basically it acts as a intermediator between model and view. Controller call model and insert data into view. types of controller laravel provide
> 
> 1. Basic controller
> 2. Single action controller
> 3. Resource controller

Can you tell me how we are using controller when we are submitting any form from Portal? If you're using any technical term in your language like model, views then please explain them as well. 

Note: Just write in simple sentence what you understood. No need to write the language that you are finding on google.

**Comment by Hemrajbharti123** [comment]
1.**Controller in Laravel**
Controller is the central unit of laravel framework it connect the view and model. It interact with model component to fetch data from the database and then pass that data to the view component to get the output on the user browser

**Comment by Hemrajbharti123** [comment]
2.**Model**
Model handles the data used in application. It helps to fetch the data from database and perform some operation. Each database table has a corresponding model

**Comment by Hemrajbharti123** [comment]
3.**View and Blade**
View include frontend code . It contain the part of code which helps to display data on the user  browser.
Blade is a templating engine in laravel. It convert plain text into php text.

**Comment by Hemrajbharti123** [comment]
![image](https://user-images.githubusercontent.com/121417679/211522550-8a2a6f6e-2b67-4655-8ed3-c2f33c3d5aa7.png)

code for project finance details

**Comment by Hemrajbharti123** [comment]
New option is added successfully 
![image](https://user-images.githubusercontent.com/121417679/211721705-dca092ca-6165-48b1-ad5b-63818f039b3b.png)

**Comment by Hemrajbharti123** [comment]
printing hello world using dd function
![image](https://user-images.githubusercontent.com/121417679/211725662-beff718b-c222-4486-bfcc-93548c5298c2.png)

**Comment by Hemrajbharti123** [comment]
printing hello world from dd funtion

![image](https://user-images.githubusercontent.com/121417679/211725780-b2f16460-d255-4e36-b585-0361ba0c759d.png)

**Comment by Hemrajbharti123** [comment]
Route is used for creating request URL for any application. It help us to map all request which are coming from associate controller. Routes have two parameters i.e data and function

**Comment by Hemrajbharti123** [comment]
**Data Flow Diagram**

![IMG20230111134026](https://user-images.githubusercontent.com/121417679/211752795-ae7478c0-93e2-4854-9f07-5e2faf166582.jpg)

**Comment by GauravGusain98** [comment]
> **Data Flow Diagram**

Nice try. The flow diagram doesn't correctly represent the flow of data like we use in Portal. 

Can you write down the steps in sequence of how data moves from a form to a database and then back to the view.

**Comment by Hemrajbharti123** [comment]
step 1 Make a form in view
step 2 Make a controller for submit data
step 3 Make routing for view and controller 
step 4 Get form value in controller

**Comment by GauravGusain98** [comment]
> step 1 Make a form in view step 2 Make a controller for submit data step 3 Make routing for view and controller step 4 Get form value in controller

This is not correct. `Hint: The first step is the data moves from form to route.` Please write further steps

**Comment by Hemrajbharti123** [comment]
Step2. data moves from route to controller 
Step3. data moves from controller to model
Step4. data moves from model to database

**Comment by Hemrajbharti123** [comment]
**Steps for data getting store in database**
Step 1. Create a form
Step 2. Create a route for form
Step 3. Create a controller 
Step 4. Create a route for Controller 
Step 5. Create a model for the table 
Step 6. Import model in controller 
Step 7.In controller create a function for store data

**Comment by GauravGusain98** [comment]
> Step2. data moves from route to controller Step3. data moves from controller to model Step4. data moves from model to database

Step 4: Once we get data from model we return it to controller
Step 5: Controller return that data back as a response or as a view

**Comment by Hemrajbharti123** [comment]
**Three More options are Added to dropdown**

![image](https://user-images.githubusercontent.com/121417679/212245806-018e9673-d015-4133-a251-d95333d2a49e.png)

**Comment by GauravGusain98** [comment]
> **Three More options are Added to dropdown**
> 
> ![image](https://user-images.githubusercontent.com/121417679/212245806-018e9673-d015-4133-a251-d95333d2a49e.png)

Please move `Per Resource` and `Overall` option to bottom.

**Comment by Hemrajbharti123** [comment]
Done with Changes
![image](https://user-images.githubusercontent.com/121417679/212248692-c6d424e6-65e4-4816-8fc6-f255ee6cdb28.png)
