### ISSUE TITLE
Error occurring while running project seeders

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2757]
**Bug Issued By**
@Raj504 

**Describe the bug**
While running the project seeder, there is an error occurring in some windows devices. The error related to a column `reason_for_deletion` in the projects table where the column is not nullable.  Ideally it should be nullable column but in schma it is not due to which whenever we are trying to create an entry in the project table, it is expecting `reason_for_deletion` column to have a value, and as no value is passed so it is showing this error.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54376313/211010624-9992e84b-0c3a-4ad2-a288-4af8735163de.png">

**Solution**
- We need to make a migration that will make the `reason_for_deletion` column nullable in the table

**Environment where the issue is occurring**
Os - Windows
Environment - Local

**To Reproduce**
1. Try running project seeder. find how you can run a seeder corresponding to a particular module

**Additional context**
Due to this issue, many interns may face difficulty in project installation.

**Comment by Hemrajbharti123** [comment]
![image](https://user-images.githubusercontent.com/121417679/212827477-fff38db1-2791-4c08-b97e-f6f9b8888db9.png)
 can i share the PR?

**Comment by GauravGusain98** [comment]
The down method is incorrect. It should be opposite of up function. So if in up function you are making the column nullable then in the down function you should make the column not nullable instead of deleting the column

**Comment by GauravGusain98** [comment]
For raising the PR, you don't need to take permission. You can open the PR anytime and give it for review once you feel that the code changes have been done. Make sure to check your code changes before assigning the PR for review.
