### ISSUE TITLE
Functionality to add resource requirement in a project

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2766]
**Feature suggested by** 
@GauravGusain98 

**Is your feature request related to a problem? Please describe.**
In a project, at a point in time, there is always resource/team member requirement. If there is a page where we can see how many team members for a designation are required in a project then it would help us to know how many people do we need to hire or train. 

**Describe the solution you'd like**
In the project details page shown below, we can add a section for `Resource Requirement` where we can add a count of team members for each designation that is required for the project to work smoothly. 

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/54376313/212318210-517b086f-38d2-4d40-9a31-ffece27c8ce2.png">

The page should also display the count of team members that are already deployed in the project for a designation and by comparing the required team member count with deployed team member count we can show the team member requirement for a designation.

**Additional context**
This will help us to improve automation in the hiring process.

**Point of contact for guidance**
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action items

**Basics -  1 Pointer**

**Comment by race45** [comment]
how we can send form data to the controller in Laravel?
:- 1) Make HTML form.
   2) Make Controller.
   3) Route view & post
   4) Get form data
-First we make a controller with command (PHP artisan make:controller userController). make a function inside controller.
-Then make a route for it in `web.php`. import the controller then make route `Route::post("form",[userController::class,'getdata'])`. in controller we have a function getdata().
-then create a HTML form (form.blade.php). in blade create form & including `<form>tag` & use csrf token. in `<form>tag` we pass 2 attributes, action (in action write a route of form), method (GET or POST).
-in `web.php` we need to make view route for (form.blade) `Route::view("login", "form")`.
-when any user hit submit button the route will goes to `Route::post("form",[userController::class, "getdata"])` getdata function will execute. in getdata function we use Request type parameter. then return $request->input();

**Comment by GauravGusain98** [comment]
> how we can send form data to the controller in Laravel? :- 1) Make HTML form. 2) Make Controller. 3) Route view & post 4) Get form data -First we make a controller with command (PHP artisan make:controller userController). make a function inside controller. -Then make a route for it in `web.php`. import the controller then make route `Route::post("form",[userController::class,'getdata'])`. in controller we have a function getdata(). -then create a HTML form (form.blade.php). in blade create form & including `<form>tag` & use csrf token. in `<form>tag` we pass 2 attributes, action (in action write a route of form), method (GET or POST). -in `web.php` we need to make view route for (form.blade) `Route::view("login", "form")`. -when any user hit submit button the route will goes to `Route::post("form",[userController::class, "getdata"])` getdata function will execute. in getdata function we use Request type parameter. then return $request->input();

Why you are making new controller? Can't we use existing one's for this functionality?
Why we use CSRF token?

**Comment by race45** [comment]
Why we use CSRF token?
A CSRF token is a secure random token.The token needs to be unique per user session and should be of large random value to make it difficult to guess. A CSRF secure application assigns a unique CSRF token for every user session.

**Comment by GauravGusain98** [comment]
### Action items Related to calculation of deployed resource

- [ ] Now we need to calculate the number of resources that are currently deployed in the project. So you will need to get the current team members list and show the count based on designation in the deployed fields. 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/54376313/219008827-6c5cd553-8eb5-43ba-910e-32c9dce804dd.png">
- [ ] To be deployed field should be calculated by formula `needed - deployed`

**Comment by race45** [comment]
In the database table, the data are not present which you shared. 
![image](https://user-images.githubusercontent.com/92683476/219016071-722515fa-3417-4428-9bdf-1cdfa1364e13.png)

**Comment by GauravGusain98** [comment]
Check how the data is coming in the team member section in project edit page.
