### ISSUE TITLE
Ordering Client dropdown by name

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2773]
**Enhancement suggested by**
@GauravGusain98 

**Is your feature request related to a problem? Please describe.**
In any application, the UI should be user-friendly i.e user should not find any difficulty using different components in the application. In the portal, any user who wants to edit project details faces difficulty finding the client while changing the client from the dropdown. Currently, the client list is not ordered by name which is causing trouble, if we sort the list by client name in ascending order then it would be easier to find the client for that list. 

So we want to order the client list by client name in ascending order.

**To replicate the problem**
- Go to edit project screen 
    <img width="1295" alt="image" src="https://user-images.githubusercontent.com/54376313/212808789-f168f6cd-0455-4540-a29a-af6fea0cf2e8.png">
- Check the client dropdown and see the client order, it is not sorted by names

**Additional context**
This task will improve the user experience while using the portal. 

**Point of Contact for Guidance**
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action Items
**Basics - 1 pointer**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function
- [ ] On the project details page print details of the project using `dd` function
- [ ] Read about HTML forms and how we submit forms. Also, share the use of the below provide items
    - [ ] Action attribute in the form
    - [ ] Method attribute in the form 
    - [ ] Name attribute in any HTML tag and its importance while form submission

**Sorting - 1 pointer**
- [ ] Figure out the function from where we are fetching the client's details/name and passing them to frontend
- [ ] Read about [Laravel queries](https://laravel.com/docs/8.x/queries) and some basic queries like
    - [ ] [Running Database Queries](https://laravel.com/docs/8.x/queries#running-database-queries)
    - [ ] [Basic Where Clauses](https://laravel.com/docs/8.x/queries#basic-where-clauses)
    - [ ] [Select Statements](https://laravel.com/docs/8.x/queries#select-statements)
    - [ ] [Ordering, Grouping, Limit & Offset](https://laravel.com/docs/8.x/queries#ordering-grouping-limit-and-offset)
- [ ] Now try to update the query that is used to fetch client details in a way that is to order the client's result by client name in ascending order. 
- [ ] Raise PR and assign it for reveiw

**Comment by nishant22029** [comment]
Models-models are used to connect or interact  with database. To create model we use command :php artisan make:model ModelName.we use models to manage and manipulate data.

Views- we put our html part into view or whatever we want to show to user .View templates usually written using the blade templating language.

Routes-It is used for mapping our laravel page with specific url, it  also  used to map to controller actions for creating, updating, and deleting records. 

Controller- It is central unit of any mvc architecture,all logical part are done in this part .It fetches the data from model and view 

service files-service files are  used to centralize application logic and make it easier to maintain, test and debug. They allow us to organize our code into logical groups, making it easier to read, understand.

**Comment by GauravGusain98** [comment]
> Models-models are used to connect or interact with database. To create model we use command :php artisan make:model ModelName.we use models to manage and manipulate data.
> 
> Views- we put our html part into view or whatever we want to show to user .View templates usually written using the blade templating language.
> 
> Routes-It is used for mapping our laravel page with specific url, it also used to map to controller actions for creating, updating, and deleting records.
> 
> Controller- It is central unit of any mvc architecture,all logical part are done in this part .It fetches the data from model and view
> 
> service files-service files are used to centralize application logic and make it easier to maintain, test and debug. They allow us to organize our code into logical groups, making it easier to read, understand.

The motive of putting updates in your own language is that we can get to know what you understand from these topics and if there is anything that needs to be corrected. But most of your updates are definitions that we can get from the internet. Hope you understood the concept as these things will be used quite frequently ahead.
