### ISSUE TITLE
Add link to client in project details

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2781]
**Enhancement suggested by**
@GauravGusain98 

**Describe the task**
Good navigation helps to improve user experience in an application. In the projects details page, we show the client name to the user but if we want to see the details of the client then a user has to go to the client page and then search for the client and see his points. Instead of going through this long process, it would be better if a user can just go to a particular client by clicking on the client's name present in the project details page.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54376313/213688612-5c686a09-640a-43ca-9ddc-628be5ca5138.png">

**Expected behavior**
- We want to add link to client name so that on clicking it user is redirected to the client details page shown below. _NOTE: You can go to client details page from client listing_
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54376313/213688810-35474e1e-5824-486d-a97a-6460b6eb0bf3.png">

**Point of Contact for guidance**
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action Items
**Basics - 1 pointer**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function
- [ ] On project details page print project data using dd function.

**Comment by rajneeshweb** [comment]
- Models in Laravel. 
The model is the database table which holds(store) the application data and logic. and the controller directly interacts with the model to modify or change the view.

- Views in Laravel.
View is the part which shows the data to the user and also handles user interaction. View get its data from model and generates the presentation for the user. view files must have .blade.php extension and are created in View folder.

- Routes in Laravel.
Routes are the urls which we create for the application routes are created inside the routes folder. They are created in the web.php file for websites.

- Controller in Laravel.
Controller is like middleware of the application which interprets the input from the user and handles the user interaction by informing model and the view to change as appropriate. Controller is class based file in Controllers folder.

- Services files in Laravel.
A service file is a class that provides the functionality that the class provides, that can be reused in multiple other parts of the application.

- Print a value in Laravel using dd()
Laravel collection provides the wrapper for working with arrays of data. To print this collection we use the dd() function which is combination of dump() and die().
dump() to print the data and die() to halt the process.
`Public function list(){
   $data = task::all();
   dd($data->toArray());
}`
