### ISSUE TITLE
Office location and capacity - phase 1 

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2783]
**Enhancement suggested by**
@P4NK4J

**Parent Issue**
https://github.com/ColoredCow/portal/issues/2382

**Is your feature request related to a problem? Please describe.**
In ColoredCow we have a culture to freely move to different locations and work from there. As ColoredCow is growing and now we have multiple offices at different locations so we need to manage the capacity of an office so that is not overpopulated at a particular time. 

To manage these kinds of things, we need an operation Module where we will create functionalities related to operations. 

**Additional context**
On this module is set up in the portal, then we can start managing our operations-related tasks from the Portal, which will help us to easily manage our infrastructure, capacity, etc

**Point of Contact for guidance**
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action Items
**Basics - 1 pointer**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function

**Laravel Modules - 1 pointer**
- [ ] Read about the [Laravel module](https://nwidart.com/laravel-modules/v6/basic-usage/creating-a-module) and what is benefit of it. Share your understanding in your own language in the task comment. 
- [ ] Create a new module in Portal with the name Operations

**Add Home page - 1 Pointer**
- [ ] Add Operations option in Menu bar as shown in below image
    <img width="1416" alt="image" src="https://user-images.githubusercontent.com/54376313/213862119-39d63b52-77f5-4267-9858-ca227408f228.png">
- [ ]  When Clicking on the `Office Location` link, then a page should open, in which the header and its center should have `Coming Soon` written.
    <img width="876" alt="image" src="https://user-images.githubusercontent.com/54376313/213862288-f098e18a-c209-46a4-b086-44be641a8e2d.png">

**Comment by Harshvardhan80** [comment]
Laravel modules
-A Laravel module is a larvael package
-It has controller, model ,views or routes
-It  helps to make projects

create module in larvel
-got go xampp-htdocs-larevel project file
-start the command and write the command line >php artisan module: make module_name

**Comment by Harshvardhan80** [comment]
![IMG-20230204-WA0001](https://user-images.githubusercontent.com/112154429/216773782-8a5da97d-99f0-429b-88ef-53ea661059eb.jpg)
![IMG-20230204-WA0000](https://user-images.githubusercontent.com/112154429/216773783-8ef3a8fe-1a03-491b-8d3a-90d0513c32fb.jpg)

**Comment by GauravGusain98** [comment]
The menu bar is not present in the images you shared above

**Comment by Harshvardhan80** [comment]
![IMG-20230208-WA0000](https://user-images.githubusercontent.com/112154429/217334242-b7d5cd9c-9b34-463f-beee-c59be82cec39.jpg)
![IMG-20230208-WA0001](https://user-images.githubusercontent.com/112154429/217334247-aa9c6eab-37e3-4350-a614-a43532d9814f.jpg)

**Comment by GauravGusain98** [comment]
> ![IMG-20230208-WA0000](https://user-images.githubusercontent.com/112154429/217334242-b7d5cd9c-9b34-463f-beee-c59be82cec39.jpg) ![IMG-20230208-WA0001](https://user-images.githubusercontent.com/112154429/217334247-aa9c6eab-37e3-4350-a614-a43532d9814f.jpg)

Please use the existing menu bar. you don't need to create a new menu bar for every page

**Comment by Harshvardhan80** [comment]
![IMG_20230209_130328](https://user-images.githubusercontent.com/112154429/217747242-c3d9163c-c982-4a7e-b31c-f8f9dd497ee4.jpg)
![IMG_20230209_130241](https://user-images.githubusercontent.com/112154429/217747246-b2933050-e7a6-4a17-a1a6-861aadbe1928.jpg)
![IMG_20230209_130303](https://user-images.githubusercontent.com/112154429/217747247-075bf58c-0896-4996-a0e0-9ee4de29c118.jpg)

**Comment by GauravGusain98** [comment]
This UI doesn't look as per the one shown in action items. Please make it correct

**Comment by Harshvardhan80** [comment]
![IMG_20230223_224425](https://user-images.githubusercontent.com/112154429/220982138-dba5e8ad-08a7-4f03-a1ef-35d29261d806.jpg)
![IMG_20230223_224119](https://user-images.githubusercontent.com/112154429/220982150-b86dc09e-bd3f-4633-a722-a4485bee7be4.jpg)

**Comment by GauravGusain98** [comment]
Looks fine. Have you created PR for this?
