### ISSUE TITLE
Zero Expected Effort Mail coming for inactive projects

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2787]
**Bug Raised By**
@pokhiii 

**Describe the bug**
In Portal, we want to remove unwanted team members from the project so that no project should have extra resources. To solve this problem we have created a mail functionality that sends an alert email every Monday to the key account managers whose projects have team members with expected hours are zero.  

The email template looks something like this, 
```
Hi, Key account Manager Name
We found some projects where the expected hours are zero for you or team members where you are 
assigned as key account manager. Please update these projects:

Project Name
Project 1
Project 2 
Project 3
```

The problem we are facing is that this alert also includes 
1. The project that is inactive/halted
2. Project team members who are not a part of the team now. i.e They have been removed and are marked as ended

**To Reproduce**
1. Run Project seeder so that a project is created with a client
2. Now go to the client page and edit a client and set yourself as the key account manager of the project
3. Edit any project of the client and set the expected effort of any team member to zero
4. Now mark that project as halted or inactive
5. Setup mailtrap as per step 12 provided in the [installation guide](https://github.com/ColoredCow/portal/blob/master/docs/installation.md)
6. Run the command `php artisan project:zero-effort-in-project`
7. You will receive the halted project name in the mail in your mailtrap inbox

**Expected behavior**
The email should only contain the active project and active team members

**Environment on which the issue is occurring**
All

**Additional context**
Due to this, the key account managers are getting incorrect information and they have to check their projects manually

**Contact person for guidance**
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action items
**Basics Concept - 1 pointer:**

- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function

**Scheduling custom command**
- [ ] Read about [schedule commands](https://laravel.com/docs/8.x/scheduling) in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Check how we run the scheduled commands

**Eloquent**
- [ ] Read how to make database queries in Laravel using this documentation: [Link](https://laravel.com/docs/8.x/queries) 
- [ ] Read about Laravel Relationship: [Link](https://laravel.com/docs/8.x/eloquent-relationships#main-content)

**Bug Fixing - 1 Pointer**
- [ ] Find the command file that is used to send email
- [ ] Find the function that is used to get data for email. Share the function name and file in which it is defined in the comment section
- [ ] Go to the function and undertand how it is working. Share your understanding of the workflow in the comment
- [ ] Figure out why the inactive/halted projects are getting fetched
- [ ] Figure out why ended team members are getting fetched
- [ ] fix the issue and test by sending mail using the command. The mail should only contain valid projects Name
- [ ] Raise a PR and assign it for reveiw

**Comment by kanuj365** [comment]
Basics Concept ->
Models in Laravel -> In laravel a Modal represents a database table and provides an easy way to interact with that table. It can also be used to insert, retrieve and update data in the database.to create a model we can use the artisan command-
(php artisan make:modal ModalName)

Views in Laravel -> In laravel Views are used to represent the HTML content that is sent to the browser. and it is also used to display the dynamic data by controller. The views contain plain html with this also includes Blade templates.
  public function show()
  {
return view('welcome')
}

Routes in Laravel -> In laravel, Routes define the url structure of our application and map urls to actions in our controllers. The routes are defined in the "web.php". here are different types of methods are available like 
Route ::post() when we try to submit the form we can use post method to maps a url to a function.
Route:: put()  when we try to update the a resources on the server then it is used.
Route::get()  when we try get data from database then we use this get method.
Route::resources() when we need a set of routes in controller for a crud operation then we can use this. etc.

 Controller in Laravel-> In laravel, a controller is a class that defines HTTP endpoint behavior. it handle the incoming http requests and returning appropriate response. even Controller perform different tasks like data validation, accessing models to retrieve data and returning views  .
here is different types of controller like-
Single action controller 
Resource controllers

Services files in Laravel -> In laravel , a service file use for wide range of tasks, such as processing data , shared  logic and it can also be used to share logic between multiple parts of the application, such as controllers, models and other services.

how we can print a value in Laravel using dd()
public function hello($id)
{
$showclient=Client::where('id',$id)->get();
dd($showclient);
}
in this function i'm getting all client whose id is equal to id i.e. passing as parameter and i can see that by dd.

 printing hello world using the dd function->
 dd("hello world") main php file
 @dd("hello world")->in blade file
 

Scheduling custom ->
 Scheduling custom command-> Laravel provides a convenient way to schedule repetitive tasks by using Task Schedular, -
how we can create this->
1- create a console command by using this command (php artisan make:command MyCommand).
2- after the command run a file will be generate where a handle function will be available in MyCommand class.
3- In handle function you can define your task .
4- Open the kernal.php file and in the schedule method add a call to the command method, passing the name of the console command you want to schedule and use the cron or every method to set the schedule for running the command ex-($schedule->command('project:zero-expected-hours-in-project')->weekly()->tuesdays()->at('11:00');).
5-Run the following command to register the scheduled tasks. (php artisan schedule:run).

**Comment by kanuj365** [comment]
> `understanding of the workflow`

![image](https://user-images.githubusercontent.com/68420715/215642650-ca2b75b9-be5f-41b9-9a22-a0b528e7ac93.png)
