### ISSUE TITLE
Show client id in client page

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2792]
**Enhancement Requested By**
@mohitsharma-22 

**Problem Statement**
Every client that we create in the portal has an id corresponding to it. This id is not the `id` column of the clients table in the database instead it is the sequence number of the client. Whenever a new client comes we provide it a client_id so that we should know which number of clients it is for us.

We use this client_id in the invoice number as well. So we want to know the client id corresponding to the client in portal. 

**Point of contact for guidance**
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action items

**Basics Concept - 1 pointer**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function
- [ ] Try printing the detail of any client on the client page using the dd() function

**Add client id - 0.5 pointer**
- [ ] On the client page add a new column `client id` before the client name. The value of this column should be taken from the `client_id` column 

**Sorting - 2 pointer**
- [ ] Add sorting icons in front of the name and id column similar to what we have on the Recruitment page
    ![image](https://user-images.githubusercontent.com/54376313/214581475-0cbefbd5-4674-45df-9e8a-52c35ff6719d.png)
- [ ] On hovering over these icons the cursor should work to change to a finger shape. _Note: For styling, we use HTML classes instead of adding CSS styles. We already have a defined class for the cursor with a pointer shape, just find it and add it to these icons_
- [ ] On clicking these icons the list clients should be sorted according to those columns. 
    - [ ] Find how the clients are sorted right now
    - [ ] Figure out the approach of how you are going to implement the solution so that the client should be ordered as per the selection. Write down the approach in the comment and share it with @GauravGusain98 
    - [ ] After approval, start working on solution

**Comment by Priyanka-Kaintura** [comment]
sir, Can I try proceeding forward using Ajax if thi is the criteria for sorting.

![image](https://user-images.githubusercontent.com/112419110/223411799-d08ff741-eb65-4a9f-ad80-2496e8fa075b.png)

**Comment by Priyanka-Kaintura** [comment]
![image](https://user-images.githubusercontent.com/112419110/223412085-14c1ee72-6cd3-4feb-a3d9-4bb6d5d42b49.png)

**Comment by Priyanka-Kaintura** [comment]
however I found more direct things like Kyslik, a package for handling column sorting in laravel. This approach will add on certain things to the configuration. but for other similar cases the package can be used directly without much things to work on.


[https://github.com/Kyslik/column-sortable/blob/master/README.md](url)

**Comment by Priyanka-Kaintura** [comment]
Services is a tool for injecting dependencies in a class using constructor or setter and getter methods. For example it can retrieve data from the models and can pass it to the controller.  

Printing hello world using dd function : dd('Hello World')
