### ISSUE TITLE
Need a way to download the FTE of all the project in a excel file. 

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#2810]
We need a way to download the FTE status of all the resources in an excel file so that the finance team can define some reports for resource management. 

Sharing my thoughts on implementing this.

1. Add a button on the main project screen with Export as Excel. 
2. When the User will click on that an excel file will be downloaded with the following columns. 
  1. Team member name 
  2. Project name
  3. Date
  4. FTE
  

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/10670690/218018335-d01bd2ef-9534-407c-bc04-b06737f3ea0c.png">

**Comment by yuvraj752** [comment]
Breakdown of problem statement

- [ ] Create a button on project screen
- [ ] on clicking the button, empty excel file should be downloaded
- [ ] Passing project, team members' data in exported excel file
- [ ] Passing FTE in the excel sheet

**Comment by pankaj-ag** [comment]
@yuvraj752 I have updated sample 2. Let's proceed with that. We can make modifications later if we need. 

Also let's keep the file name with current timestamp name: YearMonthDay -> 20220512

**Comment by mohitsharma-22** [comment]
@yuvraj752 @pankaj-ag Getting below error while access export to excel. Please check.

<img width="1143" alt="Screenshot 2023-02-28 at 11 35 47 AM" src="https://user-images.githubusercontent.com/16541548/221768580-f3a0cf5d-20e6-403a-8af2-4f7b73f5f4b6.png">

<img width="1172" alt="Screenshot 2023-02-28 at 11 37 55 AM" src="https://user-images.githubusercontent.com/16541548/221768725-6dad5b7f-3e4a-4725-ba0b-95d3b32412b1.png">

**Comment by mohitsharma-22** [comment]
@yuvraj752 @P4NK4J Thanks the report looks good. 

You can close this task.
