### ISSUE TITLE
Project TeckStack not showing

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2816]
**Issue Raised By** 
@GauravGusain98 

**How to Replicate**
1. Go to Projects
2. Edit a project 
3. Go to `Project Techstack` section 
    <img width="1203" alt="image" src="https://user-images.githubusercontent.com/54376313/218367508-c423c3f3-da0a-4574-8ba2-d01de196f56e.png">
4. Fill Teckstack details
5. Save the details
6. The updated data is not shown in the fields

**Expected behavior**
One we save the teckstack form, the updated data should be displayed in the page

**Comment by GauravGusain98** [comment]
### Action Items
**Basics Concept - 1 pointer:**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function

**Form Submission**
- [ ] Read about HTML forms and how we submit forms. Also, share the use of the below provide items
- [ ] Action attribute in the form
- [ ] Method attribute in the form and different types of Methods
- [ ] Name attribute in any HTML tag and its importance while form submission
- [ ] Read about `old()` function in laravel

**Bugfix**
- [ ] Find if the data is getting stored in database 
- [ ] See why its not getting shown in the form
- [ ] Make chnages to display stored data in the form as well
- [ ] Create a PR
- [ ] Do self review of your code changes in GitHub
- [ ] Assign for review

**Comment by rajneeshweb** [comment]
**Basics Concept - 1 pointer**
- [Previously Answered](https://github.com/ColoredCow/portal/issues/2781#issuecomment-1407372506)

- An HTML form is used to collect user input.
The HTML `<form>` element is used to create an HTML form.

- The action attribute defines the action to be performed when the form is submitted.
the form data is sent to a file on the server when clicking the submit button.

- The method attribute specifies the HTTP method to be used when submitting the form data.
The form-data can be sent as URL variables with method="get" or as HTTP post transaction with method="post". we never use GET method to send sensitive data.

- The name attribute specifies the name of a form.
The name attribute is used to reference elements in a JavaScript, or to reference form data after a form is submitted.

- The old() function is used to retrieve the value of the field from the previous form submission.
