### ISSUE TITLE
HR update schedule throwing error 500 

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2817]
**Describe the task**
Updating schedule in application view page, throws an error

**Steps to replicate**
Currently, if we go to HR->Recruitment in navigation, application listing would appear. 
For any application, click on view, a screen to view the application appears. 
If we go to the dropdown section at the bottom -> select a user from the dropdown -> click on update schedule -> the page throws an internal server error
<img width="927" alt="image" src="https://user-images.githubusercontent.com/35001775/218645330-a758bc28-4168-4dbb-a036-116dcbd21efa.png">

<img width="963" alt="image" src="https://user-images.githubusercontent.com/35001775/218645409-afb8cbe0-4838-4aa1-8abc-7830eb13548d.png">

We want this to be debugged and fixed. The update schedule button should work similar to its working in `Evaluate` section.

**Comment by GauravGusain98** [comment]
### Action items
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function

**Comment by Adarsh123Singh** [comment]
### **Models:**
It can manage data and Business logics. It can be used in our project to manage data giving data to the portal. And it can also be used as a questioning data  and from the table (if table is used) within the database.

**Comment by Adarsh123Singh** [comment]
**### Views**
view is a method in laravel to seperate controller and domain logic. And it is also used in html code required by the application.
It is used in our task in html code in giving required application in portal. And it is also seprate controller and domain logics in laravel.

**Comment by Adarsh123Singh** [comment]
### **Routes:**
Routes file directly saved in folder routes in all laravel routes automatically. So without Routes our tasks cannot contain in laravel. Some methods are their in routes for eg:- get, put, patch, delete.

**Comment by Adarsh123Singh** [comment]
### **Controller:**
It is a class where user can written a Business logic in related request.
By Default, It can be stored in app/http/Controller folder.
It is used to store Business logic related request in a single class in given task in portal.

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
