### ISSUE TITLE
Open user dashboard page from profile

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2818]
**Enhancement Suggested By**
@HKKohli 

**Is your feature request related to a problem? Please describe.**
Currently, we see user details at 2 place, one from HR->working staff->employee details and other from `My profile` menu on the dashboard. 
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/54376313/218668599-ad1cf5f7-25cd-4d5d-9c8c-208eb6ca47fb.png">

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/54376313/218668866-97494d3e-b0fa-4884-8de1-be26d8c65325.png">

We want to open employee details from the `My profile` menu option. 

**Point of contact for guidance**
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action Items

**Basics Concept - 1 pointer:**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function

**Show dashboard**
- [ ] On Clicking `My profile` the employee details of the user should be shown
- [ ] Remove the routes, files and logic related to older profile section, as we will not be using it now.
- [ ] Create PR
- [ ] Do a self reveiw
- [ ] Assign the PR for review

**Comment by shreyakharola** [comment]
Views in Laravel contain the complete HTML of the project. Views is under **resources** directory. Here we separate HTML from our logic used in designing that page

**Comment by shreyakharola** [comment]
Routes are nothing but they direct us to the other pages. We use get here and it contains 2 parameters one for uri and other for callback(can keep it acc. To your wish). Web.php contains routes directories.

**Comment by shreyakharola** [comment]
Controllers are under app/Http/controllers directory. We organize all the request handling logic using controllers. Classes for controllers are created so the related request handling could group in as a single class. We also use middleware here which filters and inspect the http request before entering our application.

**Comment by shreyakharola** [comment]
Services files are there in the app.php file which is under config. All service providers extend the Illuminate\Support\ServiceProvider class. Service Providers are just classes to register so
me global functionality.

**Comment by shreyakharola** [comment]
dd stands for dump, die. 
The dump function dumps a variable's content to the browse and stops the script execution.
$users = User::all();
dd($users);
In output will be the users in an array

**Comment by shreyakharola** [comment]
public function index()
{
  $products ="hello world";
  dd( $products );
}

**Comment by Priyanka-Kaintura** [comment]
@GauravGusain98  Sir, here is one problem with the current solution for this issue, if the user is not an employee then clicking on 'My profile' will throw an error of missing parameter as the employee id will be null. PR: [https://github.com/ColoredCow/portal/pull/2909](url)
