### ISSUE TITLE
Show All projects by default to admin and super admin

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2826]
### Enhancement suggested by
@mohitsharma-22 

### Problem that your solution is solving
In project listing page by default the user project is shown. For admin and super admin user who usually are not in any project we want to show the all projects list by default. 

**Expected behavior**
- [x] #2839
- [x] For admin and super admin role users, the all project listing should be shown as default

### Contact person for help
@GauravGusain98

**Comment by GauravGusain98** [comment]
### Action items

**Basics Concept - 1 pointer:**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function

**Roles and Permission**
- [ ] Read about roles and permission - [Link](https://spatie.be/docs/laravel-permission/v5/basic-usage/basic-usage)

**Default project listing**
- [ ] Fix the logic such that for admin and super admin the default page should be `all project` instead of `my project`
    <img width="1376" alt="image" src="https://user-images.githubusercontent.com/54376313/219437212-1df204bc-e7bc-4726-9f9c-be0590ed633e.png">

**Comment by thisajaychauhan** [comment]
**views** - views is a graphical user interface by which users can interact.
all the things we can see on the display.

**models** - models are connected to controllers by which controllers interact with a database.

**controller**- controllers is a bridge between views and models. 
the controller contains the logical part. 
it is the heart of the MVC pattern.
receive updates from views then notify the model and apply crud methods. 
vice versa take updates from the database and display them in views.

**Services** - services also contain logical parts.
it is responsible for complex logic. like validation logic.

**routing** - routing is used in making a path to the particular page requested by the user.

**Comment by thisajaychauhan** [comment]
we can print a value using dd() in .blade.php file by 
@dd("**enter the text...** ");

**Comment by thisajaychauhan** [comment]
print **hello world** using the dd function

**Comment by thisajaychauhan** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/120373044/221768609-695ecde4-5745-4781-932d-7cb6d4447496.png)

**Comment by AJAYSINGHBISHT12** [comment]
Controller - it is the central unit .it controls model and  view .and it is the middle layer between database and HTML. it is inside the http file.
models- if we have to make connection in the database ,in this we use models.
view - inside view blade file is present and inside blade file everything is written in html. and everything we see in the display is due to the html written in blade file inside the view file.
routes - inside the route their is api route, channels route , console route, web route. routing basically on clicking the link to the user desired page.
Services-The Services directory contains various "helper" services our application needs to function.

**Comment by AJAYSINGHBISHT12** [comment]
we can print a value using dd() in blade.php file
@dd("enter the text");

**Comment by AJAYSINGHBISHT12** [comment]
![Screenshot 2023-03-18 130631](https://user-images.githubusercontent.com/123948333/226092123-d9a85083-199a-4843-9116-97d712bd76b9.png)
