### ISSUE TITLE
Add Levels/Rounds for CodeTrek Applicants 

### ISSUE THREAD

**Issue by nishant22029** [ColoredCow/portal#2848]
Parent Issue:- https://github.com/ColoredCow/portal/issues/2704

Related Issue
https://github.com/ColoredCow/portal/issues/2734
https://github.com/ColoredCow/portal/issues/2736
https://github.com/ColoredCow/portal/issues/2743
https://github.com/ColoredCow/portal/issues/2794
https://github.com/ColoredCow/portal/issues/2807

Is your feature request related to a problem? Please describe.
In ColoredCow, CodeTrek is a journey that most of the interns do. In it, they learn the basics of software development and hone their skills. Now, we want to track and capture this journey of all the interns in Portal. This will help us monitor each individual's progress and see where we can or they can do better.

For this, we have introduced Codetrek Module and added functionality to add, edit, and delete applicants' details in previous tasks.

Now we need to add the Levels/Rounds of the applicants and provide the functionality to streamline Evaluation Process.
![image](https://user-images.githubusercontent.com/114382264/221354858-dbf3cdd8-43b7-4b6c-89bd-307b1378413e.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/114382264/221355422-d8acb390-d9e0-42d7-9778-98cecd18f846.png)

### Action Items
- [x] Read about [Laravel Migration](https://laravel.com/docs/8.x/migrations#creating-tables). Create a column **Round**  in the code_trek_applicants  table in the employee portal database.
- [x] Add view and Evaluate button as shown in the image below.
![image](https://user-images.githubusercontent.com/114382264/221358652-f14b922a-9ebe-4612-ac0f-c779ed65bfb2.png)
- [x] On clicking the view button it should be redirected to the applicant-edit page where all the data of the applicant will be shown.
- [x] On clicking the Evaluate button it should be redirected to the applicant-evaluation page where data of the applicant will be shown in the image below.
![image](https://user-images.githubusercontent.com/114382264/221484068-f3076995-0b11-4bf9-a4b6-dba53a4d174c.png)
- [x] Read about accordion in Bootstrap.
- [x] Inside the applicant-evaluation page make functionality so that on click of **Take action**  applicants can be evaluated and their **Rounds** should be updated.

**Comment by GauravGusain98** [comment]
The issue description looks fine, you can start working on it.

**Comment by nishant22029** [comment]
![image](https://user-images.githubusercontent.com/114382264/222070308-fd16bf1e-5e4a-44ba-b841-6e266c45a231.png)
should i have to store feedback in code_trek_applicant details table or another table

**Comment by GauravGusain98** [comment]
There should be another table with the name `codetrek_applicant_round_details`

There you will add applicant_id, round_name, and other details corresponding to that round 
for very new round of applicant a new entry will be created in this table. So it will have one-to-many realtionship
