### ISSUE TITLE
Finance Report: Revenue by Client

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#2853]
When the user will go to revenue by the client. We need a report where the user can compare the client revenue on different months. 

We already have an overall report for the same set of data in the P&L reports and I think we can leverage the same code base to filter out the data based on the client. 

We can remove the revenue filter since that does not make any sense in this report. 

The report will look like something In the screenshot. The client listing should be vertical and the month-wise revenue will be horizontal. 

At the last we need a total of the data (It should include the filters also if applied)

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/10670690/221775638-457cb72f-5802-4ebf-81b9-2ab4ac0e12d2.png">

Once we have the data in the portal we need to give the ability to export it in the excel also.

**Comment by yuvraj752** [comment]
@pankaj-ag I have created a landing page for Revenue by Client.

![Capture](https://user-images.githubusercontent.com/49526581/224917900-ec3ab401-2db3-4c4c-a1d4-8ad72d82ce3b.PNG)

clicking revenue visualization card opens client revenue graph and the client revenue report card is disabled.

![Capture1](https://user-images.githubusercontent.com/49526581/224918035-fdc086a1-8c3e-4262-9088-a5935db596e6.PNG)

![Capture2](https://user-images.githubusercontent.com/49526581/224918164-2d11cff2-aa15-4c20-bf89-13cfdb255958.PNG)

@pankaj-ag if there is any changes thats need to be made feel free to let me know.

**Comment by yuvraj752** [comment]
Breakdown of problem statement
- [ ] create a empty table in the view
- [ ] pass the client data in the view table
- [ ] export the client data in the excel file
