### ISSUE TITLE
Don't show red color on project velocity if it is the first date of billing period

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2886]
### Background
In ColoredCow some of the projects are charged hourly. So we have to capture the hours booked in the hour and based on it we generate the client invoice/bill for the period. 

The velocity of the project is the ratio of hours booked in the project and the total expected hours in the project for a billing period. In an ideal scenario, it should be 1. 

We currently show the velocity of a project on the project listing page as shown below. 
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/54376313/219282099-ce655322-859b-436b-b2f1-80e46bd0feb5.png">

The project velocity has red and green indicating if it is poor or good. When a new billing month start, initially the velocity is 0 due to which the velocity comes red. 

### Task 
- We want the velocity to come in black color instead of green and red on first day of the billing period irrespective of the velocity value. 

### Additional Context
- The billing date changes after 10 PM in the night. So write the code accordingly
- To test this functionality, you have to change the date of your computer to the billing start date.
- You can set the billing start date from the client details. Therefore fill all the details of the client.

**Comment by AJAYSINGHBISHT12** [comment]
for black colour we have to write text-secondary

**Comment by AJAYSINGHBISHT12** [comment]
![Screenshot 2023-03-21 181249](https://user-images.githubusercontent.com/123948333/226609547-0ff4868c-d2e0-4401-bb33-85a608e27127.png)

**Comment by GauravGusain98** [comment]
@AJAYSINGHBISHT12 The task is that if today is first date of billing period then you don't have to highlight the velocity shown in the project listing page. 

What you need to find?
1. How you will get billing date of the project.
- You can find it from the client details of the project


Technical details:
- By default the color of text is black. So no class is needed to make the color black
- You just need to compare the dates and based on that highlight the velocity

**Comment by AJAYSINGHBISHT12** [comment]
sir please check the syntax and I'am getting errors in this syntax

**Comment by AJAYSINGHBISHT12** [comment]
@php
                                            $textColor1 = $project->billing_date == (today(config('constants.timezone.indian'))) ? 'text-dark' : 'text-danger';
                                             $textColor = $project->velocity>=1 ? 'text-success' :'text-danger';
                                        @endphp
                                        <a class="{{ $textColor }}"
                                            href="{{ route('project.effort-tracking', $project) }}"><i
                                                class="mr-0.5 fa fa-external-link-square"></i></a>
                                        <span
                                            class="{{ $textColor || $textColor1 }} font-weight-bold">{{ $project->velocity . ' (' . $project->current_hours_for_month . ' Hrs.)' }}</span>
                                    </td>
                                </tr>
