### ISSUE TITLE
Fix setting icon in book listing page - Mobile

### ISSUE THREAD

**Issue by mohitgusain** [ColoredCow/portal#2916]
**Describe the bug**
In Mobile, go the books listing page, and you will see the setting icon is getting overlaps with the book title

**Expected behaviour**
An icon position should align nicely so that it comes nicely. Apply some UI thinking

**Screenshots**
![image](https://user-images.githubusercontent.com/30264862/228538740-eeb71bbc-df08-4a3e-a869-7b3bb9e7fd2e.png)

**Comment by GauravGusain98** [comment]
@MayankMukul Can you start working on this task https://github.com/ColoredCow/portal/issues/2944. You can skip this one for now.
