### ISSUE TITLE
Fix the Alignment of Employees tile in HR working staff

### ISSUE THREAD

**Issue by Gauravchamoli1997** [ColoredCow/portal#2918]
**Describe the task**
The Alignment of the Highlighted box as shown below is not look good. The text and buttons are not vertically aligned. 
![Screenshot (122)](https://user-images.githubusercontent.com/121275531/228742178-33f9341a-660a-41e7-921e-dc86ff80c2bf.png)

**Expected behavior**
The Alignment should be correct and equal. They should be vertically centre aligned

**References**
Specify any reference material / links

**Comment by GauravGusain98** [comment]
Not needed as design team will work on portal designs and propose new designs
