### ISSUE TITLE
Add requisition button functionality on the project resource page. 

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#2929]
**Describe the task**
Usually FTE of a user can be greater than 1 which means user is doing extra work on the other hand, it can be less than 1 which means user is not working optimally. So, we want to add requisition button to the project resource page which will help user to fill and submit a form to requisite the resource.

Attached the screenshot for the reference: 

![Screenshot (27)](https://user-images.githubusercontent.com/106467597/230015635-0348044e-e954-41c1-b563-c8c7543cfb39.png)

**Expected behavior**
On resource requisition page add a column name ```Requested By``` which contains user id who have submit a requisite resource. 

Action Items

- [x]  Find a file where add requisition button is displayed.
- [x]  Understand the flow of button when clicked and the data it contains.
- [x]  Now, add same button to the project resource page with a new column name Actions to it.
- [x]  Add a new column name Requested By to the job_requisition table using migration command and also to the UI of resource requisition page.
- [x]  Now, fetch the data in the Requested By column with user id.

**Comment by GauravGusain98** [comment]
Can you add required changes in for of points?

**Comment by rahulpanwar16** [comment]
Actions needed: 

> Can you add required changes in form of points?

Action Items

- [ ] Find a file where add requisition button is displayed. 
- [ ] Understand the flow of button when clicked and the data it contains.
- [ ] Now, add same button to the project recourse page with a new column name Actions to it.
- [ ] Add a new column name Required By using migration command and to the resource requisition page also.

**Comment by rahulpanwar16** [comment]
> Can you add required changes in form of points?

Action Items

- [ ] Find a file where add requisition button is displayed. 
- [ ] Understand the flow of button when clicked and the data it contains.
- [ ] Now, add same button to the project recourse page with a new column name Actions to it.
- [ ] Add a new column name Required By using migration command and to the resource requisition page also.

**Comment by rahulpanwar16** [comment]
> Can you add required changes in form of points?


Can you add required changes in form of points?

Action Items

- [ ]  Find a file where add requisition button is displayed.
- [ ]  Understand the flow of button when clicked and the data it contains.
- [ ]  Now, add same button to the project resource page with a new column name Actions to it.
- [ ]  Add a new column name Requested By to the job_requisition table using migration command and also to the UI of resource requisition page.
- [ ]  Now, fetch the data in the Requested By column with user id.

**Comment by rahulpanwar16** [comment]
**Unit Testing**

- Added a requisition button on project resource page and when we click on button a modal is displayed.
- Optimized the process time when we submit a requisition.
- Removed success alert to success toast message when we submit a requisition.
- Success toast message also shown when we submit a second requisition.

![Screenshot (84)](https://user-images.githubusercontent.com/106467597/233910365-2789b60b-2082-4f33-811b-720144fca8fb.png)


- Optimized the process time when we submit a requisition on fte handler page as well.
- Removed success alert to success toast message when we submit a requisition.

![Screenshot (87)](https://user-images.githubusercontent.com/106467597/233910463-f07ff8ea-b235-4acb-a6c0-e4b3ac9467e6.png)
