### ISSUE TITLE
Make the invoice issue date ,end date of the invoice term.

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#2930]
**Is your feature request related to a problem? Please describe.**
As per CA, We need to create the invoice in the same month date when we have given the service. The main issue is at the end of the financial year. where March invoices are created in April. Many clients also requested to create the invoice with date of 31 March and not with 1st April.

**Describe the solution you'd like**
The invoice we create from portal has the invoice date on which we generate the invoice.  Please make the invoice issue date end date of Term. For example invoices of March month is of term 1st March - 31st March. The invoice issue date should be 31st March. and not the 1st April, even if we create and send the invoice on 1st April

<img width="482" alt="Screenshot 2023-04-04 at 4 18 09 PM" src="https://user-images.githubusercontent.com/16541548/229769540-d11d8abf-f3cb-402f-8ce5-d269744408e5.png">

**Comment by AmishaBisht** [comment]
The issue date should be 31 if the invoice is created on the 1st what should be the date for other cases like the invoice is generated on 12 April?

**Comment by AmishaBisht** [comment]
![Screenshot (157)](https://user-images.githubusercontent.com/90472056/232453363-fbcbf9b3-820a-44cc-853e-7924e3cbd293.png)

**Comment by GauravGusain98** [comment]
@AmishaBisht 
So we store the billing date of a client in the client_billing_details table. This date is the day when the invoice should be sent.

Currently while generating an invoice we show the issue date as the date when we send the invoice but what we want is that the issue date should be 1 day less than the billing date of the invoice i.e (term_end_date)

**Comment by AmishaBisht** [comment]
@GauravGusain98 in the above case the issue date should be 16 April?

**Comment by GauravGusain98** [comment]
> @GauravGusain98 in the above case the issue date should be 16 April?

Yes, if the billing date of client is 17
