### ISSUE TITLE
Search Functionality in CodeTrek Page

### ISSUE THREAD

**Issue by Himanshunegi0332** [ColoredCow/portal#2946]
**Describe the task**
Currently in a CodeTrek page we don't have any search functionality.
We need a search functionality in CodeTrek page similar to what we have in Project listing page.
The searching on the codetrek page will be on the basis of Applicant Name.

**Expected behavior**
![Screenshot (83)](https://user-images.githubusercontent.com/108523408/230015526-a886d2ba-7c50-4059-9915-d60d4dd519f9.jpg)

**Comment by GauravGusain98** [comment]
Questions
1. Over which field we want to search? Please mention that also in description.
