### ISSUE TITLE
Change the layout of project contract page 

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#2974]
**Describe the task**
Currently project resource page is taking full width at all responsive breakpoints. We want to change the layout which sets a max-width at each responsive breakpoint.
Attached a screenshot : 
![Screenshot (37)](https://user-images.githubusercontent.com/106467597/231142565-61f60c8e-22e0-4360-af08-ffdd9d0be085.png)

**Expected behavior**
Attached a screenshot :
![Screenshot (36)](https://user-images.githubusercontent.com/106467597/231142392-232a65e5-c564-459c-bee1-57e4d87ac529.png)

**Comment by payalpm** [comment]
@rahulpanwar16 can u tell me little bit about project and which file changes u want

**Comment by GauravGusain98** [comment]
The UI is getting re-designed. This task is not needed now.
