### ISSUE TITLE
Fix nav items alignment of home page 

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#2980]
**Describe the task**
On the portal home page under the card header named books the alignments of nav items ```Your wishlist , You have read and Recommend``` are not correct below 1200 px.
Attached a screenshot for reference :

![Screenshot (39)](https://user-images.githubusercontent.com/106467597/231443856-aafea68c-b2c5-4091-9708-0952893d4129.png)

**Expected behavior**
Alignments of nav items should be in a same line below 1200 px as shown below : 
 
![Screenshot (42)](https://user-images.githubusercontent.com/106467597/231451650-911e98b5-4aa6-419e-aeb8-2048b7f15a18.png)

**Comment by GauravGusain98** [comment]
This is more of a UI issue. Design team will be creating new designs for portal. So this issue is not needed.
