### ISSUE TITLE
Update Feedback in CodeTrek

### ISSUE THREAD

**Issue by Hemrajbharti123** [ColoredCow/portal#2984]
**Describe the task**

When an applicant in CodeTrek moves to several levels we can give them feedback also, but these updates are not shown on the home page of CodeTrek. You have to show the latest feedback on the home page of CodeTrek if we don't give the feedback to the applicant then it should look like it does now on the home page.

**Additional context**
You have to show the updated feedback in the `feedbacks` column.

![image](https://user-images.githubusercontent.com/121417679/231668148-109473ec-9f08-499a-b782-25e73cda502a.png)

**Action Items**

-**Pre-Requisites**

- [ ] Take a pull request for the latest updates [Reference link](https://www.linkedin.com/pulse/what-differences-between-git-pull-origin-master-shruthi-rajkumar/)
- [ ]  Run migration [Reference link](https://nwidart.com/laravel-modules/v6/advanced-tools/artisan-commands)
- [ ] Add applicant in Codetrek.

- **Basic 1 pointer**

- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language.
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language.
- [ ] Read about Views and blade files in Laravel. Share your understanding of why we use them in the task comment in your own language.
- [ ] Read about migration and seeder commands in Laravel. Share your understanding of why we use them in the task comment in your own language.
- [ ] Now read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language.
- [ ] Now read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language.

- **Workflow Understanding**

- [ ] Find the code for the updated feedback section.
- [ ] how we update the feedback and figure out the flow.
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing hello world using the dd function.

- **Update the existing files**

- [ ] When you know the flow properly update the code to achieve the goal.

**Comment by GauravGusain98** [comment]
I think we can keep this on hold. I am not sure if we need to show feedbacks in the listing page or not

**Comment by GauravGusain98** [comment]
Not neeeded
