### ISSUE TITLE
Key Account Manager dropdown in client details page

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#2994]
**Describe the task**
When creating/updating a client, in the list of Key Account Managers, there are a few problems:
1. The names are not sorted, so it's difficult to identify the person we want to select
2. The names of inactive users are also coming, as a result the list is unnecessarily long!
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/12053186/232401723-db8fd3da-2c46-43ec-85f8-2a2f574a8351.png">

**Expected behavior**
1. The names should be sorted
2. Inactive users should not be included

**Comment by Priyanka-Kaintura** [comment]
@GauravGusain98 Sir, where do we check the status of user as active or inactive in this, I can only find the status of clients and projects. Please give me a reference to check the user status

**Comment by GauravGusain98** [comment]
> @GauravGusain98 Sir, where do we check the status of the user as active or inactive in this, I can only find the status of clients and projects. Please give me a reference to check the user status

If a user has a `deleted_on` column filled in the `users` table in the database then he/she is inactive, else if the field is null then he/she is a active user.
