### ISSUE TITLE
Search filter Functionality on project resource page. 

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#3003]
**Describe the task**
Currently, we only have search functionality on project resource page. However, we want to add a functionality of filter also on this page for better user experience.  

**Expected behavior**
For reference attached a screenshot of project resource page where filter icon is attached besides search input:
![Screenshot (67)](https://user-images.githubusercontent.com/106467597/232994484-f127b460-1d34-4ac9-b8cb-163a4c800177.png)

For reference when user click on the filter icon the modal should be displayed with all designations name.
![Screenshot (65)](https://user-images.githubusercontent.com/106467597/232994540-d6fa6908-fa36-43d0-ad88-5774508e3262.png)

**To reproduce the data on project resource page**

- Go to projects from CRM nav bar.
- Click on any project and edit the project.
- Click on resource requirement tab.
- That tab will display all the designations name with needed and deployed. 
- You can fill the required designation needed and check if ```additional resource required is greater than zero``` then only data will be displayed to the project resource page as shown in above screenshot.

**Comment by rathorevaibhav** [comment]
Not a priority right now.
