### ISSUE TITLE
Show designations in resource required column on project resource page. 

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#3006]
**Describe the task**
Currently, ```additional resource required``` consists of a count which don't give us complete information. So, we also want to add a designation in the column that will provides the information what designation and what count is required, same as what ```resource needed and resource deployed``` columns gives us information. 

Attached a screenshot of the page:
![Screenshot (68)](https://user-images.githubusercontent.com/106467597/233032721-da187e16-ceda-4e02-bf79-ab342c793a82.png)

**Expected behavior**
In additional resource required column, show all designations and it's corresponding count that are required in a project 

**To reproduce the data on project resource page**

- Go to projects from CRM nav bar.
- Click on any project and edit the project.
- Click on resource requirement tab.
- That tab will display all the designations name with needed and deployed.
- You can fill the required designation needed and check if ```additional resource required is greater than zero``` then only data will be displayed to the project resource page as shown in above screenshot.

**Comment by Ayush8923** [comment]
This issue is completed. Closing this issue.
