### ISSUE TITLE
Update route based active navigation logic.

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#301]
Based on our discussion we need to change the current logic for active menus. 
Currently, we have some hardcoded URL values.
There are some hardcoded route values in all the menu item files. 

 ![image](https://user-images.githubusercontent.com/10670690/40598585-30998f08-6266-11e8-8dd5-068e028f0c40.png)

We need to figure out a way to remove them and map the menu with route names like. 

```
class="nav-item nav-link {{ Request::is('*'. route('applications.internship.index'). '*') ? 'active' : '' }}"
```

**Comment by rathorevaibhav** [comment]
@pankaj-ag can you put more details here? Like what are the hardcoded values and what should be the fix?
