### ISSUE TITLE
Reduce the character count of invoice number

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#3010]
**Is your feature request related to a problem? Please describe.**
With the new invoicing system (e-invoicing ) in place we need to limit the characters of the invoice number

**Describe the solution you'd like**
Please remove the extra 0 from the invoice number.

Current invoice number (Sample) = EX0020010000430423
Where EX is for International, IN for Indian/domestic
next 3 digit is for client code = 002
next 3 digit is for project code = 001
Next 6 digits is for invoice number = **000043**.
Next 2 digit is for Month = 04
Next 2 digit is for Year = 23

Remove first 3 0 form invoice number - 
*000043** should be now *043**.

New Invoice number will be = EX0020010430423

**Comment by GauravGusain98** [comment]
This is completed
