### ISSUE TITLE
Add Counts to each tabs in CodeTrek

### ISSUE THREAD

**Issue by Hemrajbharti123** [ColoredCow/portal#3023]
**Is your feature request related to a problem? Please describe.**

In CodeTrek we have three tabs `active`, `inactive` and `completed`. We have to show the count of applicants in each tab.

**Additional context**
We want it similar to how we show counts in project listing page 
![image](https://user-images.githubusercontent.com/121417679/234203332-81e02671-a893-4a19-962e-f816b3f0360f.png)

**Comment by jaskaransingh304** [comment]
Breakdown-
Code review and documentation: 0.5-1 hour.
Understanding the functionality : 0.5-1 hour.
Making the required changes : 2-3 hour.
Testing, code review, and documentation : 1 hour.

Expected Time =4-6 hours.
