### ISSUE TITLE
Add toast message when we create a contract on project contract page. 

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#3030]
**Describe the task**
Whenever new contract is created a alert success message is shown. We use the bootstrap alert success earlier but now we always add toast message as an alert.

Attached a screenshot for the reference of alert success message:
![Screenshot (98)](https://user-images.githubusercontent.com/106467597/234266301-ab530355-60ad-4b88-b277-d86525f7beed.png)

**Expected behavior**
Add toast message instead of alert success message.

Attached a screenshot for the reference:
![Screenshot (99)](https://user-images.githubusercontent.com/106467597/234266414-9cf34c6a-d517-426b-8dd3-8b0873685625.png)

**References**
You can take reference from the codetrek page while creating new applicant.

**Comment by GauravGusain98** [comment]
As the contract page is being revamped so this is not needed now.
