### ISSUE TITLE
Set Mandatory field in CodeTrek

### ISSUE THREAD

**Issue by Hemrajbharti123** [ColoredCow/portal#3035]
**Is your feature request related to a problem? Please describe.**
In CodeTrek when we add a new applicant a modal form is open, there are some fields that are mandatory and some that are not. Set    Graduation year is also a mandatory field. 

**Screenshot**
 
![Screenshot 2023-04-26 124634](https://user-images.githubusercontent.com/121417679/234499891-23b426eb-6b17-435c-87f1-136c085952d5.png)

**Action Items**

**Basic - Pointer 1**

- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ]  Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ]  Read how we can print a value in Laravel using dd()
- [ ] Try printing hello world using dd function
- [ ] Try to print any invoice details using dd function on the CodeTrek page

**pointer 1**

- [ ] Find the CodeTrek applicant create a form set the required field as mandotory

**Comment by GauravGusain98** [comment]
@Hemrajbharti123 This task is not needed. The graduation year is not compulsory. Closing this issue.
