### ISSUE TITLE
Fix search button alignment on working staff page

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#3038]
**Describe the bug**
In mobile, the working staff page the search button is moving out of the page which needs to be fixed.

**To Reproduce**
1. Go to 'HR'
2. Click on 'Working Staff'

**Screenshot**
![Screenshot (110)](https://user-images.githubusercontent.com/106467597/234565194-eb26e8a2-8a76-418f-9a3a-5e0401e49727.png)

**Expected behavior**
The search button should be shown properly in screen sizes :

- [x] #3058
- [ ] 425px
- [ ] 520px

**Additional context**

- [ ] Read how variable.scss file works.
- [ ] You may need to read about [bootstrap](https://getbootstrap.com/docs/4.0/utilities/sizing/) for classes that are used to change sizes of elements and text.

**Comment by GauravGusain98** [comment]
This is not needed now as design team will work on the portal designs
