### ISSUE TITLE
We need to add one more filter named `Dropped` in the CodeTrek Module

### ISSUE THREAD

**Issue by Ayush8923** [ColoredCow/portal#3040]
**Feature Suggested By**
@Ayush8923 

**Parent Issue:-** https://github.com/ColoredCow/portal/issues/2704

**Current Behavior**
- In the Employee Portal, we had introduced a new module named `CodeTrek`. In this module, the CodeTrek home page has 3 filters. 
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/80516839/234636179-9a77a1c7-41f3-4817-b2ff-3fde36fd1503.png">

**Excepted Behaviour**
- We need to add one more filter named 'Dropped'. When the user clicks on this `Dropped` filter, only applications that have been dropped should appear. Also, there should be a change in the status of their application.

**Procedure:-**
- Click the `View` button in any application.
- Click the `Delete` button to delete the application.
- After deleting this application, this application should appear in the `Dropped` filter.

**Comment by GauravGusain98** [comment]
Not needed
