### ISSUE TITLE
Fix the UI of client page 

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#3042]
**Describe the bug**
On Client page the the highlighted UI is not looking good. It should be properly aligned to the table. 

**Screenshot**
![test](https://user-images.githubusercontent.com/106467597/234785242-c40f9e46-4e52-4f87-aff6-08b7a40c29b5.png)

**To Reproduce**
1. Go to 'CRM'
2. Click on 'Clients'

**Expected behavior**
You can take reference from the project listing page. 
![Screenshot (114)](https://user-images.githubusercontent.com/106467597/234786968-e8357ecf-6530-4d39-82dc-5591d7b8faaf.png)

The page should be shown properly in screen sizes :

- [ ] 375px
- [ ] 425px
- [ ] 525px

**Additional context**
- [ ]  Read how variable.scss file works
- [ ] You may need to read about [bootstrap](https://getbootstrap.com/docs/4.0/utilities/sizing/) for classes that are used to change sizes of elements and text.

**Comment by GauravGusain98** [comment]
Not needed as design team will be prosing new designs.
