### ISSUE TITLE
Fix the space between add new applicant button and search field on codetrek page  

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#3044]
**Describe the bug**
In mobile, the Codetrek page has is no spacing between the ```add new applicant``` button and ```search field```. We want proper spacing in between. 

**Screenshot**
![Screenshot (115)](https://user-images.githubusercontent.com/106467597/234789153-2a760950-5c45-4401-ad8d-e8efe527dd4f.png)

**To Reproduce**
1. Go to 'Codetrek'

**Expected behavior**
The page should be shown properly in screen sizes :

- [ ] 375px
- [ ] 400px
- [ ] 530px

**Additional context**

- [ ] Read how variable.scss file works.
- [ ] You may need to read about [bootstrap](https://getbootstrap.com/docs/4.0/utilities/sizing/) for classes that are used to change sizes of elements and text.

**Comment by GauravGusain98** [comment]
Not needed as design team will work on portal designs and propose new designs
