### ISSUE TITLE
Responsive project show details page 

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#3046]
**Describe the bug**
On mobile, the team members table with velocity attribute is getting out of the page which needs to be fixed.  

**Screenshot**
![Screenshot (120)](https://user-images.githubusercontent.com/106467597/234834145-60204735-af18-4242-8789-c9584f6ce1dc.png)

**To Reproduce**
1. Go to 'CRM'
2. Click on 'Projects'
3. Click on 'Any Project name'
4. Scroll down to 'Team Members table'

**Expected behavior**
The page should be shown properly in screen sizes :

- [ ] 375px
- [ ] 425px
- [ ] 470px

**Additional context**

- [ ] Read how variable.scss file works.
- [ ] You may need to read about [bootstrap](https://getbootstrap.com/docs/4.0/utilities/sizing/) for classes that are used to change sizes of elements and text.

**Comment by GauravGusain98** [comment]
Not needed as design team will work on portal designs and propose new designs
