### ISSUE TITLE
Fix the UI of the table on project resource page  

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#3059]
**Describe the task**
Whenever, there is no such project found while searching a project the UI does not look good at the last column of the table. Hence, it needs to be fixed. 

Attached a screenshot for the reference:
![Screenshot (122)](https://user-images.githubusercontent.com/106467597/235908737-397eedb7-fbaa-4e18-8e0b-27d2feec348f.png)

**Expected behavior**

Attached a screenshot for the reference:
![Screenshot (72)](https://user-images.githubusercontent.com/106467597/235908491-ede6da69-4f7e-4802-8ec5-d4f55def5919.png)

**Comment by tarunnjoshi** [comment]
@rahulpanwar16 Could you please check if this issue is reproducible on your local? It seems that there is no UI case for the project resource page in the project.

**Comment by rahulpanwar16** [comment]
> @rahulpanwar16 Could you please check if this issue is reproducible on your local? It seems that there is no UI case for the project resource page in the project. If this issue is already done by someone please close it.

Yes, I have checked the UI of page is fine and I am closing this issue.
