### ISSUE TITLE
Add no applicant found when user searches for the applicant on codetrek page 

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#3060]
**Describe the task**
Whenever, there is no applicant found from any status tab it shows blank. So, we want ```No applicant found ``` should be displayed in the table.

Attached a screenshot for reference : 
![Screenshot (124)](https://user-images.githubusercontent.com/106467597/235925942-24565b2d-8112-4874-8b74-be46aea31acb.png)

**Expected behavior**
The `No applicant found` text should be shown if there are no applicant result. Similar to how it looks in project page
<img width="1440" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/ccd60db0-93ac-4d42-946f-073e913ef720">

**References**
You can take reference from the project listing page.

**Comment by jaskaransingh304** [comment]
### Expected Time - 4 hours.

Code review and documentation: 0.5-1 hour.
Understanding the functionality of similar code: 1 hour .
then ,
Making the required changes : 2 hour.

For testing, code review, and documentation : 1 hour.

TOTAL TIME SPEND IN A TASK =5 hours
