### ISSUE TITLE
Create a Sidebar in the homepage of the portal

### ISSUE THREAD

**Issue by Himanshunegi0332** [ColoredCow/portal#3062]
**Current Behavior**
Right now, we do not have a way to view the CodeTrek Applicants in the Employee Portal dashboard so that employees can give feedback to the applicant or see the progress of that applicant 

**Expected behavior**
- In this feature, we need to create a sidebar in the Employee Portal Dashboard, in which the names of all applicants are shown.
- The Sidebar should be on the right side near the My Profile navbar.
**Refer to the screenshot for the reference**
![Screenshot (101)](https://user-images.githubusercontent.com/108523408/236387214-58b64e83-593b-48dc-9216-4bfb537c6ae4.png)

**References**
- When the user clicks on this sidebar, the sidebar should open as shown in the below screenshot.
![image](https://user-images.githubusercontent.com/108523408/236389690-59fa0943-dbf3-44ea-8344-0d331f5edc60.png)

**Comment by Harshvardhan80** [comment]
![Screenshot 2023-05-05 152948](https://user-images.githubusercontent.com/112154429/236439640-9fbcd675-5c34-4dee-a4a5-9b71c3a91878.png)
I was asking that after clicking on the side bar the name of the applicant should come, something else?

**Comment by Ayush8923** [comment]
> ![Screenshot 2023-05-05 152948](https://user-images.githubusercontent.com/112154429/236439640-9fbcd675-5c34-4dee-a4a5-9b71c3a91878.png) I was asking that after clicking on the side bar the name of the applicant should come, something else? or to show only the name or after clicking on the name, go to the file of codetrek

@Harshvardhan80 Yes. For now, we just need to display the name of the applicant. In its second task, when the user clicks on the name of the applicant, it will redirect to a new page in which the user can give feedback to the applicant.

**Comment by Harshvardhan80** [comment]
![Screenshot 2023-05-08 165121](https://user-images.githubusercontent.com/112154429/236811721-8e6976c6-1add-4a80-8f6c-eb9db6398627.png)
that is right?
