### ISSUE TITLE
Functionality to provide feedbacks to codetrek candidates

### ISSUE THREAD

**Issue by Himanshunegi0332** [ColoredCow/portal#3067]
**Describe the task**
As in the previous issue #3062, we have made a sidebar on the homepage where we display the names of our Code Trek interns, but we want to make it easier for users to give feedback to the interns. To do this, we would like to create clickable links for the intern's name that will redirect users to the modal where they can submit feedback.

**Expected behavior**

- [ ] Add clickable links to the intern name on the sidebar and open a modal when a candidate name is clicked
- [ ] Show candidate details in the modal as shown in below provide image
- [ ] Create a table schema for database table to store feedbacks and categories

- The feedback modal should include the user's name, University, and Year in which it has an Observation, Categories, and feedback section.
 
- **The CodeTrek Feedback Modal should contain the following things:-**
![Untitled (1)](https://user-images.githubusercontent.com/108523408/236632151-b89137c4-3c6a-41bd-894a-688d5f007c21.png)

**Comment by thisajaychauhan** [comment]
@GauravGusain98 I have built the database schema for **code_trek_candidates_feedback** and **code_trek_feedback_categories**.
this is the link. 
https://docs.google.com/presentation/d/1g8oOr_XTdCGSNd6EaBeJSZxCFHTvuqgacdZx_ZSDyBM/edit?usp=sharing

**Comment by GauravGusain98** [comment]
> @GauravGusain98 I have built the database schema for **code_trek_candidates_feedback** and **code_trek_feedback_categories**. this is the link. https://docs.google.com/presentation/d/1g8oOr_XTdCGSNd6EaBeJSZxCFHTvuqgacdZx_ZSDyBM/edit?usp=sharing

please share the comment access for the database schema

**Comment by thisajaychauhan** [comment]
## Expected Time

- [x] Add clickable links to the intern name on the sidebar and open a modal when a candidate name is clicked. **3-4 hours**
- [x] Show candidate details in the modal. **3-4 hours**
- [x] Create a table schema for the database table. **1-2 hours**
- [x]  store feedback and categories. **3-4 hours**
- [x] For testing, code review, and documentation. **1-2 hours**

**Comment by thisajaychauhan** [comment]
there is a problem after getting the latest pull from the origin master it showing me a sidebar like this
![Screenshot 2023-06-01 163102](https://github.com/ColoredCow/portal/assets/120373044/5fe4e9c2-4b1b-43b4-ad77-1a420bbfd24f)

**Comment by thisajaychauhan** [comment]
## right now the modal is looking like this
![Screenshot 2023-06-02 112358](https://github.com/ColoredCow/portal/assets/120373044/250e69a3-61f0-47da-9859-1182836fbf95)

**Comment by GauravGusain98** [comment]
> ## right now the modal is looking like this
> ![Screenshot 2023-06-02 112358](https://user-images.githubusercontent.com/120373044/242797766-250e69a3-61f0-47da-9859-1182836fbf95.png)

The feedback type should be positive or negative instead of good or bad. 

Also the meaning of the thumbs-up or down icon are not clear. So also add label `Feedback Type` above them

**Comment by GauravGusain98** [comment]
> there is a problem after getting the latest pull from the origin master it showing me a sidebar like this ![Screenshot 2023-06-01 163102](https://user-images.githubusercontent.com/120373044/242577645-5fe4e9c2-4b1b-43b4-ad77-1a420bbfd24f.png)

Did you run `npm run dev`?

**Comment by thisajaychauhan** [comment]
no

**Comment by thisajaychauhan** [comment]
> > there is a problem after getting the latest pull from the origin master it showing me a sidebar like this ![Screenshot 2023-06-01 163102](https://user-images.githubusercontent.com/120373044/242577645-5fe4e9c2-4b1b-43b4-ad77-1a420bbfd24f.png)
> 
> Did you run `npm run dev`?

no

**Comment by thisajaychauhan** [comment]
now its showing good.

**Comment by thisajaychauhan** [comment]
### This is the `code_trek_candidate_feedback` table
![Screenshot 2023-06-02 180210](https://github.com/ColoredCow/portal/assets/120373044/d7938bad-1559-4ffc-9019-74e3a385a778)

### and this is the `users` table from where I am taking id as a `foreign key` in the above table
![Screenshot 2023-06-02 180310](https://github.com/ColoredCow/portal/assets/120373044/d13c607f-5087-42d1-9721-d27aa9478c68)

### iam encountering with this error 
 SQLSTATE[HY000]: General error: 1005 Can't create table `uta_portal`.`code_trek_candidates_feedback` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `code_trek_candidates_feedback` add constraint `code_trek_candidates_feedback_candidate_id_foreign` foreign key (`candidate_id`) references `code_trek_applicants` (`id`))


this error says that in both tables datatype of `foreign key` should be the same but in the user table datatype is `increment` and in .`code_trek_candidates_feedback` increment datatype is also assign to the primary key. with this error my second migration file also not getting migrate.

**Comment by thisajaychauhan** [comment]
now it is resolved.
