### ISSUE TITLE
Rename column name round_name to latest_round_name on the code_trek_applicants table

### ISSUE THREAD

**Issue by rahulpanwar16** [ColoredCow/portal#3076]
**Describe the task**
We have defined different types rounds according to the performance of the applicant.
Rounds such as:

- Preparatory
- Level-1
- Level-2
- Level-3
- Onboarded

So, currently on the code trek applicants table the column name is round_name which needs to be changed to ```current_round_name```

**Expected behavior**
Column name should be current_round_name which will displays the current round type of the applicant.  

**Action Items**

- [ ] Understand how migration file works. How it is named? What is the meaning of up and down functions inside the migration file? Take help from [Laravel documentation](https://laravel.com/docs/8.x/migrations)
- [ ] Rollback and then Create a new migration file to add current_round_name in the table. Take reference from [here](https://nwidart.com/laravel-modules/v1/advanced-tools/artisan-commands#modulemake-migration)

**Comment by Ayush8923** [comment]
This issue PR is merged. Closing it.
