### ISSUE TITLE
Introducing a new tab for onboarded in Code Trek module  

### ISSUE THREAD

**Issue by Akshiteshnaithani** [ColoredCow/portal#3079]
**Describe the task.**
In `CodeTrek` module , we have to create a  new tab called "Onboarded". Currently, the module consists of three tabs: Active, Inactive, and Completed. The purpose of the "Onboarded" tab would be to track the progress of Applicants who have successfully completed the onboarding process.

**Current Behavior**
Currently, the CodeTrek module consists of three tabs:
- **Active**
- **Inactive**
- **Completed**

**Screenshot**
![image](https://github.com/ColoredCow/portal/assets/121417968/1c7f39b3-b636-40b9-be2f-8a86517a0d8b)

**Expected Behavior**
When a applicant is selected to be moved to the "Onboarded" in the CodeTrek module , the applicant's profile should now be visible within the "Onboarded" tab.

**Comment by GauravGusain98** [comment]
This is not needed
