### ISSUE TITLE
Sending email notifications for new CodeTrek Applicant.

### ISSUE THREAD

**Issue by Akshiteshnaithani** [ColoredCow/portal#3083]
**Describe the task**
When a new applicant is added to the `Code Trek` an email should be triggered to notify the applicant about their successful application. Currently, this functionality is not implemented, and applicants are not receiving any email notifications.

**Current Behavior**
Currently, no email is triggered or sent to the applicant when a new applicant is added to the system. As a result, applicants remain unaware of the status of their application.

**Screenshot**
![image](https://github.com/ColoredCow/portal/assets/121417968/1cfa3d3b-7bb6-429f-ae09-ee133a57c9fe)

**Expected Behavior**
After adding a new applicant, an email should be sent to the applicant's provided email address. The email should contain relevant information regarding their successful application, such as a confirmation message, next steps, and any additional instructions

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
