### ISSUE TITLE
Trigger email notification when applicant round changes

### ISSUE THREAD

**Issue by Akshiteshnaithani** [ColoredCow/portal#3098]
**Describe the task**
Currently, there is a need to implement a feature that triggers an email notification whenever the round of an applicant is changed. This will greatly improve communication and informed about any updates or changes in the applicant's progress.

**Current Behavior**
At present, there is no functionality in place to send email notifications when the round of an applicant is changed. This lack of notification system makes it difficult to keep track of applicant progress.

**Expected Behavior**
The expected behavior is to have an email notification sent automatically when the round of an applicant is changed. The email should contain relevant information about the applicant, such as their name, current round, and any additional details which are necessary.

**Screenshot**
![image](https://github.com/ColoredCow/portal/assets/121417968/058440de-f6e5-4e87-9fc1-aa3a87acab2a)

Mail should be triggered by clicking the button `Take Action`

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
