### ISSUE TITLE
Center Name not Updated When Editing Codetrek Applicant Information

### ISSUE THREAD

**Issue by Harshvardhan80** [ColoredCow/portal#3109]
**Describe the task**
Currently, when editing the information of Codetrek applicants in the Codetrek module, the centre name field is not being updated when a different centre name is selected. this issue prevents the correct association of the selected centre name with the applicant.

**Steps to reproduce**
1. Go to the Codetrek module.
2. Select an applicant to edit their information.
3. Locate the "Centre Name" field in the form.
4. Select a different centre name from the available options.
5. Save the changes and observe the result.

**Expected behavior**
Upon selecting a different centre name while editing the Codetrek applicant information, the centre name field should be automatically updated to reflect the newly selected centre name. This ensures that the correct centre name is associated with the applicant, providing accurate information and tracking.

**References**
![Screenshot 2023-05-27 192736](https://github.com/ColoredCow/portal/assets/112154429/ce4f02e4-a719-497b-a550-ad5967aeb197)

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
