### ISSUE TITLE
Apply filter for downloading FTE-report excel.

### ISSUE THREAD

**Issue by AbhishekNegi25** [ColoredCow/portal#3125]
### Current Behaviour

Currently, if we download the FTE-report from project section. It generates an excel sheet having FTE of each employee for current month.

### Expected Behaviour

- [x] We need to introduce a `Month and Year` filter to download FTE report for a specific month.

**Additional context**

**Comment by AbhishekNegi25** [comment]
- [ ] Add two more columns `Committed Hours` and `Booked Hours`.
- [ ] Need to rename the file name, apply the below logic:
- If we apply the current month and year filter, the file name will be `FTE_Report-year-month-currentdate`.
-  If we apply the filter for other than the current month the file name will be `FTE_Report-year-month-last date of the month`.

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
