### ISSUE TITLE
Error occurring after updating Node.js and NPM versions

### ISSUE THREAD

**Issue by Akshiteshnaithani** [ColoredCow/portal#3136]
**Description:**
We recently updated the Node.js and NPM versions in our portal's tech stack. However, we encountered an error after performing the update.

**Steps to reproduce:**

- Update Node.js to [18.16.0].
- Update NPM to [9.5.1].
- Start the portal application.
- Run the command `npm run dev`

![unnamed](https://github.com/ColoredCow/portal/assets/121417968/45901216-66e5-4fc9-9029-bb4e986a498d)

**Expected behavior**
The portal should function correctly after updating the Node.js and NPM versions.

**Current behavior:**
After updating the Node.js and NPM versions, an error occurs in the portal. The exact nature of the error, as well as any error messages or warnings encountered, are as follows:
![image](https://github.com/ColoredCow/portal/assets/121417968/f576e72e-70d8-4736-9739-7c771d692441)

**Comment by GauravGusain98** [comment]
The issue looks fine, you can start working on it

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
