### ISSUE TITLE
Saving access token of campaign in the cache.

### ISSUE THREAD

**Issue by rajatsajwan** [ColoredCow/portal#3139]
**Description**
Currently, we are sending the request for the token to access the campaign application but now we have to save that token in cache for a certain time period when the time is over we have to resend a request for the access token again and save it for the certain time period in cache.

**Comment by pankaj-ag** [comment]
@rajatsajwan, let's not save the token in the DB. Let's store it in the cache. Laravel has beautiful support for caching. 
https://laravel.com/docs/8.x/cache#retrieve-store

You can add fetch token as a callback.
