### ISSUE TITLE
New fields for job

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#316]
**Description**
A job application may get closed after a particular date. There can be many reasons like no more vacancies or we're no longer hiring for that particular job description.
Right now, there is no way to hide that job field.

**Expected behavior**
When creating or editing a new job opportunity field, it should have two new date fields: `start_date` and `end_date`.

Add two new fields in the screen below
![image](https://user-images.githubusercontent.com/12053186/128664290-64797d37-8b28-4bbe-bf77-c43dd1e89628.png)

**Comment by srivastava-jyoti** [comment]
@rathorevaibhav Okay, I will take help from @am-Anmol for setting up the database configurations.
@kuldeep3 I have removed > in start_date and made the pull request and working on the first feature which you asked for.

**Comment by srivastava-jyoti** [comment]
@kuldeep3 This is how the page looks now.
![Screenshot (54)](https://user-images.githubusercontent.com/79009032/131243504-698efdf7-382f-4f3c-ba3b-0bdde3af33f8.png)

**Comment by rathorevaibhav** [comment]
@kickb71 please test this also.

**Comment by kickb71** [comment]
@rathorevaibhav I have tested it, I can see the date field, If I go into the job, I can see the start date and end date as well. 
But I can't edit the date it the start date is less than today's date.

**Comment by rathorevaibhav** [comment]
This is working fine. The dates are saving. I'll open another issue to show/hide from website
