### ISSUE TITLE
Remove the inactive team members and inactive or halted projects from email notifications

### ISSUE THREAD

**Issue by thisajaychauhan** [ColoredCow/portal#3164]
**Describe the task**
Currently, the cron job sends email notifications to the key account manager for inactive and active team members and inactive and active or halted projects. Its means that inactive team members and inactive or halted projects also receive email notifications, which is not needed.

**Expected behavior**
The expected behavior is that the cron job will send email notifications only to the key account manager for active projects and active team members. The filtering mechanism will exclude inactive team members and inactive or halted projects from receiving email notifications.

## Expected Time

- [ ] Set up the mail trap for email. `2-3 hours`
- [ ] Understand the bug. `3-4 hours`
- [ ] Understand the e-mail flow in Laravel. `2-3 hours`
- [ ] For testing, code review, and documentation. `1-2 hours`

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
