### ISSUE TITLE
Something went wrong error on direct route access

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#317]
@bohraji can you add more details and elaborate which route?

> Also, I saw that on directly accessing the route, I get a something went wrong error, instead of not allowed or redirecting to the home page with a message. Can you track that in a separate issue?

**Comment by bohraji** [comment]
@rathorevaibhav Here is screenshot of the URL and error encountered
<img width="1606" alt="screen shot 2018-05-30 at 14 02 03" src="https://user-images.githubusercontent.com/12884297/40708848-1d684c50-6412-11e8-8221-2c58abcdd197.png">

**Comment by bohraji** [comment]
The system should re-route me to the home page with a flash message.

**Comment by rathorevaibhav** [comment]
Agreed. This is `403 forbidden` response. Agree on re-route to the home page with a flash message.
