### ISSUE TITLE
Bug: Updation of working staff type

### ISSUE THREAD

**Issue by Bahugunajii** [ColoredCow/portal#3178]
**Describe the bug**
Super admins are not able to manage the working staff type for some users

**To Reproduce**
1. Go to Settings
2. Click on User Management
3. Click on the setting button of any user of whom you want to change the working staff type
4. Select the working staff type from dropdown and click the save button
5. The staff type will be changed for that employee (but it doesn't work for every employee)

**Expected behavior**
We need to fix this existing functionality in order to make it work for all users

**Comment by Ayush8923** [comment]
This issue is completed. Closing it.
