### ISSUE TITLE
Fix the alignment of Add New Post button header and close button on Media page in portal

### ISSUE THREAD

**Issue by ImRishabhRawat** [ColoredCow/portal#3183]
**Describe the bug**
On the portal's media page header of Add New Post button is not aligned with the Close button.

**To Reproduce**
1. Go to 'Media'
2. Click on 'Add New Post'
3. See error

**Screenshot**
<img width="1228" alt="Screenshot 2023-06-22 at 12 57 05 PM" src="https://github.com/ColoredCow/portal/assets/104312137/7cb99d20-0d55-43e9-8995-a363c2f79e73">

**Expected behavior**
The alignment of add new post header and the close button should be on the same level 

<img width="1274" alt="Screenshot 2023-06-22 at 2 04 29 PM" src="https://github.com/ColoredCow/portal/assets/104312137/e78ce028-0de2-4cf6-b33f-548bde851450">

Expected behavior should be like this , The header and the close button should on the same level

**Environment in which the issue is occurring**
- All environment

**Comment by GauravGusain98** [comment]
@ImRishabhRawat I am not able to understand the expected behaviour. You can also add a reference modal screenshot  from other pages according to which we can make changes to our current modal

**Comment by GauravGusain98** [comment]
As you are working on this issue so you also need to provide the breakdown of what all action items you will be doing to perform this task and how many hours you are expecting to complete it

**Comment by ImRishabhRawat** [comment]
**Expected Time**

- [ ] Align the close button  to the same level as Add New Post heading.  **30 min**
- [ ]  Remove the top blank card  and the outer card.  **1-2 Hour**
- [ ] For testing and code review  **2-3 hours**

**Comment by LavishRawat** [comment]
Closing the issue as it is completed.
