### ISSUE TITLE
Create a page to show all codetrek applicant's feedback 

### ISSUE THREAD

**Issue by thisajaychauhan** [ColoredCow/portal#3185]
**Describe the task**
Currently, we give feedback to applicants by selecting their names from the sidebar menu and saving it in our database. Now, we want to create a new page where we can display all the feedback received for a specific applicant. To make it organized, we plan to use an accordion-style layout for the feedback. Additionally, when we click on the feedback button, the new page should open and show the relevant feedback.

**Expected behavior**
We need to make a new page that shows all the feedback for a particular Codetrek applicant. The feedback will be displayed in a way that is easy to navigate, like an accordion. When we click on the feedback button, the new page will open and show us all the feedback given to the particular applicant.

- The image below shows an example of how the feedback button should look like.

![Screenshot 2023-06-22 161241](https://github.com/ColoredCow/portal/assets/120373044/bf4749bd-9056-48ec-a691-a162712271ca)

- Take accordion reference --> Codetrek module  -> click on evaluate button.

![Screenshot 2023-06-22 161814](https://github.com/ColoredCow/portal/assets/120373044/95f16fd4-2188-4239-90b9-3d1ef0b92a37)

- The accordion heading will contains - 
  - user name who give the feedback
  - feedback categories
  - feedback type 
  - date
  
- The accordion body will contains -
  - feedback
  

**References**
- Take database reference
  - code_trek_candidate_feedback

- Take feedback accordion UI reference [figma link](https://www.figma.com/file/9OBp2TdJvfb3uwj2x0peTK/feedback-accordion?type=design&node-id=0-1&mode=design&t=dF19jiWQJzn76EHE-0)

**Comment by GauravGusain98** [comment]
@Priyanka-Kaintura You can start working on this task. For this task you need to create a new branch from this branch `feature/3067/functionality-to-provide-feedbacks-to-codetrek-candidates`

**Comment by Priyanka-Kaintura** [comment]
> @Priyanka-Kaintura You can start working on this task. For this task you need to create a new branch from this branch `feature/3067/functionality-to-provide-feedbacks-to-codetrek-candidates`, as the PR related to this branch is not yet merged in master #3131

**Comment by Priyanka-Kaintura** [comment]
Breakdown of the Task: 
- [ ] Create function in controller and service file to fetch the data 
- [ ] Error Fix in data fetching
- [ ] Create the UI as per the expectation
- [ ]  Enhancement on UI
- [ ] Create a PR
- [ ] Work on further suggested changes

**Comment by GauravGusain98** [comment]
This has been deployed. Closing this now
