### ISSUE TITLE
Change the column name Status to Level

### ISSUE THREAD

**Issue by thisajaychauhan** [ColoredCow/portal#3187]
**Task Description**
Currently, in the codetrek module, there is a column called "status" that shows the levels of codetrek applicants. However, the name "status" doesn't clearly describe its purpose or what it represents.

**Expected Behavior**
To make it more understandable, we need to change the name of the "status" column in the codetrek module to "level". This will accurately reflect the information it contains, making it easier for users to comprehend.

![Screenshot 2023-06-22 161241](https://github.com/ColoredCow/portal/assets/120373044/075a7c9d-8d86-480b-8666-541eb27b6f8a)

**Comment by CYBWEBALI** [comment]
I can fix this issue Can you assign it to me.

**Comment by Ayush8923** [comment]
@CYBWEBALI I'm assigning this issue to you and once this issue is fixed then you can raise the PR of this issue.

**Comment by CYBWEBALI** [comment]
Done PR #3200 .
