### ISSUE TITLE
Add a dropdown menu for the status in the CodeTrek page

### ISSUE THREAD

**Issue by jaskaransingh304** [ColoredCow/portal#3197]
**Describe the task**

Currently, we are not getting a dropdown menu next to the status column in the applicants' table on the CodeTrek page, allowing us to filter applicants based on their status.
![image](https://github.com/ColoredCow/portal/assets/109968722/fe22a69f-c93a-48b1-beef-346f74eaea79)

**Expected behavior**
We need to add a dropdown menu next to the status column, clicking on which we can get all the options. Further, when we click on any level, we should get the same applicant list after filtering whose status is what we have chosen.

**References**

On the HR Recruitment page, there is a table called "Applications" that includes columns for "Name," "Details," "Assignee," and "Status." Next to the "Details," "Assignee," and "Status" columns, there are dropdown menus. Clicking these dropdown menus displays options for filtering the table based on the respective columns.

![image](https://github.com/ColoredCow/portal/assets/109968722/567ea7ff-3d33-4a7a-947e-a1b12aa02588)

**Comment by Ayush8923** [comment]
@jaskaransingh304 Expected behavior will be something like this. Please let me know, if there are any questions and confusion.
When we choose any status in the status dropdown, we should get the same applicant list after filtering whose status is what we have chosen.

**Comment by jaskaransingh304** [comment]
Thank You. I will surely ask if I face any issue.

**Comment by jaskaransingh304** [comment]
Breakdown-

Code review and documentation: 0.5-1 hour.
Understanding the functionality: 2-3 hours.
Making the required changes: 2-3 hours.
Testing, code, review, and documentation: 1 hour.

Expected Time =6-8 hours.

**Comment by GauravGusain98** [comment]
This has been deployed. Closing this now
