### ISSUE TITLE
Email and phone number formatting validation in CodeTrek module

### ISSUE THREAD

**Issue by Sachinbisht27** [ColoredCow/portal#3201]
**Is your feature request related to a problem? Please describe.**
In the `codetrek` module, While adding a new applicant right now the Phone Number and Email input field is receiving the non-formatted text.

**Right Now:**
![image](https://github.com/ColoredCow/portal/assets/96137915/92320675-6644-471c-b35d-85d6c67dc0f1)

**Describe the solution you'd like**
- The phone number field should receive only numbers not text (alphabets).
- The Email field should be filled only if the mail format is correct. Also, the message should appear as available in the screenshot.
![image](https://github.com/ColoredCow/portal/assets/96137915/89a1f313-368d-4142-b723-874c610c3315)

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by CYBWEBALI** [comment]
I can fix this issue assign it to me.

**Comment by GauravGusain98** [comment]
> I can fix this issue assign it to me.

Hi @CYBWEBALI I've assigned this task to you. Also is it possible for us to connect over email to explore further opportunities together as I see you are taking interest in open source projects? You can find my email in my profile.

**Comment by GauravGusain98** [comment]
This is not needed as we are doing the backend validation. Closing this
