### ISSUE TITLE
CodeTrek applicants not getting added to level 1

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#3204]
**Describe the bug**
Whenever we add a new applicant in the CodeTrek then ideally he should be in level 1 but there is some issue in the logic due to which the `latest_round_column` in the database does not get populated with the value level-1 due to which the applicant level is not set whenever we create a applicant entry

<img width="507" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/1487b8b2-569c-4489-a6d7-84aced802f97">

**To Reproduce**
1. Go to `CodeTrek` menu
2. Click on add applicant button
3. Fill the details and submit
4. In the applicant listing page the level will not be shown.  

**Expected behavior**
After adding a new applicant he/she should be added to level-1 of codetrek

**Comment by MohitGururani** [comment]
### Expected Time: 0.5-1 hour
### time taken: 1 hour
