### ISSUE TITLE
Add a bar chart in codetrek report page

### ISSUE THREAD

**Issue by thisajaychauhan** [ColoredCow/portal#3210]
**Task Description**
Currently, in the codetrek module, specifically in the `Reports` tab, there is a need to create a bar graph that visualizes the number of applicants added to the codetrek program on daily basis.
![image](https://github.com/ColoredCow/portal/assets/120373044/f1e619a2-ab9b-4a6b-8bd4-b2a801e2003a)

**Expected Behavior**
To address this requirement, our objective is to implement a bar graph that displays the number of applicants added to the codetrek per day. Each bar on the graph will represent a single day, allowing for clear visualization of the applicant intake over time. 

This enhancement will provide valuable insights into the applicant flow within the CodeTrek module and assist in tracking and analyzing the recruitment process effectively.

- The below image is just for reference.

![239968881-03f4af0f-90d8-4c34-a5a1-802578aebb89](https://github.com/ColoredCow/portal/assets/120373044/4e3ae5ff-0746-4bdc-9c30-c3bef4d85b3a)

**References**

**Comment by GauravGusain98** [comment]
This has been created and deployed
