### ISSUE TITLE
Assign a mentor to the codetrek candidates

### ISSUE THREAD

**Issue by thisajaychauhan** [ColoredCow/portal#3222]
**Describe the task**
In the codetrek module, there is an existing `feedback` column in the applicant list that is no longer necessary. Instead, the column needs to be renamed as `mentor assigned`.

![Screenshot 2023-06-27 113004](https://github.com/ColoredCow/portal/assets/120373044/c4eccb05-e489-4b58-b641-a36d5aef8353)

**Expected behavior**
The objective is to implement a functionality where, if a mentor is assigned to an applicant, the corresponding mentor's avatar will be displayed in the `mentor assigned` column. Additionally, when hovering over the avatar, the name of the assigned mentor should be displayed. This feature will provide a visual representation and easy identification of the assigned mentors in the applicant list.

**References**
- You can take reference from: CRM->projects

![image](https://github.com/ColoredCow/portal/assets/120373044/ca7ac9ee-6223-4b6d-b853-f52a831ba145)

**Comment by ImRishabhRawat** [comment]
**Expected Time**
1. Initially, I need to assess the portal and grasp the procedure, which would take around `0-1 hour`.
2. Subsequently, locating the file related to the CodeTrek page is required, which would also take approximately `0-1 hour`.
3. It will take approximately `3-4 hours` to comprehend the migration process and other Laravel concepts.
4. Finally, dedicating `3-4 hours` to implementing the necessary code updates.

**Total Time : 9-10 Hours**
