### ISSUE TITLE
Implement Button Logic for Tab Navigation in Codetrek 

### ISSUE THREAD

**Issue by LavishRawat** [ColoredCow/portal#3234]
**Describe the task**
The task involves implementing status and button logic for the tab navigation in the Codetrek Onboarding system. The system has three tabs: Active, Inactive, and Completed. Each tab has different behavior and available actions based on the applicant's status.

**Current Behavior**
Currently, the CodeTrek module consists of three tabs:

- Active
- Inactive
- Completed

**Screenshot**
<img width="1440" alt="Screenshot 2023-07-03 at 12 57 49 PM" src="https://github.com/ColoredCow/portal/assets/108713935/faf60173-0f9a-43e9-a5a5-7c4a9dd14371">

**Expected behavior**

**For  Active Tab**
**_When the status of an applicant is active then he/she -_**

1. Can be marked as inactive. 
2. If a candidate is in the onboarded round then we need to show a Start Internship button that will change the status of applicant to completed (Mark Completed Button will be changed to Start Internship)

**For InActive Tab**
 **_When the status of an applicant is inactive then he/she -_**
	
1. Can only be marked as Active.
2. The applicant can not be moved to another round if he/she is marked inactive.
3. Only the Mark Active button will be visible.

**For Completed Tab**
_**When the status of an applicant is completed then he/she -**_

1. Will not have any Buttons to change its status.
2. Only the Details of the applicant will be displayed on the card.

**Comment by Priyanka-Kaintura** [comment]
@LavishRawat Sir where are the buttons supposed to be? in the index page or somewhere else?

**Comment by Priyanka-Kaintura** [comment]
@LavishRawat Sir for some reason I'm unable to see the contents of the evaluate page other than the navigation bar. could you please suggest what could be the possible problems at my end. I have taken the most reason pull from /feature/3067/functionality-to-provide-feedbacks-to-codetrek-candidates

**Comment by LavishRawat** [comment]
@Priyanka-Kaintura could you please run the `php artisan optimize` command and then try again? let me know if this solves your problem.

**Comment by Priyanka-Kaintura** [comment]
@LavishRawat Sir, I tried the above suggested fix and it still does not work.

**Comment by Ayush8923** [comment]
@Priyanka-Kaintura Please check the `codeTrek_applicants_round_table`. In this table, store the round details corresponding to each candidate. If this data is empty corresponding to the candidate then the data is not coming because the `codetrek_applicant` table maps `codeTrek_applicants_round_table`. And please also check how this flow is working. Please let me know, it working or not?

**Comment by Priyanka-Kaintura** [comment]
ok sir

**Comment by Priyanka-Kaintura** [comment]
@LavishRawat @Ayush8923 Sir, From which branch should I create the new branch for this issue?

**Comment by Ayush8923** [comment]
@Priyanka-Kaintura Let's create the branch from `master`.

**Comment by GauravGusain98** [comment]
This has been deployed. Closing now
