### ISSUE TITLE
Display University Name in Codetrek Candidate Listing Page

### ISSUE THREAD

**Issue by suyashnautiyal** [ColoredCow/portal#3264]
Description:
Currently, the Codetrek candidate listing page only displays basic candidate information. We need to enhance the page by adding the university name of each candidate. This will provide more context about the candidates' educational background and help in evaluating their qualifications.

Tasks:

- Update the candidate model/schema to include a field for storing the university name.
- Modify the Codetrek candidate listing page template to include the new field for displaying the university name.
- Implement the necessary backend logic to retrieve the university name for each candidate and pass it to the front end.
- Update the frontend code to display the university name alongside the other candidate information.

To Reproduce

1. Go to Codetrek.
2. Add a new column next to the candidate's name
3. Implement the necessary backend logic.

![Screenshot from 2023-07-10 17-14-57](https://github.com/ColoredCow/portal/assets/138096316/96f982ca-7f2e-4c5a-a785-c31e99f7d9f7)

The new bar will look like:
![Screenshot from 2023-07-10 17-30-12](https://github.com/ColoredCow/portal/assets/138096316/c11cdc00-5a0c-4b76-9fc4-da74eecde978)

**Comment by GauravGusain98** [comment]
This is already fixed. Closing
