### ISSUE TITLE
Add a new round introductory call to the codetrek rounds 

### ISSUE THREAD

**Issue by Priyanka-Kaintura** [ColoredCow/portal#3266]
**Description of the task**
Right now, when a new applicant is added to codetrek, they are directly assigned to 'level 1'. We want to add a new round 'introductory call' in codetrek rounds. Now  when a new applicant is added to codetrek they will be assigned round 'introductory call'.

Need : When a candidate is at the 'introductory call' round, an interview can be scheduled for them (right now manually) and depending on the response during the interview the interviewer can move the applicant to 'level 1' or 'preperatory'

**Expected behavior**
Add a new round 'introductory call' to the 'codetrek applicant rounds'.
When a new applicant is added to the codetrek they should move to round 'introductory call' automatically.

**Comment by Priyanka-Kaintura** [comment]
Task Breakdown:

- [ ] Add a new round to the codtrek rounds
- [ ] Change the default round of the new applicant to 'introductory call'
- [ ] Make any other modifications related to the new round or any related change that happens.
- [ ] Test locally
- [ ] Create a pr
- [ ] Work on the feedbacks

**Comment by GauravGusain98** [comment]
This has been deployed. Closing this now
