### ISSUE TITLE
Getting error while accessing reports page

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#3307]
**Describe the bug**
Not able to see the report on the Portal.
Getting error when it opens the page.

**To Reproduce**
1. Go to Portal
2. Click on Reports sub menu link under Finance 
3. Scroll down to 'to see the report is not visible

**Expected behavior**
It should show the report.

**Screenshots**

<img width="1468" alt="Screenshot 2023-07-25 at 12 53 47 PM" src="https://github.com/ColoredCow/portal/assets/16541548/17e50bc8-4ba5-43c4-9d7e-2b2fb29e34d9">

**Comment by pankaj-ag** [comment]
This issue has been fixed. It was because of some changes in other modules. Check the discussion here. 
https://github.com/ColoredCow/portal/pull/3308#discussion_r1273215314

**Comment by pankaj-ag** [comment]
@mohitsharma-22 please take a look and close the task.

**Comment by mohitsharma-22** [comment]
@pankaj-ag Its working fine. Closing now.
