### ISSUE TITLE
Internship field

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#343]
Currently, we have three field – design, marketing, and engineering.

With the current internship applications, we cannot tell which field an application is there for. We can take two routes:
1. Either create different internships for each field
2. Add a field option in the internship applications

**Comment by rathorevaibhav** [comment]
@bohraji would require your opinion on this

**Comment by mohitgusain** [comment]
Which method will be better  @rathorevaibhav .

**Comment by rathorevaibhav** [comment]
@mohitgusain let me discuss the best route with the team. Will get back to you on this.

**Comment by mohitgusain** [comment]
Ok I will.

**Comment by rathorevaibhav** [comment]
This is complete. Closing.
