### ISSUE TITLE
Add ENV variable on portal's production environment.

### ISSUE THREAD

**Issue by Ashutosh6481** [ColoredCow/portal#3435]
**Describe the task**
ENV variables need to be added for the implementation of the solution mentioned in the issue #3417, on the production environment of the portal.
The variables need to be added are 

CITI_BANK_MESSAGE_PATTERN=
AXIS_BANK_MESSAGE_PATTERN=

**Comment by Satendra-SR** [comment]
@Ashutosh6481 please share the env variables with me over Google chat

**Comment by Satendra-SR** [comment]
Done with your request @Ashutosh6481 
Please close this ticket is things work as you expect.
