### ISSUE TITLE
Add a server side check for random book query

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#365]
Currently, we have added a check on the client side so that user can see the random book modal for the very first time. 

We need to add the same check on the server side also.

**Comment by rathorevaibhav** [comment]
@pankaj-ag please update the status label on this.

**Comment by abhishek-pokhriyal** [comment]
@pankaj-ag I am not clear about few things here:
1. Where is the server side check needed?
1. Is this the client clide check that you mentioned in the description?
`$unreadBook = (session('disable_book_suggestion')) ? null : Book::getRandomUnreadBook();`
