### ISSUE TITLE
Grading for college

### ISSUE THREAD

**Issue by bohraji** [ColoredCow/portal#479]
After #414 
With  college database, we need to have a grading of colleges also. The grading currently will be in the categories below-
- **A** - IIT/IIM
- **B** - NIT
- **C** - State Engineering Colleges / Good Private Universities (SNU/UPES)
- **D** - Unknown/Less known private colleges

**Comment by Satendra-SR** [comment]
#479
@bohraji 
 **According to my understanding**

There should be a field called `grading` or `college_grading` in `college` table and we should have some changes in **UI** also to store college grading.
Please elaborate it if _Anything else_ is required for this.

**Comment by bohraji** [comment]
@Satendra-SR Your understanding is correct. For starting, when we create a college database, we can assign the values based on the categorisation above. Then a section in the `settings>hr` tab will be present to adjust the ratings of the college.
Also, all new application should be mapped to the college listings.

**Comment by nishanth-kd** [comment]
Is anyone working on this? @Satendra-SR @bohraji

**Comment by Satendra-SR** [comment]
No @nishanth-kd,
actually, it was assigned to me but now I'm working on the Finance module. so I left it.
