### ISSUE TITLE
Option to add new project stage from invoice create screen

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#546]
An invoice is required to be attached to a billing in a project stage. The user goes to invoice create screen then realizes he has to create a project stage first for which he has to go all the way to project screen and then comes back to the invoice create screen.

How fast would it be if there's an option to create a project stage from the invoice screen only? 🚀 🚀

**Comment by Satendra-SR** [comment]
This needs to be stored through ajax so that the data may not be lost.
I have created a new issue #607  to implement that first and then after I will do this one.
