### ISSUE TITLE
Multi tenant- testing enhancement - Remove dependancy from the Tenant service provider

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#561]
![image](https://user-images.githubusercontent.com/10670690/42573215-18ef40fa-8539-11e8-96c8-bc541108ba6b.png)

Sometimes Travis gives an error in testing. We need to figure out the cause of this issue. 
For now, I have fixed that by adding an extra check to the Tenant service provider.

**Comment by rathorevaibhav** [comment]
No longer pursuing this. Closing.
