### ISSUE TITLE
Test cases for no-show functionality

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#603]

**Comment by mohitgusain** [comment]
@pankaj-ag. Please if any description. What could be the test cases for no-show?

**Comment by pankaj-ag** [comment]
Sharing a pseudo-algorithm for this. 

1.    create a job
2.    create an applicant for the job
3.    set his status as pending 
4.    set his schedule date 2 hours ago 
5.    call artisan command for moving it to no-show
6.    check applicant status is no-show
