### ISSUE TITLE
Front end validation not working in invoice paid amount

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#611]
In reference to: https://github.com/ColoredCow/employee-portal/pull/550#issuecomment-407661145

**Comment by rathorevaibhav** [comment]
@Satendra-SR I was checking from the invoice create screen, not from project billing screen.

**Comment by dsajwan2020** [comment]
This issue has been fixed. If we try to save invoice without entering **Received Amount**, there is a check which asks user to  **Please fill out this field**. 
Please refer the following screenshot
![image](https://user-images.githubusercontent.com/96309135/161513281-7a822fa8-736d-4398-a7ba-9ee7b99dcb92.png)
