### ISSUE TITLE
missing authorization when not super-admin

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [ColoredCow/portal#626]
The UI for `super-admin` was designed with the assumption that users cannot be given permissions directly rather permission will be given to the role and that role will be assigned to the user.

This works for now but will be a (serious) security issue in future when permissions are granted directly to a user.

See this comment for some reference: https://github.com/ColoredCow/employee-portal/pull/597#issuecomment-408334725

**Comment by abhishek-pokhriyal** [comment]
@rathorevaibhav Does this issue make sense? If we'll never assign permission directly to the user then what's the point?

**Comment by abhishek-pokhriyal** [comment]
@rathorevaibhav I checked and found only super-admin was able to access the roles and permissions. Please have a look at it. Maybe I am missing something.

**Comment by rathorevaibhav** [comment]
This looks complete and implemented. Closing.
