### ISSUE TITLE
Send offer letter to applicant after application approval

### ISSUE THREAD

**Issue by pokhiii** [ColoredCow/portal#671]
Requirements: 
- [x] When _user A_ select `sends for approval`, it is required for _user A_ to upload an offer letter and select someone to approve the application.
- [x] A mail is sent to the person who was requested for approval (mail contains a link to that particular application) when _user A_ requests for approval
- [x] When the approver clicks the link it takes it to that particular application.  
- [x] When the approver selects the `Approve` action, a modal pops up which shows the offer letter that was earlier uploaded by _user A_
- [ ] When the approvers clicks on `Confirm`, a mail is sent to the applicant with the offer letter attached to it

The following workflow is complete
- [x] When a user directly approves, that is, without sending for approval, an option to upload offer letter appears (which is a required field) and when clicks on confirm button a mail is sent to the applicant with the offer letter attached to it.

**Comment by abhishek-pokhriyal** [comment]
@rathorevaibhav could you please verify that we aren't missing anything here in the requirements?

**Comment by vikasrinvi** [comment]
@bohraji  have a look on this issue and let us know if you have any feedback on this.
