### ISSUE TITLE
ApplicationRound - Model and Controller logic should be separated

### ISSUE THREAD

**Issue by mohitgusain** [ColoredCow/portal#692]
- [x] Model Application round logic should be in the controller.

- [ ] Onboard create user logic should be in Event Listener /Model Observer.

**Comment by abhishek-pokhriyal** [comment]
@Satendra-SR @vikasrinvi @mohitgusain This looks way too much complicated. Looking at the code, I've no clue how to proceed. A lot of code is written in `ApplicationRound` model (which, ideally, should not be there) changing which may affect (break) the functionality in other places. I'll need to discuss this @rathorevaibhav before taking any decision. Putting this on-hold for now.

**Comment by vikasrinvi** [comment]
@abhishek-pokhriyal so when you targeting this discussion?
