### ISSUE TITLE
Application dashboard tabs resets the job id filter when clicked

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#792]
**Describe the bug**
Currently, users can filter all the applications from the HR > opportunities tab. It takes the user to applications dashboard filtered by job id. By default the "Open" applications tab is active.

However, when you switch the tab to another status "On Hold" or "Closed", the job filter resets and you see applications for all jobs.

**Steps to replicate**
1. Login and click on HR > Recruitment.
2. Click on the `Opportunities` tab.
3. Click on any job which has an application. Click on `view application`.
4. Click on the `Closed` status.
5. You will see the job filter resets and it shows all the closed applications

For more info, check out screenshots from comment below https://github.com/ColoredCow-Portal/portal/issues/133#issuecomment-862952321

**Comment by rathorevaibhav** [comment]
This works fine.
