### ISSUE TITLE
Job add "domain" field

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#793]
**Describe the task**
We need to capture a new field called "domain" for a job that will allow us to make better data analytics and reporting.

**Expected behavior**
In the form to create a new job or when editing a job, there should be a new field labeled "Domain" that will be a select field. It will have these options:
1. Engineering
2. Design
3. Marketing

**Comment by rathorevaibhav** [comment]
@am-Anmol when I update the domain field, it deletes the job and shows a message saying `job_name deleted successfully`. Please check. I'm testing on UAT

**Comment by am-Anmol** [comment]
@rathorevaibhav This is a bug that is coming before adding the `domain field` and that's why I have created issue #845 for it.

**Comment by rathorevaibhav** [comment]
This looks good on UAT. Closing.
