### ISSUE TITLE
New job opportunity should get created on ColoredCow website also

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#794]
**Describe the task**
Currently, we have separate mechanisms to create an entry on the career page on the website and work opportunities in ColoredCow Portal. When a new opportunity is created on the portal, it doesn't get created on the website.

**Expected behavior**
- [x] When a new `JOB` type opportunity is created on Portal, a new post type for career should also be created in website.
- [x] The opportunity should also be updated or deleted at website, if same action happens at Portal.

**Note:** This task will require both Portal and website setup.

**References**
Check out the Corcel package to easily create entries in the WordPress database from Laravel
https://github.com/corcel/corcel

**Comment by am-Anmol** [comment]
@GauravGusain98 
Can you please share steps to replicate for `Draft jobs are still showing in website` because I'm unable to do so?

**Comment by GauravGusain98** [comment]
This is a job in uat for software developer fresher, which is in draft state
![image](https://user-images.githubusercontent.com/54376313/131288286-fa6eedc0-0e15-4d16-a416-8af91681dcc9.png)


But I still see the job in the website 
![image](https://user-images.githubusercontent.com/54376313/131288365-3e5478b6-0404-47ff-a6a4-026ca29c81d2.png)

**Comment by GauravGusain98** [comment]
Also, I tried to make a job published but was not able to see that on the website
![image](https://user-images.githubusercontent.com/54376313/131288596-5a5615f5-4f97-4431-ada7-36949d80babd.png)

![image](https://user-images.githubusercontent.com/54376313/131288626-55fcb78e-8438-4bde-8822-6a043936c58a.png)

**Comment by rathorevaibhav** [comment]
@srivastava-jyoti please test this one also.

**Comment by srivastava-jyoti** [comment]
@rathorevaibhav I have tested this. It is working fine on UAT. Drafts and closed ones are not showing on the UAT of the main website. Only Published ones are visible.

**Comment by rathorevaibhav** [comment]
This is working great! Great work @am-Anmol 👏
