### ISSUE TITLE
Rename conversion rate to conversion rate diff in the invoice module. 

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#797]
**Describe the bug**
We have a typo in the conversion rate, it should be conversion rate diff. 

**Expected behavior**
1. Rename label from Conversion rate to conversion rate diff
2. Rename database column from conversion_rate to conversion_rate_diff
3. Update the invoice modal column as well.

**Screenshots**
<img width="1031" alt="Screenshot 2021-07-16 at 12 14 20 PM" src="https://user-images.githubusercontent.com/10670690/125904112-a5b98dab-85b6-4c23-b74e-485dd17d21fc.png">

**Comment by mohitsharma-22** [comment]
@rathorevaibhav Label name is changed.
<img width="1107" alt="Screenshot 2021-07-31 at 7 39 54 PM" src="https://user-images.githubusercontent.com/16541548/127742483-3a662b2a-5dfe-4f28-8fb0-3d1eaa153117.png">
