### ISSUE TITLE
Reporting - Daily new applications

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#810]
**Describe the task**
We need a new dashboard (page or section) within the HR module to show the analytical data. This will be visible to only super-admins and HR admins.

**Expected behavior**
A clear and concise design for the HR analytics dashboard. The basic use case would be to show a report that displays daily new applications.
Some suggestions that the design team may consider:
1. Graph (line or bar) that shows the count of new applications
2. By default it can be past 7 days but there can be an option to increase/decrease the report duration.
3. There may be more options like showing daily new applications based on college or job profile. Maybe in the future.

Design team to share the link for design files.

**Comment by vishalkumarcc** [comment]
PRD for the project: https://docs.google.com/document/d/170KT7y7_venU_uF1lpKnTJbXjj4qOu3Qk22q-pfsMtk/edit?usp=sharing

**Comment by vishalkumarcc** [comment]
Prototype link: https://www.figma.com/proto/ZjX8ogSM5yrZGhvO5vEWJn/Employee-Portal?page-id=0%3A1&node-id=353%3A97&viewport=356%2C-1133%2C0.17737901210784912&scaling=min-zoom&starting-point-node-id=353%3A97

**Comment by vishalkumarcc** [comment]
Design file link: https://www.figma.com/file/ZjX8ogSM5yrZGhvO5vEWJn/Employee-Portal?node-id=0%3A1

**Comment by rathorevaibhav** [comment]
This looks great 🎉
