### ISSUE TITLE
Dashboard to view daily job applications

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#811]
**Describe the task**
We need a dashboard to show daily new job applications.

**Expected behavior**
- [x] SQL Query to fetch daily job applications
- [x] Use a graph library to show a bar-graph
- [x] By default it will show for the past 7 days. But there will be a filter to adjust the report duration and graph should update.

**References**
Designs to be worked on in ColoredCow/portal#810

**Comment by kickb71** [comment]
Changes need to be  done
Change the bar to vertical 
Make the file code file smaller
Center align
Dates format To date should be less than From date

**Comment by rathorevaibhav** [comment]
@kickb71 here are the design files:
1. [Prototype](https://www.figma.com/proto/ZjX8ogSM5yrZGhvO5vEWJn/Employee-Portal?page-id=0%3A1&node-id=409%3A461&viewport=356%2C-1133%2C0.17737901210784912&scaling=min-zoom&starting-point-node-id=353%3A97)
2. [Design guide](https://www.figma.com/file/ZjX8ogSM5yrZGhvO5vEWJn/Employee-Portal?node-id=0%3A1)

Please make sure you build the basic functionality and finish this. The download option, filter by option and other graphs can be worked on later as a separate issue.

**Comment by srivastava-jyoti** [comment]
@rathorevaibhav & @kickb71 while testing this I am getting this error on clicking view button.
![Screenshot (74)](https://user-images.githubusercontent.com/79009032/132021578-b9db9c84-5162-417d-8f49-db3650b1915e.png)

**Comment by rathorevaibhav** [comment]
There are some updates required here but I think we can close this. Will target separately in #943
