### ISSUE TITLE
Allow finance user to add the current usd rates when we receive a payment. 

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#814]
**Is your feature request related to a problem? Please describe.**
We want to capture the USD -> RS rates we received from the bank when we get the payment. It will help us to get the total amount in rupees when we do the calculations. 

**Describe the solution you'd like**
1. Add one column in the invoice table with name conversion_rate. It will take a float value & can be nullable.
2. It will be visible when the invoice payment is international

**Comment by mohitsharma-22** [comment]
@rathorevaibhav Is this fix updated on UAT? Are there any form fields updated for this? Or this is only updated in DB for calculations?

**Comment by rathorevaibhav** [comment]
@mohitsharma-22 this is related to the conversion rate field. If you can test that is working fine, then we can close this.

**Comment by rathorevaibhav** [comment]
@pankaj-ag any thoughts on this?

**Comment by pankaj-ag** [comment]
@mohitsharma-22 now you should see two columns. 

conversation rate diff
and conversation rate

**Comment by mohitsharma-22** [comment]
@pankaj-ag Currently it showing only one column.

<img width="1042" alt="Screenshot 2021-09-14 at 1 50 25 PM" src="https://user-images.githubusercontent.com/16541548/133222411-bc29e4a6-9637-4657-a914-c270745886c0.png">
