### ISSUE TITLE
"Repeat slot till" option does not show up on recurrence option select

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#815]
**Describe the task**
When we select an option from the recurrence dropdown, the repeat slots option do not show up. It starts showing up when you click on the recurrence dropdown again.
![image](https://user-images.githubusercontent.com/12053186/94342854-afeeea80-0031-11eb-91e6-3644674d2498.png)

**Expected behavior**
The repeat slot option should show immediately when a valid option in recurrence.

**Steps to replicate**
1. Go to Dashboard
2. Select AppointmentSLots from HR dropdown
3. Click on any cell in the calendar to open the create appointment slot
4. Select weekly from the dropdown
5. You will notice that nothing happens. But if you click on dropdown again, the "repeat slots" field starts showing up

**Comment by srivastava-jyoti** [comment]
Closing.
