### ISSUE TITLE
Applicants universities mapping

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#822]
**Describe the task**
We need to link applicants with universities so that we can add filters to the application listing based on university. These filters will be helpful for evaluation and campaigning.

**Expected behavior**
1. Seed the current distinct colleges we have in the production database into universities table.
2. Add university_id into applicants table
3. Write a script that matches university name from applicants table and assigns university_id
4. We will keep the current college field as it is. For new applications, there should be an option in the UI for admins to select university from dropdown.

**Comment by P4NK4J** [comment]
Closing this issue, since it is completed and deployed on the production
