### ISSUE TITLE
Option to assign/remove labels to an application

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#831]
**Describe the task**
We need to tag applications with labels for easy sorting and finding.

**Expected behavior**
In the application listing screen (both job and internship), there should be an option to add labels to an application.

1. In every row, show a three-dot icon before the applicant name that will open a dropdown. The dropdown will only have one option right now which would be "Assign labels"
2. When clicking on assign labels, it should open a modal that will have the functionality to select/unselect labels as checkbox.
3. On clicking on the save option inside the modal, the page reloads with updated labels for that application.

**References**
Similar to how GitHub allows option to assign/remove labels for an issue/PR.

**Comment by srivastava-jyoti** [comment]
Closing.
