### ISSUE TITLE
User-specific maximum appointments per day

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [ColoredCow/portal#836]
**Is your feature request related to a problem? Please describe.**
The user should be able to specify the maximum number of appointments she would like to have.

**Describe the solution you'd like**
Right now the maximum number of appointments a user can have in a day is 3. This is value is defined in the `config` and is constant among all the users.

**Solution**
1. Create a new table `user_meta`
2. A meta key called `max_appointments_per_day` will store the max number of appointments
3. Update the code here to first read from `user_meta` and then fall back to config value https://github.com/ColoredCow/portal/blob/3f5b1ce2dab23d7f93354a75f1cd447e7f2d8875/Modules/AppointmentSlots/Services/AppointmentSlotsService.php#L216

**Describe alternatives you've considered**
Calling the person and rescheduling!

**Additional context**
@rathorevaibhav shared that 3 appointments in a day sometimes becomes too much. So, it'd be nice if he has the ability to control these.

**Comment by rathorevaibhav** [comment]
This works great. @srivastava-jyoti great work!
