### ISSUE TITLE
Send reminder email from Employee portal.

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#839]
Ability to send an invoice reminder email to the client from Portal.
Give a button "Send email" next to each pending invoice.
It should open a modal (like in the HR module, to send emails for interviews), with the content prepopulated in it.

- Give the option to add more email addresses in CC.
- Give the option to edit the content if needed.
- Send the button from the model to send the emails.
- Sender's email address should be "finance@coloredcow.com"
- An option to check if the email id sent or not. It will be good if it can be saved in sent items of sender's email account like "mohit@coloredcow.com" (which should be editable, so that it can be changed if required.)

**Comment by mohitsharma-22** [comment]
@dsajwan2020 The issue is not fully fixed. Please fix the pending items in it.

1. I am not able to see the modal with the email content.
2. I didn't find the email in my sent email box.

**Comment by GauravGusain98** [comment]
This is completed
