### ISSUE TITLE
Monthly invoice details page.

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#840]
Please create a page, which tell the below details of all the invoices for a particular month. 
We can change the month and year from the dropdown to get the data of a particular month.
Export to Excel link would be there to download the excel of the page.

**Domestic Invoices**

- Project 
- Invoice amount
- Invoice Amount with GST
- Amount received
- GST Amount
- TDS Amount
- Sent on
- Payment received on
- Total of each column

**Internaltional invocies**

- Project
- Invoice amount 
- Amount received
- Bank charges
- Dollar rate
- Exchange rate difference
- Sent on
- Payment received on
- Total of each column

**Comment by pankaj-ag** [comment]
@abhinav80066 we need to update the column formatting for Indian and international payments.

**Comment by dsajwan2020** [comment]
There are some additional requirement in this feature request

- The naming convention of the Excel file that is exported should be in following naming convention
   TaxReport-Region-Month-Year  for example if Region is India then Report naming convention TaxReport-India-06-2021
 
-  TaxReport excel file should also display total of following column 
    Amount 
    Received amount 
    Amount (+GST) 
    GST 
    TDS
-

**Comment by mohitsharma-22** [comment]
@pankaj-ag Is this done. I am closing it now.
