### ISSUE TITLE
Invoices details client wise

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#841]
Please create a page, which tells the below details of all the invoices of a client.
Select the client from a drop-down.

Yearly break up of invoices (Year start from April and ends in March).
Please provide the Export to Excel for this page.

**Indian client**
Client name.
- Project name
- Invoice number
- Invoice amount
- GST amount
- TDS amount
- Amount received.
- Sent on date
- Payment date
Total Yearly
Grand total at the end.

**For international clients.**
Client name.
- Project name
- Invoice number
- Invoice amount
- Bank charges
- Dollar rate
- Exchange rate difference
- Amount received in Dollars.
- Amount in INR
- Sent on date
- Payment date
- Total Yearly
Grand total at the end.

**Comment by rathorevaibhav** [comment]
Details from #885 
```
Add functionality to get invoice-related data of a client.
Please add a drop-down to filter the data for a specific date range.
Add functionality to export the data in excel

Fileds required in the report

Client / Project Name:
Date Range - 1st April 2021 to 31st March 2022
Invoice Date| Invoice Number| Amount | GST | Amount (+GST) | Received amount | TDS | Sent at | Payment at | Status.
```

**Comment by rathorevaibhav** [comment]
Add a new filter here with options for:
1. All clients
2. Every client
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/12053186/160598520-fa83ad31-2edd-44a3-9bdd-f06f192703e7.png">


The options in the client field should be sorted by client name alphabetically ascending order

**Comment by deepankar-sajwan** [comment]
When report is exported from Export to Excel button the naming convention of the File which  is exported will be Clientname-FinancialYear-TaxReport for example clientname is Bigtech ,Financial year 2020-2021so file name will be 
Bigtech-2020-2021-TaxReport

**Comment by P4NK4J** [comment]
@Himanshunegi0332 Why you closed this issue? Is there any specific reason ?

**Comment by Himanshunegi0332** [comment]
Sorry sir, it was done by mistake.
