### ISSUE TITLE
Opportunity delete when we update any field 

### ISSUE THREAD

**Issue by am-Anmol** [ColoredCow/portal#845]
**Describe the bug**
In Opportunities Tab, while updating any opportunity details (like Job title, status, type, Job Description) it deletes this opportunity but ideally, it should update details.

**Steps to replicate**
1. Login and click on HR > Recruitment.
2. Click on the `Opportunities` tab.
3. Click on any Opportunity.
4. Then update any field `Job title`, `status`, `type`, `Job Description` and click on the `Update` button.
5. You will see the opportunity got deleted.

**Expected behavior**
It should update opportunity details.

**Screenshots**
![image](https://user-images.githubusercontent.com/48876126/126684579-56e57c64-d7b8-4f18-832a-a75227527865.png)

**Comment by rathorevaibhav** [comment]
@am-Anmol this is not working on UAT. I changed the domain for a job opportunity and it got deleted after I update it.

**Comment by rathorevaibhav** [comment]
This is working great on UAT. Thanks and great work @am-Anmol 👏
