### ISSUE TITLE
Artisan route cache command throws an error

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#848]
**Describe the task**
When running the command `php artisan route:cache`, it results in an error
![image](https://user-images.githubusercontent.com/12053186/126778397-39d62b83-e97f-4ffd-96a8-49e922bf3ece.png)

**Expected behavior**
The command should work fine without any errors.

**References**
https://laravel.com/docs/8.x/deployment#optimizing-route-loading

**Comment by rathorevaibhav** [comment]
This works great. @kickb71 thanks!

**Comment by kickb71** [comment]
No problem sir!
