### ISSUE TITLE
Update pre-requisites

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#858]
**Describe the task**
While setting up project with WAMP, openssl PHP extension gave some errors.

**Expected behavior**
- [ ] Update pre-requisites file with WAMP installation and configuration steps.

**Comment by RohitDhingra27** [comment]
WAMP uses different php.ini files in the CLI and for Apache. When we enable php_openssl through the WAMP UI, we enable it for Apache, not for the CLI. We need to modify,
C:\wamp\bin\php\php-X.Y.Z\php.ini,  to enable it for the CLI.
Also check whether the terminal have access to  php.ini that is being loaded.

 In php.ini, we need to uncomment the  ";extension=openssl" by removing ";" before it and then restart the apache services.
@rathorevaibhav
