### ISSUE TITLE
Project module schema

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [ColoredCow/portal#881]
**Describe the task**

1. Rename `project_resource` table to `project_resources`
2. This won't be needed then
   https://github.com/ColoredCow/portal/blob/fbc7429b63efb9622a4de44657280808bdfae1d1/Modules/Project/Entities/ProjectResource.php#L10
3. Add foreign key constraints for
   1. `project_id` ---- `id` on table `projects`
   2. `resource_id` ---- `id` on table `users`

**Expected behavior**
A clear and concise description of what needs to be done.

**References**
Specify any reference material / links

**Comment by wevekamola** [comment]
@rathorevaibhav Verified this change from the UAT DB structure. Good to close 👍 

![image](https://user-images.githubusercontent.com/29367838/131219683-92782f79-c3f2-4fa7-9bc5-54752e566b61.png)

**Comment by rathorevaibhav** [comment]
Thanks. Closing.
