### ISSUE TITLE
Project designations are limited

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [ColoredCow/portal#882]
**Is your feature request related to a problem? Please describe.**
I was adding `Mohit Sharma` to the `Glific` project but there was no suitable designation.

**Describe the solution you'd like**
Two solutions I can suggest:
1. Either add more designations like `QA`
2. Give an option for the project manager to add more designations as required

**Comment by rathorevaibhav** [comment]
@bohraji can you add the designations that need to be in the system? Please modify the issue description accordingly.

I think can skip the dynamically creating designations feature for now.

**Comment by rathorevaibhav** [comment]
This seems like not needed. Closing.

**Comment by rathorevaibhav** [comment]
@abhishek-pokhriyal please re-open in case you see this needs some work.
