### ISSUE TITLE
Consolidated invoice data report for a specific client.

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#885]
Add functionality to get invoice-related data of a client.
Please add a drop-down to filter the data for a specific date range.
Add functionality to export the data in excel

Fileds required in the report

Client / Project Name:
Date Range - 1st April 2021 to 31st March 2022
Invoice Date| Invoice Number| Amount | GST | Amount (+GST) | Received amount | TDS | Sent at | Payment at | Status.

**Comment by mohitsharma-22** [comment]
Please check more details for it at https://github.com/ColoredCow/portal/issues/841

**Comment by rathorevaibhav** [comment]
Closing this. Taking forward in #841
