### ISSUE TITLE
Project detail page to have project repository section

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#891]
**Describe the task**
In the project detail page, we need to add a new section same as "Project resources" section. This new section should contain the information about the project github repositories.
![image](https://user-images.githubusercontent.com/12053186/129522044-79a59392-bae6-44d6-aa30-36d0a3ae8bd4.png)

**Expected behavior**
There should be:
- [x] A new section where user can add one or more repository links. The section title should be "Project repositories".
- [x] The repository link field will be a simple URL form field
- [x] When on save and update, the repository links should be saved accordingly for the project

**References**
To reach to project detail screen:
1. Go to "Project management" dropdown at the top navbar and select project
2. If there are no projects, create one
3. Click on the project name to reach the project detail screen

**Comment by kickb71** [comment]
Tested on UAT

**Comment by rathorevaibhav** [comment]
@kickb71 can you share what exactly did you test here? It doesn't seem to be working for me at all.

**Comment by kickb71** [comment]
@rathorevaibhav The textbox to enter the data is working perfectly. But the data is not submitting

**Comment by rathorevaibhav** [comment]
This is working fine now. Closing.
