### ISSUE TITLE
Job application dashboard - New UI for Application Status tabs

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#912]
**Describe the task**
Create the new UI for the application status tabs based on the designs
- [Prototype link](https://www.figma.com/proto/ZjX8ogSM5yrZGhvO5vEWJn/Employee-Portal?page-id=0%3A1&node-id=615%3A2&viewport=241%2C48%2C0.28&scaling=min-zoom&starting-point-node-id=615%3A2)
- [Design file link](https://www.figma.com/file/ZjX8ogSM5yrZGhvO5vEWJn/Employee-Portal?node-id=615%3A2)

**Expected behavior**
- [ ] The application status tabs should look the same as the new designs
![image](https://user-images.githubusercontent.com/12053186/130974524-e5348c6f-aa5d-4f11-b3eb-3ff3d247a621.png)

**References**
1. For more details on the task, check out #809 
2. For now, use the font-awesome v4.7 icons that are being used at the other places

**Comment by srivastava-jyoti** [comment]
@vishalkumarcc for closed tag & to import excel fie the designs are missing. Can you please include them in the design fie??

**Comment by vishalkumarcc** [comment]
Sure I'll update the design files and let you know when it's done.

**Comment by vishalkumarcc** [comment]
The closed applications will be accessible from filter section. The screens are there in the design file. Let me know if you can't find it.
![image](https://user-images.githubusercontent.com/86099784/133189271-bf01701a-3fad-42d5-bf16-72e250f716e4.png)

**Comment by vishalkumarcc** [comment]
The project was focused only on the "status tabs" so I didn't design screens for importing excel files. @rathorevaibhav should I design screens for this "excel file" interaction?

**Comment by rathorevaibhav** [comment]
@srivastava-jyoti everything looks good. Just two issues I noticed:
1. When I click on "Trial Program", it says count is 1 but shows many applications. I think the link for that tab is not right. It should be this: `https://uat.employee.coloredcow.com/hr/recruitment/job?status=in-progress&round=Trial-Program`
2. There is a blue outline when I click on the tab item. It shouldn't come.
![image](https://user-images.githubusercontent.com/12053186/134773548-097adcea-a607-4c99-848f-a90ae4692a48.png)
