### ISSUE TITLE
Removing resource from project is not working

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#913]
**Describe the bug**
When removing a resource from the project, nothing is happening. We are getting an error in the network tab. The screenshot is attached below.

**To Reproduce**
1. Go to the project page
2. Click on any project
3. In the resources tab remove a resource 
4. Check the error in the network tab by inspecting the page

**Expected behavior**
Removing a resource should remove the resource from the project

**Screenshots**
![image](https://user-images.githubusercontent.com/54376313/131003243-4304eca9-3a71-4aec-8fe3-8d9a6b6c4b55.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
NA

**Comment by rathorevaibhav** [comment]
This is working fine. Closing.
