### ISSUE TITLE
Undefined Index on invoices page

### ISSUE THREAD

**Issue by gaurish-saini** [ColoredCow/portal#923]
**Describe the bug**
While we visit the invoice page it shows the following error:

**To Reproduce**
1. Go to Finance tab from navbar
2. Click on `Invoices` from the dropdown.
4. See an error

**Expected behavior**
There should not be any error, clicking on the invoices tab should directly take to the Invoices page.

**Screenshots**
![image](https://user-images.githubusercontent.com/58362095/131449151-f03780f7-a51f-47fe-b484-a4ef5d62b637.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rathorevaibhav** [comment]
This task is complete. Closing.
