### ISSUE TITLE
Code editor setup in pre-requisites

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#927]
**Describe the task**
To maintain consistent formatting and standards of code in Employee Portal, we need to add several extensions in the code editor

**Expected behavior**
Inside the pre-requisites file, create an action item to set up the following extensions in code editors.
1. **Sublime Code Editor:**
        -  PHP formatting - PHPfmt
        - Laravel Blade Snippets for Balde files
        - Prettier - for JS,CSS,HTML files

2. **Visual Studio Code Editor:**
        - Prettier - for JS,CSS,HTML
        - Blade Files - for Laravel Blade Snippets
        - Laravel Extra Intellisense
        - PHP Intelephense
        - PHP cs fixer

**Comment by rathorevaibhav** [comment]
Looks good. Closing.
