### ISSUE TITLE
UAT (latest master) color theme is missing

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#938]
**Describe the task**
The color theme seems to be missing
![image](https://user-images.githubusercontent.com/12053186/131854316-a512c31d-c723-40e4-916f-ef8269214881.png)

**Expected behavior**
- [x] The color theme should work fine

**Comment by kickb71** [comment]
This issues is resolved and ready to test

**Comment by rathorevaibhav** [comment]
This is complete.
