### ISSUE TITLE
Add new fields in the project add screen.

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/portal#948]
- Update Project table with columns as mentioned in the screenshot
<img width="1011" alt="Screenshot 2021-09-16 at 12 47 09 PM" src="https://user-images.githubusercontent.com/40158831/133567580-b848c275-4d6f-4003-b128-9a1289e4316b.png">

- Add UI to update project details

**Comment by GauravGusain98** [comment]
@AkhileshNegi Can you please test this feature on UAT.

**Comment by AkhileshNegi** [comment]
@GauravGusain98 I have tested it in UAT from my end
