### ISSUE TITLE
Distinguish paid invoices with green color text 

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#952]
Change the color to Green for Paid invoices in **Invoices** and **Monthly Tax report** pages 

Make the Paid status green.

<img width="1091" alt="Screenshot 2021-09-10 at 11 37 49 AM" src="https://user-images.githubusercontent.com/16541548/132808251-00cd7933-26c5-48f9-a4b1-1f4489951cf2.png">

**Comment by srivastava-jyoti** [comment]
@rathorevaibhav this is also working fine. Paid invoices and paid monthly tax reports are of green color.

**Comment by mohitsharma-22** [comment]
@rathorevaibhav this is working fine.

<img width="1114" alt="Screenshot 2021-09-25 at 5 03 14 PM" src="https://user-images.githubusercontent.com/16541548/134770021-f531bab3-87cf-488a-bc82-1f6ba724947e.png">
