### ISSUE TITLE
Remove the currency signs from excel downloaded from monthly tax reports.

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#954]
**Describe the bug**
Signs are making these values text and to make a total, I need to remove the signs manually. 

<img width="913" alt="Screenshot 2021-09-10 at 7 22 51 PM" src="https://user-images.githubusercontent.com/16541548/132869754-c6bf4f5b-4006-4b5b-a2a7-62f7357400e3.png">

**Comment by srivastava-jyoti** [comment]
@rathorevaibhav this is working fine. Currency symbols are not shown in downloaded excel sheet.

**Comment by mohitsharma-22** [comment]
@rathorevaibhav it is working fine.
<img width="872" alt="Screenshot 2021-09-25 at 4 43 53 PM" src="https://user-images.githubusercontent.com/16541548/134769458-b0cafb8e-db3e-4af4-b523-4a9bb5c03739.png">
.
