### ISSUE TITLE
Please correct international monthly tax reports columns.

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#955]
**Describe the bug**
The Table header is the same as the Indian tax report. 
It should be different  as per the values in the invoices creation and payment fields.

**Remove** 
1. GST column
2. Remove TDS Column
3. No need to show the Amount (+GST) column.

**Add**
1. Amount Received in $
2. Bank charges column.
3. Currency conversion rate column.
4. Currency conversion difference Column.
4. Invoice Amount in the INR column. 
5. Amount received in INR

<img width="1189" alt="Screenshot 2021-09-10 at 7 26 29 PM" src="https://user-images.githubusercontent.com/16541548/132871239-4d808444-0ec2-48f9-9aa3-9164419b4367.png">

<img width="897" alt="Screenshot 2021-09-10 at 7 25 01 PM" src="https://user-images.githubusercontent.com/16541548/132871323-0fbc9fdd-afb5-41d7-b6a7-0b76dad5c7ea.png">

Refer invoice payment details page for details for column details.
<img width="1122" alt="Screenshot 2021-09-10 at 8 10 26 PM" src="https://user-images.githubusercontent.com/16541548/132871603-9bad6068-66a0-4a39-a4f6-0cb38daeaa3f.png">

**Comment by srivastava-jyoti** [comment]
@rathorevaibhav this is working fine on Uat. As per requirements, there is a different table having different columns for Indian and international invoices.

**Comment by rathorevaibhav** [comment]
@mohitsharma-22 can you check this for changes other than the following:
1. Currency conversion rate column.
2. Invoice Amount in the INR column.
3. Amount received in INR

These three items will be worked on separately and will be available for you later. Can you test the rest except these?

**Comment by gautam071** [comment]
@rathorevaibhav @mohitsharma-22 The USD to INR conversion is working in UAT perfectly. In local we can replicate only through API keys. When we replicate the API keys in local must be updated in UAT too.

**Comment by rathorevaibhav** [comment]
Closing this as the remaining items are being worked on in #814
