### ISSUE TITLE
Update Migrations for Effort Tracking

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#970]
**Is your feature request related to a problem? Please describe.**
We need to make migration to create some table and columns for effort tracking module. 

**Describe the solution you'd like**
Make migration as per the [Schema](https://docs.google.com/presentation/d/1jaByFL_NodzD1onxb7JGie3MFsNxfrMbdsEg9WFHVDk/edit#slide=id.p)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by rathorevaibhav** [comment]
This is complete. Closing.
