### ISSUE TITLE
Add steps for portal setup on macOS

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/portal#981]
**Describe the task**
Add steps for portal setup on macOS

**Expected behavior**
1. Update pre-requisites guide for macOS
2. Update installation guide for macOS

**Comment by rathorevaibhav** [comment]
@gautam071 the pre-requisites guide is not updated for macOS. Please check. It should have MAMP installation step.

**Comment by gautam071** [comment]
@rathorevaibhav  Added a PR for this issue

**Comment by rathorevaibhav** [comment]
Looks good. Closing.
