### ISSUE TITLE
Dashboard value error

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#990]
**Describe the bug**
There are errors occurring in the console for the chart values only occurs on the page where the chart is not called.

**Expected behavior**
The errors must not show on all the pages.

**Screenshots**
<img width="1440" alt="Screenshot 2021-09-15 at 10 33 20 PM" src="https://user-images.githubusercontent.com/73119570/133478134-25f28508-7abc-479d-b782-a55f46698209.png">

**Comment by rathorevaibhav** [comment]
This is working fine now. Thanks!

**Comment by GauravGusain98** [comment]
Opened by mistake. This has been tested. Hence closing this.
