### ISSUE TITLE
Update the prerequisites page

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#995]
**Describe the task**
The prerequisites page looks like the learning page make the prerequisites first and then add the learning

**Expected behavior**
- Make all the learning links in the learning tag under the prerequisites heading
- Make all links available for all the (Mac OS/Windows/Linux)
- Distinguish Between Prerequisites and Learning

**Comment by gautam071** [comment]
@rathorevaibhav This issue is completed in the above PR itself can you check and close the task

**Comment by rathorevaibhav** [comment]
This looks good. Closing.
