### ISSUE TITLE
The API for the conversion of USD to INR not found

### ISSUE THREAD

**Issue by gautam071** [ColoredCow/portal#998]
**Is your feature request related to a problem? Please describe.**
The API keys are not found in the local when opening the finance page

**Describe the solution you'd like**
    - Make the API key
    - Error message should pop up saying "the API server fails to produce the values"

**Additional context**
<img width="1440" alt="Screenshot 2021-09-16 at 2 10 33 PM" src="https://user-images.githubusercontent.com/73119570/133580193-6b63ebea-f3a6-4fde-a87c-276e1532cfed.png">

**Package Link**
1. https://github.com/orkhanahmadov/laravel-currencylayer

**Expected Outcome**
- [ ] The connection with external API should be made only if API key is available in the env file. If it's absent, then system should not make the API call and instead use a hardcoded value from config.

**Comment by rathorevaibhav** [comment]
This works great! Thanks @bharatsingh100 🎉
